import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def load_module(relative_path: str, module_name: str):
    spec = importlib.util.spec_from_file_location(module_name, REPO_ROOT / relative_path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


CLAUDE = load_module("scripts/export-claude-agents.py", "export_claude_agents_runtime")
COPILOT = load_module("scripts/export-copilot-agents.py", "export_copilot_agents_runtime")


class RuntimeExporterMigrationTest(unittest.TestCase):
    def assert_no_unresolved_neutral_refs(self, *roots: Path) -> None:
        for root in roots:
            for markdown_path in sorted(root.rglob("*.md")):
                content = markdown_path.read_text(encoding="utf-8")
                lines = content.splitlines()
                content = "\n".join(
                    line
                    for line in lines
                    if not line.startswith("<!-- Generated by scripts/export-")
                )
                try:
                    markdown_path.relative_to(root / "skills")
                except ValueError:
                    pass
                else:
                    content = CLAUDE.REPO_MANAGED_REF_RE.sub(
                        lambda match: (
                            ""
                            if match.group(1).removeprefix("./").startswith("scripts/")
                            else match.group(0)
                        ),
                        content,
                    )
                match = CLAUDE.REPO_MANAGED_REF_RE.search(content)
                self.assertIsNone(
                    match,
                    f"{markdown_path}: unresolved neutral reference "
                    f"{match.group(1) if match else ''}",
                )

    def test_neutral_defaults(self) -> None:
        expected = {
            "source": "agents",
            "modes": "modes.json",
            "profiles": "tools/agent-profiles",
        }
        for module in (CLAUDE, COPILOT):
            with self.subTest(runtime=module.__name__):
                self.assertEqual(module.DEFAULT_SOURCE_AGENTS, expected["source"])
                self.assertEqual(module.DEFAULT_MODES_FILE, expected["modes"])
                self.assertEqual(module.DEFAULT_PROFILE_DIR, expected["profiles"])

        self.assertEqual(
            CLAUDE.DEFAULT_MODEL_SET_DIR, "runtimes/claude/model-sets"
        )
        self.assertEqual(
            COPILOT.DEFAULT_MODEL_SET_DIR, "runtimes/copilot/model-sets"
        )
        for module in (CLAUDE, COPILOT):
            self.assertEqual(
                module.KNOWN_SOURCE_FRONTMATTER_KEYS,
                {"name", "description", "kind"},
            )

    def test_manifest_aliases_drive_input_adapters(self) -> None:
        manifest = REPO_ROOT / "modes.json"
        claude_aliases = CLAUDE.load_mode_aliases(manifest)
        copilot_aliases = COPILOT.load_mode_aliases(manifest)
        expected = ["general", "run-general", "monetize", "run-monetize"]

        self.assertEqual(claude_aliases["orchestrator-general"], expected)
        self.assertEqual(copilot_aliases["orchestrator-general"], expected)
        for module, aliases in (
            (CLAUDE, claude_aliases),
            (COPILOT, copilot_aliases),
        ):
            adapter = module.make_input_adapter(
                "orchestrator-general", aliases["orchestrator-general"]
            )
            for alias in expected:
                self.assertIn(f"`/{alias}`", adapter)

    def test_duplicate_manifest_alias_is_rejected(self) -> None:
        payload = {
            "version": 1,
            "modes": [
                {
                    "name": "flow",
                    "agent": "orchestrator-flow",
                    "aliases": ["flow"],
                },
                {
                    "name": "pipeline",
                    "agent": "orchestrator-pipeline",
                    "aliases": ["flow"],
                },
            ],
        }
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "modes.json"
            path.write_text(json.dumps(payload), encoding="utf-8")
            for module in (CLAUDE, COPILOT):
                with self.subTest(runtime=module.__name__):
                    with self.assertRaisesRegex(ValueError, "duplicates alias 'flow'"):
                        module.load_mode_aliases(path)

    def test_tier2_exporters_reject_reserved_goal_aliases(self) -> None:
        payload = {
            "version": 1,
            "modes": [
                {
                    "name": "general",
                    "agent": "orchestrator-general",
                    "aliases": ["general", "run-general", "run-goal"],
                }
            ],
        }
        with tempfile.TemporaryDirectory() as temp_dir:
            path = Path(temp_dir) / "modes.json"
            path.write_text(json.dumps(payload), encoding="utf-8")
            for module in (CLAUDE, COPILOT):
                with self.subTest(runtime=module.__name__):
                    with self.assertRaisesRegex(ValueError, "reserved for host-runtime"):
                        module.load_mode_aliases(path)

    def test_copilot_orchestrator_enables_required_agent_tool(self) -> None:
        content = COPILOT.build_agent_markdown(
            name="orchestrator-flow",
            description="Coordinate a bounded flow.",
            body="Coordinate work.\n",
            subagents=["executor", "reviewer"],
        )

        frontmatter = content.split("---", 2)[1]
        self.assertIn("tools:\n  - agent\n", frontmatter)
        self.assertIn("agents:\n  - executor\n  - reviewer\n", frontmatter)

    def test_claude_orchestrator_explicitly_disallows_agent_tool(self) -> None:
        content = CLAUDE.build_agent_markdown(
            name="orchestrator-flow",
            description="Coordinate a bounded flow.",
            body="Coordinate work.\n",
            tools=[],
        )

        frontmatter = content.split("---", 2)[1]
        self.assertIn("disallowedTools: Agent", frontmatter)

    def test_claude_runner_uses_fresh_continuations_without_send_message(self) -> None:
        adapter = CLAUDE.make_delegation_adapter(["executor", "reviewer"])

        self.assertIn('"continuation"', adapter)
        self.assertIn("continuation.agent", adapter)
        self.assertIn("fresh agent invocation", adapter)
        self.assertNotIn("SendMessage", adapter)

        runner = CLAUDE.RUNNER_PROTOCOL
        self.assertIn("continuation.agent", runner)
        self.assertIn("fresh invocation", runner)
        self.assertIn("do not use `SendMessage`", runner)
        self.assertNotIn("send collected results back via `SendMessage`", runner)

    def test_active_adapter_files_have_no_opencode_layout_dependency(self) -> None:
        relative_paths = (
            "scripts/export-claude-agents.py",
            "scripts/export-copilot-agents.py",
            "scripts/sync-runtime-support.py",
            "scripts/sync-codex-skills.py",
            "scripts/install-claude.sh",
            "scripts/install-claude.ps1",
            "scripts/install-copilot.sh",
            "scripts/install-copilot.ps1",
            "scripts/bootstrap-install-claude.sh",
            "scripts/bootstrap-install-claude.ps1",
            "scripts/bootstrap-install-copilot.sh",
            "scripts/bootstrap-install-copilot.ps1",
        )
        for relative_path in relative_paths:
            with self.subTest(path=relative_path):
                content = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
                self.assertNotIn("opencode/", content)
                self.assertNotIn("OpenCode", content)
                self.assertNotIn("agents-pipeline-opencode-bundle-", content)

    def test_tier2_bootstraps_require_runtime_support_sync_helper(self) -> None:
        expectations = {
            "scripts/bootstrap-install-claude.sh": (
                '"${bundle_dir}/scripts/sync-runtime-support.py"'
            ),
            "scripts/bootstrap-install-copilot.sh": (
                '"${bundle_dir}/scripts/sync-runtime-support.py"'
            ),
            "scripts/bootstrap-install-claude.ps1": (
                '(Join-Path $BundleDir "scripts/sync-runtime-support.py")'
            ),
            "scripts/bootstrap-install-copilot.ps1": (
                '(Join-Path $BundleDir "scripts/sync-runtime-support.py")'
            ),
        }
        for relative_path, required_entry in expectations.items():
            with self.subTest(path=relative_path):
                content = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
                self.assertIn(required_entry, content)

    def test_tier2_bootstraps_require_neutral_profile_manager(self) -> None:
        expectations = {
            "scripts/bootstrap-install-claude.sh": '"${bundle_dir}/tools/agent-profile.py"',
            "scripts/bootstrap-install-copilot.sh": '"${bundle_dir}/tools/agent-profile.py"',
            "scripts/bootstrap-install-claude.ps1": '(Join-Path $BundleDir "tools/agent-profile.py")',
            "scripts/bootstrap-install-copilot.ps1": '(Join-Path $BundleDir "tools/agent-profile.py")',
        }
        for relative_path, required_entry in expectations.items():
            with self.subTest(path=relative_path):
                content = (REPO_ROOT / relative_path).read_text(encoding="utf-8")
                self.assertIn(required_entry, content)

    def test_release_bundle_asserts_runtime_support_sync_helper(self) -> None:
        workflow = (
            REPO_ROOT / ".github" / "workflows" / "release-bundle.yml"
        ).read_text(encoding="utf-8")
        self.assertIn(
            'test -f "${BUNDLE_DIR}/scripts/sync-runtime-support.py"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/tools/agent-profile.py"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/scripts/sync-codex-skills.py"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/scripts/codex_skill_catalog.py"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/skills/run-pipeline/SKILL.md"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/skills/run-adaptive/SKILL.md"',
            workflow,
        )
        self.assertIn(
            'test -f "${BUNDLE_DIR}/skills/ui-communication-designer/SKILL.md"',
            workflow,
        )
        self.assertIn(
            'test ! -e "${BUNDLE_DIR}/skills/run-goal"',
            workflow,
        )

    def test_release_validates_and_packages_one_immutable_commit(self) -> None:
        ci_workflow = (
            REPO_ROOT / ".github" / "workflows" / "ci.yml"
        ).read_text(encoding="utf-8")
        release_workflow = (
            REPO_ROOT / ".github" / "workflows" / "release.yml"
        ).read_text(encoding="utf-8")
        bundle_workflow = (
            REPO_ROOT / ".github" / "workflows" / "release-bundle.yml"
        ).read_text(encoding="utf-8")

        self.assertIn("checkout_ref:", ci_workflow)
        self.assertGreaterEqual(
            ci_workflow.count("ref: ${{ inputs.checkout_ref || github.ref }}"),
            4,
        )
        self.assertIn(
            '"${EVENT_REF}" != "refs/tags/${REQUESTED_TAG}"',
            release_workflow,
        )
        self.assertIn(
            "checkout_ref: ${{ needs.resolve.outputs.sha }}",
            release_workflow,
        )
        self.assertIn("sha: ${{ steps.release_ref.outputs.sha }}", release_workflow)
        self.assertIn("RELEASE_SHA: ${{ github.sha }}", release_workflow)
        self.assertIn("tag: ${{ needs.resolve.outputs.tag }}", release_workflow)
        self.assertIn("EXPECTED_SHA: ${{ needs.resolve.outputs.sha }}", release_workflow)
        self.assertIn(
            "ref: ${{ inputs.checkout_ref || github.sha }}",
            bundle_workflow,
        )
        self.assertNotIn("git fetch --tags --force", bundle_workflow)

    def test_ci_runs_both_pester_suites_and_macos_installer_smoke(self) -> None:
        workflow = (
            REPO_ROOT / ".github" / "workflows" / "ci.yml"
        ).read_text(encoding="utf-8")

        self.assertEqual(workflow.count("Invoke-Pester -Path"), 1)
        self.assertIn('"tests/install-codex.Tests.ps1",', workflow)
        self.assertIn('"tests/install-runtime-profiles.Tests.ps1"', workflow)
        self.assertEqual(workflow.count(") -CI"), 1)
        self.assertNotIn("-EnableExit", workflow)
        self.assertIn("Validate macOS Bash installer and workspace profile", workflow)
        self.assertIn("profile_eligibility", workflow)
        self.assertIn("validate-minimum-runtimes:", workflow)
        self.assertIn('python-version: "3.11"', workflow)
        self.assertIn('node-version: "18"', workflow)
        self.assertIn("node scripts/validate-status-runtime-smoke.cjs", workflow)
        self.assertIn('actionlint_version="1.7.12"', workflow)

    def test_tier2_dry_runs_reject_empty_whitespace_and_file_targets(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            target_file = Path(temp_dir) / "not-a-directory"
            target_file.write_text("x", encoding="utf-8")
            for runtime in ("claude", "copilot"):
                for target in ("", "   ", target_file.as_posix()):
                    with self.subTest(runtime=runtime, target=target):
                        result = subprocess.run(
                            [
                                sys.executable,
                                (
                                    REPO_ROOT
                                    / "scripts"
                                    / f"export-{runtime}-agents.py"
                                ).as_posix(),
                                "--target-dir",
                                target,
                                "--dry-run",
                            ],
                            cwd=REPO_ROOT,
                            text=True,
                            capture_output=True,
                            check=False,
                        )
                        self.assertEqual(
                            result.returncode,
                            2,
                            result.stdout + result.stderr,
                        )

                        installer = subprocess.run(
                            [
                                "bash",
                                (
                                    REPO_ROOT / "scripts" / f"install-{runtime}.sh"
                                ).as_posix(),
                                "--target",
                                target,
                                "--dry-run",
                            ],
                            cwd=REPO_ROOT,
                            text=True,
                            capture_output=True,
                            check=False,
                        )
                        self.assertEqual(
                            installer.returncode,
                            2,
                            installer.stdout + installer.stderr,
                        )

    def test_all_exporters_reject_shell_active_paths_before_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for runtime in ("codex", "claude", "copilot"):
                cases = (
                    (root / f"{runtime}$target", None),
                    (root / f"{runtime}-target", root / "unsafe`support"),
                )
                for target, support_root in cases:
                    with self.subTest(
                        runtime=runtime,
                        target=target.name,
                        support_root=support_root,
                    ):
                        command = [
                            sys.executable,
                            (
                                REPO_ROOT
                                / "scripts"
                                / f"export-{runtime}-agents.py"
                            ).as_posix(),
                            "--source-agents",
                            (REPO_ROOT / "agents").as_posix(),
                            "--target-dir",
                            target.as_posix(),
                        ]
                        if support_root is not None:
                            command.extend(
                                [
                                    "--resolve-support-refs-to",
                                    support_root.as_posix(),
                                ]
                            )
                        result = subprocess.run(
                            command,
                            cwd=REPO_ROOT,
                            text=True,
                            capture_output=True,
                            check=False,
                        )
                        self.assertEqual(
                            result.returncode,
                            2,
                            result.stdout + result.stderr,
                        )
                        self.assertIn("unsafe in generated shell instructions", result.stderr)
                        self.assertFalse(target.exists())

    def test_bash_installers_reject_shell_active_targets_before_writing(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            for runtime in ("codex", "claude", "copilot"):
                with self.subTest(runtime=runtime):
                    target = root / f"{runtime}$target"
                    command = [
                        "bash",
                        (
                            REPO_ROOT / "scripts" / f"install-{runtime}.sh"
                        ).as_posix(),
                        "--target",
                        target.as_posix(),
                        "--no-backup",
                    ]
                    if runtime == "claude":
                        command.append("--no-runner")
                    result = subprocess.run(
                        command,
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )
                    self.assertEqual(
                        result.returncode,
                        2,
                        result.stdout + result.stderr,
                    )
                    self.assertIn("unsafe in generated shell instructions", result.stderr)
                    self.assertFalse(target.exists())

    def test_exporters_reject_managed_leaf_symlinks(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            victim = root / "victim.txt"
            victim.write_text("do not overwrite", encoding="utf-8")
            cases = (
                ("codex", "config.toml"),
                ("claude", "orchestrator-flow.md"),
                ("copilot", "orchestrator-flow.agent.md"),
            )
            for runtime, relative_output in cases:
                with self.subTest(runtime=runtime):
                    target = root / runtime
                    target.mkdir()
                    output = target / relative_output
                    output.parent.mkdir(parents=True, exist_ok=True)
                    try:
                        output.symlink_to(victim)
                    except (OSError, NotImplementedError):
                        self.skipTest("symbolic links are unavailable")
                    result = subprocess.run(
                        [
                            sys.executable,
                            (
                                REPO_ROOT
                                / "scripts"
                                / f"export-{runtime}-agents.py"
                            ).as_posix(),
                            "--target-dir",
                            target.as_posix(),
                            "--strict",
                            "--dry-run",
                        ],
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )
                    self.assertEqual(result.returncode, 2)
                    self.assertIn("symbolic link", result.stderr)
                    self.assertEqual(
                        victim.read_text(encoding="utf-8"), "do not overwrite"
                    )

    @unittest.skipIf(
        sys.platform == "win32", "Windows link handling is covered by Pester"
    )
    def test_all_exporters_reject_symlinked_target_directories(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            outside = root / "outside"
            outside.mkdir()
            sentinel = outside / "user-owned.txt"
            sentinel.write_text("preserve target contents\n", encoding="utf-8")

            for runtime in ("codex", "claude", "copilot"):
                with self.subTest(runtime=runtime):
                    target = root / f"{runtime}-target-link"
                    try:
                        target.symlink_to(outside, target_is_directory=True)
                    except (OSError, NotImplementedError):
                        self.skipTest("symbolic links are unavailable")

                    result = subprocess.run(
                        [
                            sys.executable,
                            (
                                REPO_ROOT
                                / "scripts"
                                / f"export-{runtime}-agents.py"
                            ).as_posix(),
                            "--source-agents",
                            (REPO_ROOT / "agents").as_posix(),
                            "--target-dir",
                            target.as_posix(),
                            "--strict",
                            "--dry-run",
                        ],
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )

                    self.assertEqual(
                        result.returncode,
                        2,
                        result.stdout + result.stderr,
                    )
                    self.assertIn("symbolic link", result.stderr)
                    self.assertEqual(
                        sentinel.read_text(encoding="utf-8"),
                        "preserve target contents\n",
                    )
                    self.assertEqual(
                        sorted(path.name for path in outside.iterdir()),
                        [sentinel.name],
                    )
                    target.unlink()

    def test_tier2_preflight_rejects_symlinks_before_support_sync(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            victim = root / "victim.txt"
            victim.write_text("preserve me", encoding="utf-8")
            cases = (
                ("claude", "orchestrator-flow.md", ["--no-runner"]),
                ("copilot", "orchestrator-flow.agent.md", []),
            )
            for runtime, relative_output, extra_args in cases:
                with self.subTest(runtime=runtime):
                    target = root / f"{runtime} home" / "agents"
                    target.mkdir(parents=True)
                    try:
                        (target / relative_output).symlink_to(victim)
                    except (OSError, NotImplementedError):
                        self.skipTest("symbolic links are unavailable")
                    result = subprocess.run(
                        [
                            "bash",
                            (
                                REPO_ROOT / "scripts" / f"install-{runtime}.sh"
                            ).as_posix(),
                            "--target",
                            target.as_posix(),
                            "--no-backup",
                            *extra_args,
                        ],
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )
                    self.assertEqual(result.returncode, 2)
                    self.assertFalse((target.parent / "agents-pipeline").exists())
                    self.assertEqual(
                        victim.read_text(encoding="utf-8"), "preserve me"
                    )

    def test_claude_exporter_rejects_symlinked_runner_file(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            target = root / "agents"
            runner = root / "CLAUDE.md"
            victim = root / "victim.md"
            victim.write_text("preserve runner target\n", encoding="utf-8")
            try:
                runner.symlink_to(victim)
            except (OSError, NotImplementedError):
                self.skipTest("symbolic links are unavailable")

            result = subprocess.run(
                [
                    sys.executable,
                    (REPO_ROOT / "scripts" / "export-claude-agents.py").as_posix(),
                    "--target-dir",
                    target.as_posix(),
                    "--claude-md",
                    runner.as_posix(),
                    "--strict",
                    "--dry-run",
                ],
                cwd=REPO_ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 2)
            self.assertIn("symbolic link", result.stderr)
            self.assertEqual(
                victim.read_text(encoding="utf-8"), "preserve runner target\n"
            )

    def test_strict_copilot_export_bounds_size_and_loads_oversized_agents(self) -> None:
        oversized_agents = ("orchestrator-modernize", "orchestrator-pipeline")
        for agent_name in oversized_agents:
            source = REPO_ROOT / "agents" / f"{agent_name}.md"
            self.assertGreater(
                len(source.read_text(encoding="utf-8")),
                COPILOT.COPILOT_MAX_AGENT_CHARS,
            )

        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            target = root / "Copilot Export With Spaces"
            support_root = root / "Managed Support With Spaces"
            result = subprocess.run(
                [
                    sys.executable,
                    (REPO_ROOT / "scripts" / "export-copilot-agents.py").as_posix(),
                    "--source-agents",
                    (REPO_ROOT / "agents").as_posix(),
                    "--target-dir",
                    target.as_posix(),
                    "--resolve-support-refs-to",
                    support_root.as_posix(),
                    "--strict",
                ],
                cwd=REPO_ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

            generated = sorted(target.glob("*.agent.md"))
            self.assertTrue(generated)
            for output_path in generated:
                with self.subTest(output=output_path.name):
                    self.assertLessEqual(
                        len(output_path.read_text(encoding="utf-8")),
                        COPILOT.COPILOT_MAX_AGENT_CHARS,
                    )

            for agent_name in oversized_agents:
                definition_path = (
                    support_root.resolve() / "agents" / f"{agent_name}.md"
                ).as_posix()
                for suffix in ("", "-solo"):
                    output_path = target / f"{agent_name}{suffix}.agent.md"
                    content = output_path.read_text(encoding="utf-8")
                    self.assertIn("## Canonical Definition Loading", content)
                    self.assertIn(f"`{definition_path}`", content)
                    self.assertIn(
                        "interpret every formal Codex `$run-<mode>` reference as the "
                        "corresponding Copilot `/run-<mode>` compatibility alias",
                        content,
                    )
                    self.assertIn(
                        "do not emit a `$run-*` invocation to a Copilot user",
                        content,
                    )

    def test_copilot_settings_snippet_uses_path_boolean_object(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            target = Path(temp_dir) / "Copilot Settings With Spaces" / "agents"
            result = subprocess.run(
                [
                    "bash",
                    (REPO_ROOT / "scripts" / "install-copilot.sh").as_posix(),
                    "--target",
                    target.as_posix(),
                    "--dry-run",
                    "--no-backup",
                ],
                cwd=REPO_ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

            marker = "Suggested VS Code settings.json snippet:\n"
            self.assertIn(marker, result.stdout)
            payload_text = result.stdout.split(marker, 1)[1].lstrip()
            settings, _ = json.JSONDecoder().raw_decode(payload_text)
            locations = settings["chat.agentFilesLocations"]
            self.assertIsInstance(locations, dict)
            self.assertEqual(locations, {target.resolve().as_posix(): True})

    def test_tier2_bash_installs_sync_and_rewrite_support_tree_with_spaces(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            root = Path(temp_dir)
            runtime_cases = (
                ("claude", "orchestrator-flow.md", ["--no-runner"]),
                ("copilot", "orchestrator-flow.agent.md", []),
            )
            for runtime, flow_filename, extra_args in runtime_cases:
                with self.subTest(runtime=runtime):
                    target = root / f"{runtime.title()} Runtime With Spaces" / "agents"
                    result = subprocess.run(
                        [
                            "bash",
                            (
                                REPO_ROOT / "scripts" / f"install-{runtime}.sh"
                            ).as_posix(),
                            "--target",
                            target.as_posix(),
                            "--no-backup",
                            *extra_args,
                        ],
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )
                    self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

                    support_root = target.parent / "agents-pipeline"
                    marker_path = support_root / ".agents-pipeline-support.json"
                    self.assertEqual(
                        json.loads(marker_path.read_text(encoding="utf-8")),
                        {
                            "installed_root": support_root.resolve().as_posix(),
                            "tool": "agents_pipeline.sync-runtime-support",
                            "version": 3,
                        },
                    )
                    self.assertTrue((support_root / "tools" / "status-event.js").is_file())

                    self.assert_no_unresolved_neutral_refs(target, support_root)

                    quoted_status_command = (
                        f'node "{support_root.as_posix()}/tools/status-event.js"'
                    )
                    for flow_path in (
                        target / flow_filename,
                        support_root / "agents" / "orchestrator-flow.md",
                    ):
                        content = flow_path.read_text(encoding="utf-8")
                        self.assertIn(quoted_status_command, content)
                        self.assertNotIn(
                            f"node {support_root.as_posix()}/tools/status-event.js",
                            content,
                        )

    def test_claude_dry_run_accepts_target_with_missing_parent(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            target = Path(temp_dir) / "new-parent" / ".claude" / "agents"
            result = subprocess.run(
                [
                    "bash",
                    (REPO_ROOT / "scripts" / "install-claude.sh").as_posix(),
                    "--target",
                    target.as_posix(),
                    "--dry-run",
                    "--no-backup",
                ],
                cwd=REPO_ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertFalse(target.exists())

    def test_bootstrap_shells_are_compatible_with_macos_bash_case_handling(self) -> None:
        for runtime in ("codex", "claude", "copilot"):
            content = (
                REPO_ROOT / "scripts" / f"bootstrap-install-{runtime}.sh"
            ).read_text(encoding="utf-8")
            self.assertNotRegex(content, r"\$\{[A-Z_]+,,\}")
            self.assertIn("supports v0.28.0 or newer", content)

    def test_bash_bootstraps_reject_switch_like_targets_before_network(self) -> None:
        for runtime in ("codex", "claude", "copilot"):
            for target in ("--dry-run", "  --dry-run"):
                with self.subTest(runtime=runtime, target=target):
                    result = subprocess.run(
                        [
                            "bash",
                            (
                                REPO_ROOT
                                / "scripts"
                                / f"bootstrap-install-{runtime}.sh"
                            ).as_posix(),
                            "--target",
                            target,
                        ],
                        cwd=REPO_ROOT,
                        text=True,
                        capture_output=True,
                        check=False,
                    )
                    self.assertEqual(result.returncode, 2)
                    self.assertIn("looks like a switch", result.stderr)


if __name__ == "__main__":
    unittest.main()
