#!/usr/bin/env python3
import argparse
import json
import os
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
if SCRIPT_DIR.as_posix() not in sys.path:
    sys.path.insert(0, SCRIPT_DIR.as_posix())

from agent_model_profiles import (  # noqa: E402
    RuntimeModelSetting,
    load_model_set,
    load_profile,
    resolve_agent_model_settings,
)
from codex_mode_aliases import (  # noqa: E402
    MODE_DEFINITION_SCOPE_LINE,
    MODE_ALIAS_AUTHORIZATION_GUARD_LINE,
    MODE_ALIAS_DEFINITION_LOOKUP_SENTENCE,
    MODE_ALIAS_DO_NOT_SPAWN_LINE,
    MODE_ALIAS_NO_BYPASS_SENTENCE,
    MODE_ALIAS_OBEY_DEFINITION_SENTENCE,
    MODE_ALIAS_SKILL_EQUIVALENCE_LINE,
    SAME_SESSION_EXCEPTIONS_LINE,
    SAME_SESSION_NO_RELOAD_LINE,
    WORKSPACE_PROFILE_PREFLIGHT_LINE,
    build_natural_language_mode_aliases,
    build_slash_mode_aliases,
    inline_code_list,
    load_mode_agents,
    ordered_unique,
)
from path_safety import is_linklike, validate_generated_shell_path  # noqa: E402


FRONTMATTER_BOUNDARY = re.compile(r"^\s*---\s*$")
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$")
TOOL_ENTRY_RE = re.compile(r"^  ([A-Za-z0-9_-]+)\s*:\s*(true|false)\s*$")
AGENT_REF_RE = re.compile(r"@([a-z0-9][a-z0-9-]*(?:\*)?)")
ROLE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
REPO_MANAGED_REF_RE = re.compile(
    r"(?<![A-Za-z0-9_./:-])((?:agents|protocols|scripts|skills|tools)/[A-Za-z0-9_./-]+)"
)
FENCE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(.*)$")
HANDOFF_PROTOCOL_RE = re.compile(
    r"(?ms)^# HANDOFF PROTOCOL \(GLOBAL\)\n.*?(?=^## AGENT RESPONSIBILITY MATRIX|^# )"
)
RESPONSIBILITY_MATRIX_RE = re.compile(
    r"(?ms)^## AGENT RESPONSIBILITY MATRIX\n\n"
    r"\| Agent \| Primary Responsibility \| Forbidden Actions \|\n"
    r"\|[-| ]+\|\n"
    r"(?P<rows>(?:\|.*\|\n)+)"
)
FLAG_PARSING_INTRO_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} FLAG PARSING PROTOCOL(?: \([^)]+\))?)\n\n"
    r"Parse the workflow invocation input\.\n\n"
    r"Parse `raw_input`: tokens before the first `--\*` flag form `main_task_prompt`; `--\*` tokens are flags\.(?P<resume> If `main_task_prompt` is empty and `resume_mode = true`, treat as resume-only invocation\.)?\n"
)
RESPONSE_MODE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} RESPONSE MODE \(DEFAULT\))\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)
CONFIRM_VERBOSE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} CONFIRM / VERBOSE PROTOCOL)\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)
CHECKPOINT_PROTOCOL_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} CHECKPOINT PROTOCOL)\n\n(?P<body>.*?)(?=^#{1,2} |\Z)"
)
RUN_STATUS_PROTOCOL_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} (?:RUN STATUS PROTOCOL|STATUS ARTIFACT PROTOCOL))\n\n(?P<body>.*?)(?=^#{1,2} |\Z)"
)

KNOWN_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "kind",
}

SCALAR_FRONTMATTER_KEYS = {
    "name",
    "description",
    "kind",
}

UNSUPPORTED_VALUE_PREFIXES = ("[", "{", "|", ">")

ORCHESTRATOR_PREFIX = "orchestrator-"
GENERATED_MARKER = "# Generated by scripts/export-codex-agents.py"
DEFAULT_PROFILE_DIR = "tools/agent-profiles"
DEFAULT_MODEL_SET_DIR = "runtimes/codex/model-sets"


@dataclass
class AgentSource:
    path: Path
    file_stem: str
    name: str
    description: str
    body: str
    fm_keys: Set[str]
    kind: str = "subagent"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_quotes(value: str) -> str:
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        return value[1:-1]
    return value


def parse_scalar_frontmatter_value(path: Path, key: str, raw_value: str) -> str:
    value = raw_value.strip()
    if not value:
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' must use a single-line scalar value"
        )
    if value.startswith(UNSUPPORTED_VALUE_PREFIXES):
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' uses unsupported structured value '{value}'"
        )
    return strip_quotes(value)


def parse_frontmatter(
    content: str, path: Path
) -> Tuple[Dict[str, str], Dict[str, bool], str]:
    lines = content.splitlines()
    if not lines or not FRONTMATTER_BOUNDARY.match(lines[0]):
        raise ValueError(f"{path.as_posix()}: missing frontmatter block")

    end_idx: Optional[int] = None
    for idx in range(1, len(lines)):
        if FRONTMATTER_BOUNDARY.match(lines[idx]):
            end_idx = idx
            break
    if end_idx is None:
        raise ValueError(f"{path.as_posix()}: unterminated frontmatter block")

    fm: Dict[str, str] = {}
    tools: Dict[str, bool] = {}
    saw_tools = False
    frontmatter_lines = lines[1:end_idx]
    idx = 0
    while idx < len(frontmatter_lines):
        line = frontmatter_lines[idx]
        if not line.strip():
            raise ValueError(
                f"{path.as_posix()}: blank lines are not allowed inside frontmatter"
            )
        if line[:1].isspace():
            raise ValueError(
                f"{path.as_posix()}: unexpected indented frontmatter line '{line}'"
            )

        match = TOP_LEVEL_KEY_RE.match(line)
        if match is None:
            raise ValueError(f"{path.as_posix()}: malformed frontmatter line '{line}'")

        key = match.group(1).strip()
        raw_value = match.group(2).strip()
        if key in {"model", "provider"}:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported; configure model/provider in runtime config instead"
            )
        if key not in KNOWN_SOURCE_FRONTMATTER_KEYS:
            raise ValueError(f"{path.as_posix()}: unsupported frontmatter key '{key}'")
        if key in fm or (key == "tools" and saw_tools):
            raise ValueError(f"{path.as_posix()}: duplicate frontmatter key '{key}'")

        if key == "tools":
            saw_tools = True
            if raw_value:
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must not have an inline value"
                )
            idx += 1
            if idx >= len(frontmatter_lines) or not frontmatter_lines[idx].startswith(
                "  "
            ):
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must contain indented boolean entries"
                )
            while idx < len(frontmatter_lines) and frontmatter_lines[idx].startswith(
                "  "
            ):
                tool_line = frontmatter_lines[idx]
                tool_match = TOOL_ENTRY_RE.match(tool_line)
                if tool_match is None:
                    raise ValueError(
                        f"{path.as_posix()}: malformed tools entry '{tool_line}'"
                    )
                tool_name = tool_match.group(1)
                if tool_name in tools:
                    raise ValueError(
                        f"{path.as_posix()}: duplicate tools entry '{tool_name}'"
                    )
                tools[tool_name] = tool_match.group(2) == "true"
                idx += 1
            continue

        if key not in SCALAR_FRONTMATTER_KEYS:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported in this exporter"
            )
        fm[key] = parse_scalar_frontmatter_value(path, key, raw_value)
        idx += 1

    body = "\n".join(lines[end_idx + 1 :])
    if content.endswith("\n"):
        body += "\n"
    return fm, tools, body


def parse_source_agents(source_agents_dir: Path) -> List[AgentSource]:
    agents: List[AgentSource] = []
    for path in sorted(source_agents_dir.glob("*.md")):
        source = read_text(path)
        fm, tools, body = parse_frontmatter(source, path)
        name = fm.get("name", "").strip()
        description = fm.get("description", "").strip()
        kind = fm.get("kind", "").strip()
        if not name:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'name'"
            )
        if not description:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'description'"
            )
        if kind not in {"primary", "subagent"}:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key 'kind' must be 'primary' or 'subagent'"
            )
        agents.append(
            AgentSource(
                path=path,
                file_stem=path.stem,
                name=name,
                description=description,
                body=body,
                fm_keys=set(fm.keys()) | ({"tools"} if tools else set()),
                kind=kind,
            )
        )
    return agents


def parse_catalog_agents(catalog_path: Path) -> Set[str]:
    if not catalog_path.exists():
        return set()
    rows = read_text(catalog_path).splitlines()
    agents: Set[str] = set()
    for line in rows:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [part.strip() for part in stripped.split("|")]
        if len(parts) < 3:
            continue
        agent = parts[1]
        if agent in {"", "Agent"}:
            continue
        if set(agent) <= {"-"}:
            continue
        agents.add(agent)
    return agents


def build_agent_mode_aliases(mode_agents: Dict[str, str]) -> Dict[str, List[str]]:
    aliases: Dict[str, List[str]] = {}
    for mode_name, agent_name in mode_agents.items():
        if not agent_name.startswith(ORCHESTRATOR_PREFIX):
            continue
        aliases.setdefault(agent_name, []).append(mode_name)
    return aliases


def compact_markdown(text: str) -> str:
    lines = text.splitlines()
    compacted: List[str] = []
    pending_blank = False
    in_fence = False
    fence_token = ""

    for line in lines:
        fence_match = FENCE_RE.match(line)
        if in_fence:
            compacted.append(line)
            if fence_match and line.strip() == fence_token:
                in_fence = False
                fence_token = ""
            continue

        if fence_match:
            if pending_blank and compacted:
                compacted.append("")
                pending_blank = False
            compacted.append(line)
            in_fence = True
            fence_token = fence_match.group(1)
            continue

        stripped = line.rstrip()
        if not stripped:
            pending_blank = True
            continue

        if pending_blank and compacted:
            compacted.append("")
            pending_blank = False
        compacted.append(stripped)

    out = "\n".join(compacted)
    if text.endswith("\n"):
        out += "\n"
    return out


def ensure_sentence(text: str) -> str:
    return text if text.endswith((".", "!", "?")) else f"{text}."


def minify_handoff_protocol(text: str) -> str:
    match = HANDOFF_PROTOCOL_RE.search(text)
    if not match:
        return text

    section = match.group(0)
    general_match = re.search(
        r"(?m)^## General Handoff Rules\n\n(?P<bullets>(?:- [^\n]+\n)+)",
        section,
    )
    if not general_match:
        return text

    lines = ["# HANDOFF PROTOCOL (GLOBAL)", ""]
    lines.extend(line.rstrip() for line in general_match.group("bullets").strip().splitlines())
    lines.append(
        "- Orchestrator -> subagent: selected for specialization; stay within scope; satisfy the provided Definition of Done exactly."
    )

    if "## EXECUTOR -> REVIEWER HANDOFF" in section:
        lines.append(
            "- Executor -> reviewer: only the scoped DoD and required evidence count; adequate targeted evidence is sufficient, and broader proof needs a concrete uncovered path."
        )
    if "## REVIEWER -> ORCHESTRATOR HANDOFF" in section:
        lines.append(
            "- Reviewer -> orchestrator: a failed review is evidence, not automatic edit authorization. If `status = fail` and `test_only = false`, apply the materiality gate to each followup and route only admitted `required_followups` through the narrowest repair, up to `max_retry_rounds`; if `test_only = true`, skip retries; stop and report blockers when failure persists."
        )

    replacement = "\n".join(lines) + "\n\n"
    return text[: match.start()] + replacement + text[match.end() :]


def minify_agent_responsibility_matrix(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets: List[str] = []
        for raw_row in match.group("rows").strip().splitlines():
            cells = [cell.strip() for cell in raw_row.strip().strip("|").split("|")]
            if len(cells) != 3 or not all(cells):
                return match.group(0)
            bullets.append(
                f"- `{cells[0]}`: {ensure_sentence(cells[1])} Forbidden: {ensure_sentence(cells[2])}"
            )
        return "## AGENT RESPONSIBILITY MATRIX\n\n" + "\n".join(bullets) + "\n"

    return RESPONSIBILITY_MATRIX_RE.sub(repl, text, count=1)


def minify_flag_parsing_intro(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        resume = match.group("resume") or ""
        return (
            f"{match.group('heading')}\n\n"
            "Parse `raw_input`: tokens before the first `--*` flag form `main_task_prompt`; `--*` tokens are flags."
            f"{resume}\n"
        )

    return FLAG_PARSING_INTRO_RE.sub(repl, text, count=1)


def minify_response_mode(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        section = match.group("bullets")
        autopilot_clause = " and `autopilot_mode = false`" if "autopilot_mode = false" in section else ""
        return (
            f"{match.group('heading')}\n\n"
            "- Default to concise final-only reporting: outcome, key deliverables, blockers/errors. Emit stage-by-stage progress only when `--confirm` or `--verbose` requires it"
            f"{autopilot_clause}.\n"
        )

    return RESPONSE_MODE_RE.sub(repl, text, count=1)


def minify_confirm_verbose_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets = [line.strip()[2:] for line in match.group("bullets").strip().splitlines()]
        if len(bullets) < 2:
            return match.group(0)

        confirm_line = bullets[0]
        verbose_line = bullets[1]
        if "Proceed? [yes / feedback / abort]" not in confirm_line or "On abort: checkpoint and stop." not in confirm_line:
            return match.group(0)

        confirm_label = "`confirm_mode` (when not autopilot)" if "when not autopilot" in confirm_line else "`confirm_mode`"
        waiting_clause = "update status to `waiting_for_user` and " if "waiting_for_user" in confirm_line else ""
        verbose_line = verbose_line.replace("`verbose_mode` (implies confirm): also ", "`verbose_mode` (implies confirm): ")

        return (
            f"{match.group('heading')}\n\n"
            f"- {confirm_label}: after each stage, {waiting_clause}pause with `Proceed? [yes / feedback / abort]`; on abort checkpoint and stop.\n"
            f"- {verbose_line}\n"
        )

    return CONFIRM_VERBOSE_RE.sub(repl, text, count=1)


def minify_checkpoint_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        body = match.group("body")
        if (
            "<run_output_dir>/checkpoint.json" not in body
            or "checkpoint.schema.json" not in body
        ):
            return match.group(0)
        return (
            f"{match.group('heading')}\n\n"
            "After each successful stage, run `node tools/status-event.js --event stage.completed --payload-json '<json>'` so the runtime-neutral writer updates `<run_output_dir>/checkpoint.json` (schema: `protocols/schemas/checkpoint.schema.json`). Use `checkpoint.updated` with a non-empty `flags` delta when a derived flag must be persisted without marking the current stage complete.\n\n"
        )

    return CHECKPOINT_PROTOCOL_RE.sub(repl, text, count=1)


def minify_run_status_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        body = match.group("body")
        heading = match.group("heading")
        if (
            "<run_output_dir>/status/run-status.json" not in body
            or "PIPELINE_PROTOCOL.md" not in body
        ):
            return match.group(0)

        if "Use the expanded status layout (`tasks/<task_id>.json`, `agents/<agent_id>.json`) once task decomposition begins at Stage 3." in body:
            lines = [
                heading,
                "",
                "- Emit updates with `node tools/status-event.js --event <event> --payload-json '<json>'` for `<run_output_dir>/status/run-status.json` per `protocols/PIPELINE_PROTOCOL.md`; preserve `working_project_dir` unchanged when present.",
                "- Use expanded status files from Stage 3: `tasks/<task_id>.json` and `agents/<agent_id>.json`.",
                "- Event vocabulary: `run.started`/`run.resumed`, conditional `checkpoint.updated`, `stage.completed`, `tasks.registered`, `task.updated`, `agent.started`/`agent.heartbeat`/`agent.finished`, and `run.finished`.",
                "- Prefer `--event batch` for related same-run deltas; keep standalone heartbeats coarse and skip redundant ones.",
            ]
            return "\n".join(lines) + "\n\n"

        if "Use the expanded status layout once Stage 2 creates the task list." in body:
            lines = [
                heading,
                "",
                "- Emit updates with `node tools/status-event.js --event <event> --payload-json '<json>'` for `<run_output_dir>/status/run-status.json` per `protocols/PIPELINE_PROTOCOL.md`; prefer `--event batch` for same-run task/agent deltas.",
                "- Preserve `working_project_dir` unchanged when provided; if the runtime cannot honor a required delegated worktree, stop instead of silently using the caller repo.",
                "- Use expanded status files after Stage 2 creates the task list.",
                "- Event vocabulary: `run.started`/`run.resumed`, conditional `checkpoint.updated`, `stage.completed`, `tasks.registered`, `task.updated`, `agent.started`/`agent.heartbeat`/`agent.finished`, and `run.finished`. Keep standalone heartbeats coarse unless an earlier semantic change makes one useful.",
            ]
            return "\n".join(lines) + "\n\n"

        if "target_project_dir" in body and "working_project_dir" in body:
            lines = [
                heading,
                "",
                "- Emit updates with `node tools/status-event.js --event <event> --payload-json '<json>'` for `<run_output_dir>/status/run-status.json` (`layout = run-only`) per `protocols/PIPELINE_PROTOCOL.md`.",
                "- Keep modernization-planning status/checkpoint writes anchored to the source-project run root; do not pass `target_project_dir` as `working_project_dir` for planning events.",
                "- When the current/main agent transitions into the Pipeline workflow, preserve `working_project_dir` so target-local status/checkpoint files land in the target repo; do not spawn another primary orchestrator.",
            ]
            return "\n".join(lines) + "\n\n"

        if "(`layout = run-only`)" in body:
            return (
                f"{heading}\n\n"
                "Emit updates with `node tools/status-event.js --event <event> --payload-json '<json>'` for `<run_output_dir>/status/run-status.json` (`layout = run-only`) per `protocols/PIPELINE_PROTOCOL.md`.\n\n"
            )

        return match.group(0)

    return RUN_STATUS_PROTOCOL_RE.sub(repl, text, count=1)


def minify_orchestrator_runtime_body(agent_name: str, text: str) -> str:
    if not agent_name.startswith(ORCHESTRATOR_PREFIX):
        return text

    text = minify_handoff_protocol(text)
    text = minify_agent_responsibility_matrix(text)
    text = minify_flag_parsing_intro(text)
    text = minify_response_mode(text)
    text = minify_checkpoint_protocol(text)
    text = minify_run_status_protocol(text)
    return minify_confirm_verbose_protocol(text)


def expand_ref_token(
    token: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    if token == "executor-*":
        return ["executor"], []
    if token.endswith("*"):
        return [], [token]
    if token in available_agents:
        return [token], []
    return [], [token]


def extract_subagents(
    body: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    resolved: List[str] = []
    unresolved: List[str] = []
    for match in AGENT_REF_RE.finditer(body):
        token = match.group(1)
        expanded, unknown = expand_ref_token(token, available_agents)
        resolved.extend(expanded)
        unresolved.extend(unknown)
    return ordered_unique(resolved), ordered_unique(unresolved)


def make_input_adapter(agent_name: str, mode_aliases: Optional[Sequence[str]] = None) -> str:
    aliases = ordered_unique(
        [alias for alias in (mode_aliases or []) if alias.strip()]
        or [agent_name[len(ORCHESTRATOR_PREFIX) :]]
    )
    slash_aliases = build_slash_mode_aliases(aliases)
    natural_aliases = build_natural_language_mode_aliases(aliases)
    return (
        "## Codex Input Adapter\n\n"
        "Use the user's latest message as `raw_input`.\n"
        f"Recognize only these explicit leading slash mode aliases: {inline_code_list(slash_aliases)}.\n"
        f"Also accept only these allowlisted natural-language leading phrases: {inline_code_list(natural_aliases)}.\n"
        f"{MODE_ALIAS_SKILL_EQUIVALENCE_LINE}\n"
        f"{WORKSPACE_PROFILE_PREFLIGHT_LINE}\n"
        f"{MODE_ALIAS_AUTHORIZATION_GUARD_LINE}\n"
        f"{MODE_ALIAS_DO_NOT_SPAWN_LINE}\n"
        f"{MODE_ALIAS_DEFINITION_LOOKUP_SENTENCE}\n"
        f"{MODE_ALIAS_OBEY_DEFINITION_SENTENCE}\n"
        f"{MODE_ALIAS_NO_BYPASS_SENTENCE}\n"
        f"{SAME_SESSION_NO_RELOAD_LINE}\n"
        f"{SAME_SESSION_EXCEPTIONS_LINE}\n"
        f"{MODE_DEFINITION_SCOPE_LINE}\n"
        "If `raw_input` starts with one of them, strip only that leading token/phrase after applying the definition, then apply the existing flag parsing unchanged.\n"
        "Do not infer a mode alias from later mentions or generic prose.\n"
    )


def make_role_reference_adapter() -> str:
    return (
        "## Codex Agent Role Adapter\n\n"
        "Interpret source `@agent-name` references as generated role names from `.codex/config.toml`.\n"
        "When routing work, use those role names directly.\n"
    )


def detect_installed_support_root(source_agents_dir: Path) -> Optional[str]:
    support_root = source_agents_dir.resolve().parent
    marker_path = support_root / ".agents-pipeline-support.json"
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return None
    if not isinstance(marker, dict) or marker.get("tool") != "agents_pipeline.sync-runtime-support":
        return None
    if type(marker.get("version")) is not int or marker.get("version") not in (1, 2, 3):
        return None
    if marker.get("version") == 3 and isinstance(marker.get("installed_root"), str):
        return Path(marker["installed_root"]).expanduser().resolve().as_posix()
    return support_root.as_posix()


def rewrite_neutral_refs(
    text: str,
    support_root_ref: Optional[str],
    source_support_root_ref: Optional[str] = None,
) -> str:
    if not support_root_ref:
        return text

    normalized_root = support_root_ref.rstrip("/\\")
    if source_support_root_ref:
        text = text.replace(source_support_root_ref.rstrip("/\\"), normalized_root)
    text = re.sub(
        r"\bnode\s+[\"']?(?:\./)?tools/(status-event|reasoning-policy|capability-recovery|codex-child-trace)\.js[\"']?",
        lambda match: f'node "{normalized_root}/tools/{match.group(1)}.js"',
        text,
    )

    def repl(match: re.Match[str]) -> str:
        repo_relative = match.group(1)
        return f"{normalized_root}/{repo_relative}"

    return REPO_MANAGED_REF_RE.sub(repl, text)


def adapt_body(
    agent_name: str,
    original_body: str,
    has_subagents: bool,
    *,
    agent_kind: str = "subagent",
    mode_aliases: Optional[Sequence[str]] = None,
    support_root_ref: Optional[str] = None,
    source_support_root_ref: Optional[str] = None,
) -> str:
    body = original_body.replace("$ARGUMENTS", "raw_input")
    body = minify_orchestrator_runtime_body(agent_name, body)
    blocks: List[str] = []
    if agent_name.startswith(ORCHESTRATOR_PREFIX):
        blocks.append(make_input_adapter(agent_name, mode_aliases))
    if has_subagents:
        blocks.append(make_role_reference_adapter())
    if agent_kind == "subagent":
        blocks.append(
            "# CODEX CHILD DELEGATION\n\n"
            "- This exported subagent is a leaf worker. Do not spawn or delegate "
            "to another agent; return blockers to the parent orchestrator.\n"
        )
    blocks.append(body.lstrip("\n"))
    adapted = compact_markdown("\n\n".join(blocks).rstrip() + "\n")
    return rewrite_neutral_refs(adapted, support_root_ref, source_support_root_ref)


def toml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_multiline_string(value: str) -> str:
    normalized = value.rstrip("\n")
    lines = normalized.split("\n") if normalized else [""]
    escaped = [json.dumps(line, ensure_ascii=False)[1:-1] for line in lines]
    return '"""\n' + "\n".join(escaped) + '\n"""'


def resolve_runtime_model_settings(
    agent_names: Sequence[str], args: argparse.Namespace, *, runtime: str
) -> Dict[str, RuntimeModelSetting]:
    if (
        args.uniform_model is None
        and (args.agent_profile or args.model_set)
        and not (args.agent_profile and args.model_set)
    ):
        raise ValueError(
            "--agent-profile and --model-set must be supplied together unless --uniform-model is used"
        )

    profile = (
        load_profile(args.agent_profile, args.profile_dir, runtime)
        if args.agent_profile
        else None
    )
    model_set = (
        load_model_set(args.model_set, args.model_set_dir, runtime)
        if args.model_set
        else None
    )
    return resolve_agent_model_settings(
        agent_names,
        profile,
        model_set,
        uniform_model=args.uniform_model,
        runtime=runtime,
    )


def build_role_config(
    agent: AgentSource,
    body: str,
    model_setting: Optional[RuntimeModelSetting] = None,
) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        f"# Source: {agent.path.as_posix()}",
        "# This file is safe to regenerate. Edit the canonical source agent instead.",
        "",
    ]
    lines.append(f"name = {toml_quote(agent.name)}")
    lines.append(f"description = {toml_quote(agent.description)}")
    if model_setting is not None:
        if not isinstance(model_setting, dict):
            raise ValueError(
                f"{agent.name}: Codex model setting must be an object with 'model' and optional 'model_provider'"
            )
        for key in ("model", "model_provider"):
            value = model_setting.get(key)
            if value is not None:
                lines.append(f"{key} = {toml_quote(value)}")
    lines.append(f"developer_instructions = {toml_multiline_string(body)}")
    lines.append("")
    return "\n".join(lines)


def build_root_config(
    agents: Sequence[AgentSource],
    *,
    enable_feature: bool,
    job_max_runtime_seconds: Optional[int],
) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        "# Generated Codex multi-agent config from agents/*.md.",
        "# The install scripts merge the managed Codex agent sections into an existing",
        "# config.toml. Direct exporter output remains a complete generated config.",
        "",
    ]

    if enable_feature:
        lines.extend(
            [
                "[features]",
                "multi_agent = true",
                "multi_agent_v2 = true",
                "",
            ]
        )

    if job_max_runtime_seconds is not None:
        lines.extend(
            [
                "[agents]",
                f"job_max_runtime_seconds = {job_max_runtime_seconds}",
                "",
            ]
        )

    for agent in agents:
        lines.extend(
            [
                f"[agents.{agent.name}]",
                f"description = {toml_quote(agent.description)}",
                f"config_file = {toml_quote(f'agents/{agent.file_stem}.toml')}",
                "",
            ]
        )

    return "\n".join(lines)


def validate_managed_output_leaf(path: Path) -> None:
    if is_linklike(path):
        raise ValueError(f"Managed output must not be a symbolic link: {path}")
    if path.exists() and not path.is_file():
        raise ValueError(f"Managed output must be a regular file: {path}")


def write_text(path: Path, content: str) -> None:
    validate_managed_output_leaf(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    temp_path: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_path = Path(handle.name)
            handle.write(content)
        os.chmod(temp_path, mode)
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def collect_generated(
    generated: List[Tuple[Path, str]],
    generated_names: Set[str],
    path: Path,
    content: str,
    errors: List[str],
) -> None:
    key = path.as_posix().lower()
    if key in generated_names:
        errors.append(f"Duplicate generated output filename: {path.as_posix()}")
        return
    generated_names.add(key)
    generated.append((path, content))


def validate_overwrite_policy(
    generated: Sequence[Tuple[Path, str]], force: bool, errors: List[str]
) -> None:
    if force:
        return
    for out_path, _ in generated:
        if is_linklike(out_path):
            continue
        if not out_path.exists():
            continue
        existing = read_text(out_path)
        if GENERATED_MARKER not in existing.splitlines()[:3]:
            errors.append(
                f"{out_path.as_posix()}: existing file was not generated by this script; rerun with --force to overwrite"
            )


def is_generated_file(path: Path) -> bool:
    if is_linklike(path) or not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in read_text(path).splitlines()[:3]
    except OSError:
        return False


def find_stale_generated_outputs(
    target_dir: Path, generated: Sequence[Tuple[Path, str]]
) -> List[Path]:
    expected = {path.as_posix().lower() for path, _ in generated}
    stale: List[Path] = []

    config_path = target_dir / "config.toml"
    if config_path.as_posix().lower() not in expected and is_generated_file(
        config_path
    ):
        stale.append(config_path)

    agents_dir = target_dir / "agents"
    if agents_dir.exists():
        for existing in sorted(agents_dir.glob("*.toml")):
            if existing.as_posix().lower() in expected:
                continue
            if is_generated_file(existing):
                stale.append(existing)

    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export neutral source agents into Codex multi-agent role config files."
    )
    parser.add_argument(
        "--source-agents",
        default="agents",
        help="Directory containing canonical source agent markdown files.",
    )
    parser.add_argument(
        "--modes-file",
        default=None,
        help=(
            "Neutral mode manifest. Defaults to modes.json beside the source agents directory."
        ),
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Target `.codex`-style directory where `config.toml` and `agents/*.toml` will be generated.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting non-generated existing files.",
    )
    parser.add_argument(
        "--job-max-runtime-seconds",
        type=int,
        default=None,
        help="Optional value written to `agents.job_max_runtime_seconds`.",
    )
    parser.add_argument(
        "--enable-feature-flag",
        dest="enable_feature_flag",
        action="store_true",
        default=True,
        help=(
            "Emit `[features] multi_agent = true` and `multi_agent_v2 = true` "
            "in generated config.toml (default: enabled)."
        ),
    )
    parser.add_argument(
        "--no-enable-feature-flag",
        dest="enable_feature_flag",
        action="store_false",
        help="Do not emit the `[features]` block.",
    )
    parser.add_argument(
        "--resolve-support-refs-to",
        default=None,
        help=(
            "Optional installed support root used to rewrite repo-managed `agents/...`, "
            "`protocols/...`, `skills/...`, and `tools/...` references inside generated "
            "developer instructions."
        ),
    )
    parser.add_argument(
        "--agent-profile",
        default=None,
        help="Opt-in agent model profile name or JSON path.",
    )
    parser.add_argument(
        "--model-set",
        default=None,
        help="Runtime model-set name or JSON path used with --agent-profile.",
    )
    parser.add_argument(
        "--profile-dir",
        default=DEFAULT_PROFILE_DIR,
        help=f"Directory containing agent model profiles (default: {DEFAULT_PROFILE_DIR}).",
    )
    parser.add_argument(
        "--model-set-dir",
        default=DEFAULT_MODEL_SET_DIR,
        help=f"Directory containing Codex model sets (default: {DEFAULT_MODEL_SET_DIR}).",
    )
    parser.add_argument(
        "--uniform-model",
        default=None,
        help="Opt-in runtime model to apply uniformly to all generated Codex agents.",
    )
    args = parser.parse_args()

    if args.job_max_runtime_seconds is not None and args.job_max_runtime_seconds < 1:
        print("--job-max-runtime-seconds must be >= 1 when provided", file=sys.stderr)
        return 2

    source_agents_dir = (
        SCRIPT_DIR.parent / "agents"
        if args.source_agents == "agents"
        else Path(args.source_agents).expanduser()
    )
    source_root = source_agents_dir.parent
    if args.profile_dir == DEFAULT_PROFILE_DIR:
        args.profile_dir = (source_root / DEFAULT_PROFILE_DIR).as_posix()
    if args.model_set_dir == DEFAULT_MODEL_SET_DIR:
        args.model_set_dir = (source_root / DEFAULT_MODEL_SET_DIR).as_posix()
    modes_path = (
        Path(args.modes_file).expanduser()
        if args.modes_file
        else source_agents_dir.parent / "modes.json"
    )
    if not args.target_dir.strip():
        print("--target-dir must not be empty", file=sys.stderr)
        return 2
    if args.target_dir.startswith("-"):
        print("--target-dir must be a filesystem path, not a switch", file=sys.stderr)
        return 2
    try:
        target_dir = Path(
            validate_generated_shell_path(args.target_dir, "Target path")
        )
        support_root_ref = (
            validate_generated_shell_path(
                args.resolve_support_refs_to, "Support root"
            )
            if args.resolve_support_refs_to
            else None
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    catalog_path = Path(args.catalog).expanduser()
    if is_linklike(target_dir):
        print(
            f"Target path must not be a symbolic link or junction: {target_dir}",
            file=sys.stderr,
        )
        return 2
    if target_dir.exists() and not target_dir.is_dir():
        print(f"Target path is not a directory: {target_dir}", file=sys.stderr)
        return 2
    source_support_root_ref = detect_installed_support_root(source_agents_dir)

    if not source_agents_dir.exists():
        print(f"Source directory not found: {source_agents_dir}", file=sys.stderr)
        return 2

    try:
        source_agents = parse_source_agents(source_agents_dir)
        mode_agents = load_mode_agents(modes_path)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    available_agent_names = {agent.name for agent in source_agents}
    unknown_mode_agents = sorted(set(mode_agents.values()) - available_agent_names)
    if unknown_mode_agents:
        print(
            f"{modes_path.as_posix()}: mode manifest references unknown agent(s): "
            + ", ".join(unknown_mode_agents),
            file=sys.stderr,
        )
        return 2
    catalog_agents = parse_catalog_agents(catalog_path)
    agent_mode_aliases = build_agent_mode_aliases(mode_agents)
    try:
        model_settings = resolve_runtime_model_settings(
            [agent.name for agent in source_agents], args, runtime="codex"
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    errors: List[str] = []
    generated: List[Tuple[Path, str]] = []
    generated_names: Set[str] = set()

    if args.strict and catalog_agents:
        if catalog_agents != available_agent_names:
            missing_in_source = sorted(catalog_agents - available_agent_names)
            missing_in_catalog = sorted(available_agent_names - catalog_agents)
            if missing_in_source:
                errors.append(
                    "Agents listed in AGENTS.md but missing in source: "
                    + ", ".join(missing_in_source)
                )
            if missing_in_catalog:
                errors.append(
                    "Agents present in source but missing in AGENTS.md: "
                    + ", ".join(missing_in_catalog)
                )

    for agent in source_agents:
        if args.strict:
            unknown_keys = sorted(agent.fm_keys - KNOWN_SOURCE_FRONTMATTER_KEYS)
            if unknown_keys:
                errors.append(
                    f"{agent.path.as_posix()}: unknown frontmatter key(s): {', '.join(unknown_keys)}"
                )
            if agent.name != agent.file_stem:
                errors.append(
                    f"{agent.path.as_posix()}: frontmatter name '{agent.name}' must match source filename stem "
                    f"'{agent.file_stem}' for Codex role naming consistency"
                )
            if not ROLE_NAME_RE.match(agent.name):
                errors.append(
                    f"{agent.path.as_posix()}: agent name '{agent.name}' is not a valid Codex role key"
                )

        subagents, unresolved = extract_subagents(agent.body, available_agent_names)
        if args.strict and unresolved:
            errors.append(
                f"{agent.path.as_posix()}: unresolved @agent reference(s): {', '.join(unresolved)}"
            )

        body = adapt_body(
            agent.name,
            agent.body,
            has_subagents=bool(subagents),
            agent_kind=agent.kind,
            mode_aliases=agent_mode_aliases.get(agent.name),
            support_root_ref=support_root_ref,
            source_support_root_ref=source_support_root_ref,
        )
        content = build_role_config(agent, body, model_settings.get(agent.name))
        out_path = target_dir / "agents" / f"{agent.file_stem}.toml"
        collect_generated(generated, generated_names, out_path, content, errors)

    root_config = build_root_config(
        source_agents,
        enable_feature=args.enable_feature_flag,
        job_max_runtime_seconds=args.job_max_runtime_seconds,
    )
    collect_generated(
        generated, generated_names, target_dir / "config.toml", root_config, errors
    )

    for out_path, _ in generated:
        try:
            validate_managed_output_leaf(out_path)
        except ValueError as exc:
            errors.append(str(exc))

    if not args.dry_run:
        validate_overwrite_policy(generated, force=args.force, errors=errors)

    if errors:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"- {err}", file=sys.stderr)
        return 2

    if args.dry_run:
        print(
            f"Dry run: would generate {len(generated)} files into {target_dir.as_posix()}"
        )
        for out_path, _ in generated:
            print(f"- {out_path.as_posix()}")
        for stale_path in find_stale_generated_outputs(target_dir, generated):
            print(f"- remove stale generated file: {stale_path.as_posix()}")
        return 0

    (target_dir / "agents").mkdir(parents=True, exist_ok=True)
    for stale_path in find_stale_generated_outputs(target_dir, generated):
        stale_path.unlink()
        print(f"Removed stale generated file: {stale_path.as_posix()}")
    for out_path, out_content in generated:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        write_text(out_path, out_content)

    print(f"Generated {len(generated)} files into {target_dir.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
