#!/usr/bin/env python3
import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


FRONTMATTER_BOUNDARY = re.compile(r"^\s*---\s*$")
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$")
TOOL_ENTRY_RE = re.compile(r"^  ([A-Za-z0-9_-]+)\s*:\s*(true|false)\s*$")
AGENT_REF_RE = re.compile(r"@([a-z0-9][a-z0-9-]*(?:\*)?)")
ROLE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
REPO_MANAGED_REF_RE = re.compile(r"(?<![A-Za-z0-9_./:-])(opencode/[A-Za-z0-9_./-]+)")
FENCE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(.*)$")

KNOWN_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "tools",
    "agent",
}

SCALAR_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "agent",
}

UNSUPPORTED_VALUE_PREFIXES = ("[", "{", "|", ">")

ORCHESTRATOR_PREFIX = "orchestrator-"
GENERATED_MARKER = "# Generated by scripts/export-codex-agents.py"
DEFAULT_MAX_THREADS = 6
DEFAULT_MAX_DEPTH = 2


@dataclass
class AgentSource:
    path: Path
    file_stem: str
    name: str
    description: str
    body: str
    fm_keys: Set[str]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_quotes(value: str) -> str:
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        return value[1:-1]
    return value


def parse_scalar_frontmatter_value(path: Path, key: str, raw_value: str) -> str:
    value = raw_value.strip()
    if not value:
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' must use a single-line scalar value"
        )
    if value.startswith(UNSUPPORTED_VALUE_PREFIXES):
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' uses unsupported structured value '{value}'"
        )
    return strip_quotes(value)


def parse_frontmatter(
    content: str, path: Path
) -> Tuple[Dict[str, str], Dict[str, bool], str]:
    lines = content.splitlines()
    if not lines or not FRONTMATTER_BOUNDARY.match(lines[0]):
        raise ValueError(f"{path.as_posix()}: missing frontmatter block")

    end_idx: Optional[int] = None
    for idx in range(1, len(lines)):
        if FRONTMATTER_BOUNDARY.match(lines[idx]):
            end_idx = idx
            break
    if end_idx is None:
        raise ValueError(f"{path.as_posix()}: unterminated frontmatter block")

    fm: Dict[str, str] = {}
    tools: Dict[str, bool] = {}
    saw_tools = False
    frontmatter_lines = lines[1:end_idx]
    idx = 0
    while idx < len(frontmatter_lines):
        line = frontmatter_lines[idx]
        if not line.strip():
            raise ValueError(
                f"{path.as_posix()}: blank lines are not allowed inside frontmatter"
            )
        if line[:1].isspace():
            raise ValueError(
                f"{path.as_posix()}: unexpected indented frontmatter line '{line}'"
            )

        match = TOP_LEVEL_KEY_RE.match(line)
        if match is None:
            raise ValueError(f"{path.as_posix()}: malformed frontmatter line '{line}'")

        key = match.group(1).strip()
        raw_value = match.group(2).strip()
        if key in {"model", "provider"}:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported; configure model/provider in runtime config instead"
            )
        if key not in KNOWN_SOURCE_FRONTMATTER_KEYS:
            raise ValueError(f"{path.as_posix()}: unsupported frontmatter key '{key}'")
        if key in fm or (key == "tools" and saw_tools):
            raise ValueError(f"{path.as_posix()}: duplicate frontmatter key '{key}'")

        if key == "tools":
            saw_tools = True
            if raw_value:
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must not have an inline value"
                )
            idx += 1
            if idx >= len(frontmatter_lines) or not frontmatter_lines[idx].startswith(
                "  "
            ):
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must contain indented boolean entries"
                )
            while idx < len(frontmatter_lines) and frontmatter_lines[idx].startswith(
                "  "
            ):
                tool_line = frontmatter_lines[idx]
                tool_match = TOOL_ENTRY_RE.match(tool_line)
                if tool_match is None:
                    raise ValueError(
                        f"{path.as_posix()}: malformed tools entry '{tool_line}'"
                    )
                tool_name = tool_match.group(1)
                if tool_name in tools:
                    raise ValueError(
                        f"{path.as_posix()}: duplicate tools entry '{tool_name}'"
                    )
                tools[tool_name] = tool_match.group(2) == "true"
                idx += 1
            continue

        if key not in SCALAR_FRONTMATTER_KEYS:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported in this exporter"
            )
        fm[key] = parse_scalar_frontmatter_value(path, key, raw_value)
        idx += 1

    body = "\n".join(lines[end_idx + 1 :])
    if content.endswith("\n"):
        body += "\n"
    return fm, tools, body


def parse_source_agents(source_agents_dir: Path) -> List[AgentSource]:
    agents: List[AgentSource] = []
    for path in sorted(source_agents_dir.glob("*.md")):
        source = read_text(path)
        fm, tools, body = parse_frontmatter(source, path)
        name = fm.get("name", "").strip()
        description = fm.get("description", "").strip()
        if not name:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'name'"
            )
        if not description:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'description'"
            )
        agents.append(
            AgentSource(
                path=path,
                file_stem=path.stem,
                name=name,
                description=description,
                body=body,
                fm_keys=set(fm.keys()) | ({"tools"} if tools else set()),
            )
        )
    return agents


def parse_catalog_agents(catalog_path: Path) -> Set[str]:
    if not catalog_path.exists():
        return set()
    rows = read_text(catalog_path).splitlines()
    agents: Set[str] = set()
    for line in rows:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [part.strip() for part in stripped.split("|")]
        if len(parts) < 3:
            continue
        agent = parts[1]
        if agent in {"", "Agent"}:
            continue
        if set(agent) <= {"-"}:
            continue
        agents.add(agent)
    return agents


def ordered_unique(values: Sequence[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def compact_markdown(text: str) -> str:
    lines = text.splitlines()
    compacted: List[str] = []
    pending_blank = False
    in_fence = False
    fence_token = ""

    for line in lines:
        fence_match = FENCE_RE.match(line)
        if in_fence:
            compacted.append(line)
            if fence_match and line.strip() == fence_token:
                in_fence = False
                fence_token = ""
            continue

        if fence_match:
            if pending_blank and compacted:
                compacted.append("")
                pending_blank = False
            compacted.append(line)
            in_fence = True
            fence_token = fence_match.group(1)
            continue

        stripped = line.rstrip()
        if not stripped:
            pending_blank = True
            continue

        if pending_blank and compacted:
            compacted.append("")
            pending_blank = False
        compacted.append(stripped)

    out = "\n".join(compacted)
    if text.endswith("\n"):
        out += "\n"
    return out


def expand_ref_token(
    token: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    if token == "executor-*":
        return ["executor"], []
    if token.endswith("*"):
        return [], [token]
    if token in available_agents:
        return [token], []
    return [], [token]


def extract_subagents(
    body: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    resolved: List[str] = []
    unresolved: List[str] = []
    for match in AGENT_REF_RE.finditer(body):
        token = match.group(1)
        expanded, unknown = expand_ref_token(token, available_agents)
        resolved.extend(expanded)
        unresolved.extend(unknown)
    return ordered_unique(resolved), ordered_unique(unresolved)


def make_input_adapter(agent_name: str) -> str:
    suffix = agent_name[len(ORCHESTRATOR_PREFIX) :]
    command_token = f"/run-{suffix}"
    helper_token = f"/{suffix}"
    return (
        "## Codex Input Adapter\n\n"
        "Use the user's latest message as `raw_input`.\n"
        f"If it starts with `{command_token}` or `{helper_token}`, strip that first token, then apply the existing flag parsing unchanged.\n"
    )


def make_role_reference_adapter() -> str:
    return (
        "## Codex Agent Role Adapter\n\n"
        "Interpret source `@agent-name` references as generated role names from `.codex/config.toml`.\n"
        "When routing work, use those role names directly.\n"
    )


def rewrite_opencode_refs(text: str, opencode_root_ref: Optional[str]) -> str:
    if not opencode_root_ref:
        return text

    normalized_root = opencode_root_ref.rstrip("/\\")

    def repl(match: re.Match[str]) -> str:
        repo_relative = match.group(1)
        suffix = repo_relative[len("opencode/") :]
        return f"{normalized_root}/{suffix}"

    return REPO_MANAGED_REF_RE.sub(repl, text)


def adapt_body(
    agent_name: str,
    original_body: str,
    has_subagents: bool,
    *,
    opencode_root_ref: Optional[str] = None,
) -> str:
    body = original_body.replace("$ARGUMENTS", "raw_input")
    blocks: List[str] = []
    if agent_name.startswith(ORCHESTRATOR_PREFIX):
        blocks.append(make_input_adapter(agent_name))
    if has_subagents:
        blocks.append(make_role_reference_adapter())
    blocks.append(body.lstrip("\n"))
    adapted = compact_markdown("\n\n".join(blocks).rstrip() + "\n")
    return rewrite_opencode_refs(adapted, opencode_root_ref)


def toml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_multiline_string(value: str) -> str:
    normalized = value.rstrip("\n")
    lines = normalized.split("\n") if normalized else [""]
    escaped = [json.dumps(line, ensure_ascii=False)[1:-1] for line in lines]
    return '"""\n' + "\n".join(escaped) + '\n"""'


def build_role_config(agent: AgentSource, body: str) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        f"# Source: {agent.path.as_posix()}",
        "# This file is safe to regenerate. Edit the source OpenCode agent instead.",
        "",
    ]
    lines.append(f"name = {toml_quote(agent.name)}")
    lines.append(f"description = {toml_quote(agent.description)}")
    lines.append(f"developer_instructions = {toml_multiline_string(body)}")
    lines.append("")
    return "\n".join(lines)


def build_root_config(
    agents: Sequence[AgentSource],
    *,
    enable_feature: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        "# Generated Codex multi-agent config from opencode/agents/*.md.",
        "# The install scripts merge the managed Codex agent sections into an existing",
        "# config.toml. Direct exporter output remains a complete generated config.",
        "",
    ]

    if enable_feature:
        lines.extend(
            [
                "[features]",
                "multi_agent = true",
                "",
            ]
        )

    lines.extend(
        [
            "[agents]",
            f"max_threads = {max_threads}",
            f"max_depth = {max_depth}",
        ]
    )
    if job_max_runtime_seconds is not None:
        lines.append(f"job_max_runtime_seconds = {job_max_runtime_seconds}")
    lines.append("")

    for agent in agents:
        lines.extend(
            [
                f"[agents.{agent.name}]",
                f"description = {toml_quote(agent.description)}",
                f"config_file = {toml_quote(f'agents/{agent.file_stem}.toml')}",
                "",
            ]
        )

    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def collect_generated(
    generated: List[Tuple[Path, str]],
    generated_names: Set[str],
    path: Path,
    content: str,
    errors: List[str],
) -> None:
    key = path.as_posix().lower()
    if key in generated_names:
        errors.append(f"Duplicate generated output filename: {path.as_posix()}")
        return
    generated_names.add(key)
    generated.append((path, content))


def validate_overwrite_policy(
    generated: Sequence[Tuple[Path, str]], force: bool, errors: List[str]
) -> None:
    if force:
        return
    for out_path, _ in generated:
        if not out_path.exists():
            continue
        existing = read_text(out_path)
        if GENERATED_MARKER not in existing.splitlines()[:3]:
            errors.append(
                f"{out_path.as_posix()}: existing file was not generated by this script; rerun with --force to overwrite"
            )


def is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in read_text(path).splitlines()[:3]
    except OSError:
        return False


def find_stale_generated_outputs(
    target_dir: Path, generated: Sequence[Tuple[Path, str]]
) -> List[Path]:
    expected = {path.as_posix().lower() for path, _ in generated}
    stale: List[Path] = []

    config_path = target_dir / "config.toml"
    if config_path.as_posix().lower() not in expected and is_generated_file(
        config_path
    ):
        stale.append(config_path)

    agents_dir = target_dir / "agents"
    if agents_dir.exists():
        for existing in sorted(agents_dir.glob("*.toml")):
            if existing.as_posix().lower() in expected:
                continue
            if is_generated_file(existing):
                stale.append(existing)

    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export OpenCode agents into Codex multi-agent role config files."
    )
    parser.add_argument(
        "--source-agents",
        default="opencode/agents",
        help="Directory containing source OpenCode agent markdown files.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Target `.codex`-style directory where `config.toml` and `agents/*.toml` will be generated.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting non-generated existing files.",
    )
    parser.add_argument(
        "--max-threads",
        type=int,
        default=DEFAULT_MAX_THREADS,
        help="Value written to `agents.max_threads` in generated config.toml (default: 6).",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=DEFAULT_MAX_DEPTH,
        help="Value written to `agents.max_depth` in generated config.toml (default: 2).",
    )
    parser.add_argument(
        "--job-max-runtime-seconds",
        type=int,
        default=None,
        help="Optional value written to `agents.job_max_runtime_seconds`.",
    )
    parser.add_argument(
        "--enable-feature-flag",
        dest="enable_feature_flag",
        action="store_true",
        default=True,
        help="Emit `[features] multi_agent = true` in generated config.toml (default: enabled).",
    )
    parser.add_argument(
        "--no-enable-feature-flag",
        dest="enable_feature_flag",
        action="store_false",
        help="Do not emit the `[features]` block.",
    )
    parser.add_argument(
        "--resolve-opencode-refs-to",
        default=None,
        help=(
            "Optional install root used to rewrite repo-managed `opencode/...` references "
            "inside generated developer instructions."
        ),
    )
    args = parser.parse_args()

    if args.max_threads < 1:
        print("--max-threads must be >= 1", file=sys.stderr)
        return 2
    if args.max_depth < 0:
        print("--max-depth must be >= 0", file=sys.stderr)
        return 2
    if args.job_max_runtime_seconds is not None and args.job_max_runtime_seconds < 1:
        print("--job-max-runtime-seconds must be >= 1 when provided", file=sys.stderr)
        return 2

    source_agents_dir = Path(args.source_agents).expanduser()
    target_dir = Path(args.target_dir).expanduser()
    catalog_path = Path(args.catalog).expanduser()
    opencode_root_ref = None
    if args.resolve_opencode_refs_to:
        opencode_root_ref = Path(args.resolve_opencode_refs_to).expanduser().as_posix()

    if not source_agents_dir.exists():
        print(f"Source directory not found: {source_agents_dir}", file=sys.stderr)
        return 2

    try:
        source_agents = parse_source_agents(source_agents_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    available_agent_names = {agent.name for agent in source_agents}
    catalog_agents = parse_catalog_agents(catalog_path)

    errors: List[str] = []
    generated: List[Tuple[Path, str]] = []
    generated_names: Set[str] = set()

    if args.strict and catalog_agents:
        if catalog_agents != available_agent_names:
            missing_in_source = sorted(catalog_agents - available_agent_names)
            missing_in_catalog = sorted(available_agent_names - catalog_agents)
            if missing_in_source:
                errors.append(
                    "Agents listed in AGENTS.md but missing in source: "
                    + ", ".join(missing_in_source)
                )
            if missing_in_catalog:
                errors.append(
                    "Agents present in source but missing in AGENTS.md: "
                    + ", ".join(missing_in_catalog)
                )

    for agent in source_agents:
        if args.strict:
            unknown_keys = sorted(agent.fm_keys - KNOWN_SOURCE_FRONTMATTER_KEYS)
            if unknown_keys:
                errors.append(
                    f"{agent.path.as_posix()}: unknown frontmatter key(s): {', '.join(unknown_keys)}"
                )
            if agent.name != agent.file_stem:
                errors.append(
                    f"{agent.path.as_posix()}: frontmatter name '{agent.name}' must match source filename stem "
                    f"'{agent.file_stem}' for Codex role naming consistency"
                )
            if not ROLE_NAME_RE.match(agent.name):
                errors.append(
                    f"{agent.path.as_posix()}: agent name '{agent.name}' is not a valid Codex role key"
                )

        subagents, unresolved = extract_subagents(agent.body, available_agent_names)
        if args.strict and unresolved:
            errors.append(
                f"{agent.path.as_posix()}: unresolved @agent reference(s): {', '.join(unresolved)}"
            )

        body = adapt_body(
            agent.name,
            agent.body,
            has_subagents=bool(subagents),
            opencode_root_ref=opencode_root_ref,
        )
        content = build_role_config(agent, body)
        out_path = target_dir / "agents" / f"{agent.file_stem}.toml"
        collect_generated(generated, generated_names, out_path, content, errors)

    root_config = build_root_config(
        source_agents,
        enable_feature=args.enable_feature_flag,
        max_threads=args.max_threads,
        max_depth=args.max_depth,
        job_max_runtime_seconds=args.job_max_runtime_seconds,
    )
    collect_generated(
        generated, generated_names, target_dir / "config.toml", root_config, errors
    )

    if not args.dry_run:
        validate_overwrite_policy(generated, force=args.force, errors=errors)

    if errors:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"- {err}", file=sys.stderr)
        return 2

    if args.dry_run:
        print(
            f"Dry run: would generate {len(generated)} files into {target_dir.as_posix()}"
        )
        for out_path, _ in generated:
            print(f"- {out_path.as_posix()}")
        for stale_path in find_stale_generated_outputs(target_dir, generated):
            print(f"- remove stale generated file: {stale_path.as_posix()}")
        return 0

    (target_dir / "agents").mkdir(parents=True, exist_ok=True)
    for stale_path in find_stale_generated_outputs(target_dir, generated):
        stale_path.unlink()
        print(f"Removed stale generated file: {stale_path.as_posix()}")
    for out_path, out_content in generated:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        write_text(out_path, out_content)

    print(f"Generated {len(generated)} files into {target_dir.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
