#!/usr/bin/env python3
import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


SCRIPT_DIR = Path(__file__).resolve().parent
if SCRIPT_DIR.as_posix() not in sys.path:
    sys.path.insert(0, SCRIPT_DIR.as_posix())

from agent_model_profiles import (  # noqa: E402
    RuntimeModelSetting,
    load_model_set,
    load_profile,
    resolve_agent_model_settings,
)


FRONTMATTER_BOUNDARY = re.compile(r"^\s*---\s*$")
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$")
TOOL_ENTRY_RE = re.compile(r"^  ([A-Za-z0-9_-]+)\s*:\s*(true|false)\s*$")
AGENT_REF_RE = re.compile(r"@([a-z0-9][a-z0-9-]*(?:\*)?)")
FENCE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(.*)$")
HANDOFF_PROTOCOL_RE = re.compile(
    r"(?ms)^# HANDOFF PROTOCOL \(GLOBAL\)\n.*?(?=^## AGENT RESPONSIBILITY MATRIX|^# )"
)
RESPONSIBILITY_MATRIX_RE = re.compile(
    r"(?ms)^## AGENT RESPONSIBILITY MATRIX\n\n"
    r"\| Agent \| Primary Responsibility \| Forbidden Actions \|\n"
    r"\|[-| ]+\|\n"
    r"(?P<rows>(?:\|.*\|\n)+)"
)
FLAG_PARSING_INTRO_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} FLAG PARSING PROTOCOL(?: \([^)]+\))?)\n\n"
    r"You are given positional parameters via the slash command\.\n\n"
    r"Parse `raw_input`: tokens before the first `--\*` flag form `main_task_prompt`; `--\*` tokens are flags\.(?P<resume> If `main_task_prompt` is empty and `resume_mode = true`, treat as resume-only invocation\.)?\n"
)
RESPONSE_MODE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} RESPONSE MODE \(DEFAULT\))\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)
CONFIRM_VERBOSE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} CONFIRM / VERBOSE PROTOCOL)\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)
CHECKPOINT_PROTOCOL_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} CHECKPOINT PROTOCOL)\n\n(?P<body>.*?)(?=^#{1,2} |\Z)"
)
RUN_STATUS_PROTOCOL_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} (?:RUN STATUS PROTOCOL|STATUS ARTIFACT PROTOCOL))\n\n(?P<body>.*?)(?=^#{1,2} |\Z)"
)

KNOWN_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "tools",
    "agent",
}

SCALAR_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "agent",
}

REQUIRED_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "temperature",
}

UNSUPPORTED_VALUE_PREFIXES = ("[", "{", "|", ">")

ORCHESTRATOR_PREFIX = "orchestrator-"
GENERATED_MARKER = "<!-- Generated by scripts/export-copilot-agents.py"
DEFAULT_PROFILE_DIR = "opencode/tools/agent-profiles"
DEFAULT_MODEL_SET_DIR = "copilot/tools/model-sets"


@dataclass
class AgentSource:
    path: Path
    file_stem: str
    name: str
    description: str
    body: str
    fm_keys: Set[str]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_quotes(value: str) -> str:
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        return value[1:-1]
    return value


def parse_scalar_frontmatter_value(path: Path, key: str, raw_value: str) -> str:
    value = raw_value.strip()
    if not value:
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' must use a single-line scalar value"
        )
    if value.startswith(UNSUPPORTED_VALUE_PREFIXES):
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' uses unsupported structured value '{value}'"
        )
    return strip_quotes(value)


def parse_frontmatter(content: str, path: Path) -> Tuple[Dict[str, str], str]:
    lines = content.splitlines()
    if not lines or not FRONTMATTER_BOUNDARY.match(lines[0]):
        raise ValueError(f"{path.as_posix()}: missing frontmatter block")

    end_idx: Optional[int] = None
    for idx in range(1, len(lines)):
        if FRONTMATTER_BOUNDARY.match(lines[idx]):
            end_idx = idx
            break
    if end_idx is None:
        raise ValueError(f"{path.as_posix()}: unterminated frontmatter block")

    fm: Dict[str, str] = {}
    saw_tools = False
    frontmatter_lines = lines[1:end_idx]
    idx = 0
    while idx < len(frontmatter_lines):
        line = frontmatter_lines[idx]
        if not line.strip():
            raise ValueError(
                f"{path.as_posix()}: blank lines are not allowed inside frontmatter"
            )
        if line[:1].isspace():
            raise ValueError(
                f"{path.as_posix()}: unexpected indented frontmatter line '{line}'"
            )

        match = TOP_LEVEL_KEY_RE.match(line)
        if match is None:
            raise ValueError(f"{path.as_posix()}: malformed frontmatter line '{line}'")

        key = match.group(1).strip()
        raw_value = match.group(2).strip()
        if key in {"model", "provider"}:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported; configure model/provider in runtime config instead"
            )
        if key not in KNOWN_SOURCE_FRONTMATTER_KEYS:
            raise ValueError(f"{path.as_posix()}: unsupported frontmatter key '{key}'")
        if key in fm or (key == "tools" and saw_tools):
            raise ValueError(f"{path.as_posix()}: duplicate frontmatter key '{key}'")

        if key == "tools":
            saw_tools = True
            if raw_value:
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must not have an inline value"
                )
            idx += 1
            if idx >= len(frontmatter_lines) or not frontmatter_lines[idx].startswith(
                "  "
            ):
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must contain indented boolean entries"
                )
            while idx < len(frontmatter_lines) and frontmatter_lines[idx].startswith(
                "  "
            ):
                tool_line = frontmatter_lines[idx]
                tool_match = TOOL_ENTRY_RE.match(tool_line)
                if tool_match is None:
                    raise ValueError(
                        f"{path.as_posix()}: malformed tools entry '{tool_line}'"
                    )
                idx += 1
            continue

        if key not in SCALAR_FRONTMATTER_KEYS:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported in this exporter"
            )
        fm[key] = parse_scalar_frontmatter_value(path, key, raw_value)
        idx += 1

    missing_required = sorted(REQUIRED_SOURCE_FRONTMATTER_KEYS - set(fm.keys()))
    if missing_required:
        raise ValueError(
            f"{path.as_posix()}: missing required frontmatter key(s): {', '.join(missing_required)}"
        )

    body = "\n".join(lines[end_idx + 1 :])
    if content.endswith("\n"):
        body += "\n"
    return fm, body


def parse_source_agents(source_agents_dir: Path) -> List[AgentSource]:
    agents: List[AgentSource] = []
    for path in sorted(source_agents_dir.glob("*.md")):
        source = read_text(path)
        fm, body = parse_frontmatter(source, path)
        name = fm.get("name", "").strip()
        description = fm.get("description", "").strip()
        if not name:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'name'"
            )
        if not description:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'description'"
            )
        agents.append(
            AgentSource(
                path=path,
                file_stem=path.stem,
                name=name,
                description=description,
                body=body,
                fm_keys=set(fm.keys()),
            )
        )
    return agents


def parse_catalog_agents(catalog_path: Path) -> Set[str]:
    if not catalog_path.exists():
        return set()
    rows = read_text(catalog_path).splitlines()
    agents: Set[str] = set()
    for line in rows:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [part.strip() for part in stripped.split("|")]
        if len(parts) < 3:
            continue
        agent = parts[1]
        if agent in {"", "Agent"}:
            continue
        if set(agent) <= {"-"}:
            continue
        agents.add(agent)
    return agents


def ordered_unique(values: Sequence[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def compact_markdown(text: str) -> str:
    lines = text.splitlines()
    compacted: List[str] = []
    pending_blank = False
    in_fence = False
    fence_token = ""

    for line in lines:
        fence_match = FENCE_RE.match(line)
        if in_fence:
            compacted.append(line)
            if fence_match and line.strip() == fence_token:
                in_fence = False
                fence_token = ""
            continue

        if fence_match:
            if pending_blank and compacted:
                compacted.append("")
                pending_blank = False
            compacted.append(line)
            in_fence = True
            fence_token = fence_match.group(1)
            continue

        stripped = line.rstrip()
        if not stripped:
            pending_blank = True
            continue

        if pending_blank and compacted:
            compacted.append("")
            pending_blank = False
        compacted.append(stripped)

    out = "\n".join(compacted)
    if text.endswith("\n"):
        out += "\n"
    return out


def ensure_sentence(text: str) -> str:
    return text if text.endswith((".", "!", "?")) else f"{text}."


def minify_handoff_protocol(text: str) -> str:
    match = HANDOFF_PROTOCOL_RE.search(text)
    if not match:
        return text

    section = match.group(0)
    general_match = re.search(
        r"(?m)^## General Handoff Rules\n\n(?P<bullets>(?:- [^\n]+\n)+)",
        section,
    )
    if not general_match:
        return text

    lines = ["# HANDOFF PROTOCOL (GLOBAL)", ""]
    lines.extend(line.rstrip() for line in general_match.group("bullets").strip().splitlines())
    lines.append(
        "- Orchestrator -> subagent: selected for specialization; stay within scope; satisfy the provided Definition of Done exactly."
    )

    if "## EXECUTOR -> REVIEWER HANDOFF" in section:
        lines.append(
            "- Executor -> reviewer: only evidence and DoD satisfaction count; missing or weak evidence means incomplete."
        )
    if "## REVIEWER -> ORCHESTRATOR HANDOFF" in section:
        lines.append(
            "- Reviewer -> orchestrator: reviewer decisions are final. If `status = fail` and `test_only = false`, convert `required_followups` into delta tasks, route them, and retry up to `max_retry_rounds`; if `test_only = true`, skip retries; stop and report blockers when failure persists."
        )

    replacement = "\n".join(lines) + "\n\n"
    return text[: match.start()] + replacement + text[match.end() :]


def minify_agent_responsibility_matrix(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets: List[str] = []
        for raw_row in match.group("rows").strip().splitlines():
            cells = [cell.strip() for cell in raw_row.strip().strip("|").split("|")]
            if len(cells) != 3 or not all(cells):
                return match.group(0)
            bullets.append(
                f"- `{cells[0]}`: {ensure_sentence(cells[1])} Forbidden: {ensure_sentence(cells[2])}"
            )
        return "## AGENT RESPONSIBILITY MATRIX\n\n" + "\n".join(bullets) + "\n"

    return RESPONSIBILITY_MATRIX_RE.sub(repl, text, count=1)


def minify_flag_parsing_intro(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        resume = match.group("resume") or ""
        return (
            f"{match.group('heading')}\n\n"
            "Parse `raw_input`: tokens before the first `--*` flag form `main_task_prompt`; `--*` tokens are flags."
            f"{resume}\n"
        )

    return FLAG_PARSING_INTRO_RE.sub(repl, text, count=1)


def minify_response_mode(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        section = match.group("bullets")
        autopilot_clause = " and `autopilot_mode = false`" if "autopilot_mode = false" in section else ""
        return (
            f"{match.group('heading')}\n\n"
            "- Default to concise final-only reporting: outcome, key deliverables, blockers/errors. Emit stage-by-stage progress only when `--confirm` or `--verbose` requires it"
            f"{autopilot_clause}.\n"
        )

    return RESPONSE_MODE_RE.sub(repl, text, count=1)


def minify_confirm_verbose_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets = [line.strip()[2:] for line in match.group("bullets").strip().splitlines()]
        if len(bullets) < 2:
            return match.group(0)

        confirm_line = bullets[0]
        verbose_line = bullets[1]
        if "Proceed? [yes / feedback / abort]" not in confirm_line or "On abort: checkpoint and stop." not in confirm_line:
            return match.group(0)

        confirm_label = "`confirm_mode` (when not autopilot)" if "when not autopilot" in confirm_line else "`confirm_mode`"
        waiting_clause = "update status to `waiting_for_user` and " if "waiting_for_user" in confirm_line else ""
        verbose_line = verbose_line.replace("`verbose_mode` (implies confirm): also ", "`verbose_mode` (implies confirm): ")

        return (
            f"{match.group('heading')}\n\n"
            f"- {confirm_label}: after each stage, {waiting_clause}pause with `Proceed? [yes / feedback / abort]`; on abort checkpoint and stop.\n"
            f"- {verbose_line}\n"
        )

    return CONFIRM_VERBOSE_RE.sub(repl, text, count=1)


def minify_checkpoint_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        body = match.group("body")
        if (
            "<run_output_dir>/checkpoint.json" not in body
            or "checkpoint.schema.json" not in body
        ):
            return match.group(0)
        return (
            f"{match.group('heading')}\n\n"
            "After each successful stage, emit the checkpoint event via `status_runtime_event` so runtime/plugin updates `<run_output_dir>/checkpoint.json` (schema: `opencode/protocols/schemas/checkpoint.schema.json`).\n\n"
        )

    return CHECKPOINT_PROTOCOL_RE.sub(repl, text, count=1)


def minify_run_status_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        body = match.group("body")
        heading = match.group("heading")
        if (
            "<run_output_dir>/status/run-status.json" not in body
            or "PIPELINE_PROTOCOL.md" not in body
        ):
            return match.group(0)

        if "Use the expanded status layout (`tasks/<task_id>.json`, `agents/<agent_id>.json`) once task decomposition begins at Stage 3." in body:
            lines = [
                heading,
                "",
                "- Emit `status_runtime_event` updates for `<run_output_dir>/status/run-status.json` per `opencode/protocols/PIPELINE_PROTOCOL.md`; preserve `working_project_dir` unchanged when present.",
                "- Use expanded status files from Stage 3: `tasks/<task_id>.json` and `agents/<agent_id>.json`.",
                "- Required events: `run.started`/`run.resumed`, `stage.completed`, `tasks.registered`, `task.updated`, `agent.started`/`agent.heartbeat`/`agent.finished`, and `run.finished`.",
                '- Prefer `event = "batch"` for related same-run deltas; keep standalone heartbeats coarse and skip redundant ones.',
            ]
            return "\n".join(lines) + "\n\n"

        if "Use the expanded status layout once Stage 2 creates the task list." in body:
            lines = [
                heading,
                "",
                '- Emit `status_runtime_event` updates for `<run_output_dir>/status/run-status.json` per `opencode/protocols/PIPELINE_PROTOCOL.md`; prefer `event = "batch"` for same-run task/agent deltas.',
                "- Preserve `working_project_dir` unchanged when provided; if the runtime cannot honor a required delegated worktree, stop instead of silently using the caller repo.",
                "- Use expanded status files after Stage 2 creates the task list.",
                "- Required events: `run.started`/`run.resumed`, `stage.completed`, `tasks.registered`, `task.updated`, `agent.started`/`agent.heartbeat`/`agent.finished`, and `run.finished`. Keep standalone heartbeats coarse unless an earlier semantic change makes one useful.",
            ]
            return "\n".join(lines) + "\n\n"

        if "target_project_dir" in body and "working_project_dir" in body:
            lines = [
                heading,
                "",
                "- Emit `status_runtime_event` updates for `<run_output_dir>/status/run-status.json` (`layout = run-only`) per `opencode/protocols/PIPELINE_PROTOCOL.md`.",
                "- Keep modernization-planning status/checkpoint writes anchored to the source-project run root; do not pass `target_project_dir` as `working_project_dir` for planning events.",
                "- Delegated `@orchestrator-pipeline` runs must preserve `working_project_dir` so target-local status/checkpoint files land in the target repo.",
            ]
            return "\n".join(lines) + "\n\n"

        if "(`layout = run-only`)" in body:
            return (
                f"{heading}\n\n"
                "Emit `status_runtime_event` updates for `<run_output_dir>/status/run-status.json` (`layout = run-only`) per `opencode/protocols/PIPELINE_PROTOCOL.md`.\n\n"
            )

        return match.group(0)

    return RUN_STATUS_PROTOCOL_RE.sub(repl, text, count=1)


def minify_orchestrator_runtime_body(agent_name: str, text: str) -> str:
    if not agent_name.startswith(ORCHESTRATOR_PREFIX):
        return text

    text = minify_handoff_protocol(text)
    text = minify_agent_responsibility_matrix(text)
    text = minify_flag_parsing_intro(text)
    text = minify_response_mode(text)
    text = minify_checkpoint_protocol(text)
    text = minify_run_status_protocol(text)
    return minify_confirm_verbose_protocol(text)


def expand_ref_token(
    token: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    if token == "executor-*":
        return ["executor"], []
    if token.endswith("*"):
        return [], [token]
    if token in available_agents:
        return [token], []
    return [], [token]


def extract_subagents(
    body: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    resolved: List[str] = []
    unresolved: List[str] = []
    for match in AGENT_REF_RE.finditer(body):
        token = match.group(1)
        expanded, unknown = expand_ref_token(token, available_agents)
        resolved.extend(expanded)
        unresolved.extend(unknown)
    return ordered_unique(resolved), ordered_unique(unresolved)


def make_input_adapter(agent_name: str) -> str:
    suffix = agent_name[len(ORCHESTRATOR_PREFIX) :]
    command_token = f"/run-{suffix}"
    helper_token = f"/{suffix}"
    return (
        "## Copilot Input Adapter\n\n"
        "Use the user's latest message as `raw_input`.\n"
        f"If it starts with `{command_token}` or `{helper_token}`, strip that first token, then apply the existing flag parsing unchanged.\n"
    )


def make_solo_adapter() -> str:
    return (
        "## Copilot Fallback Mode (No Subagents)\n\n"
        "If subagents are unavailable in this environment, execute all stage responsibilities inline.\n"
        "Preserve stage order, output contracts, and quality gates.\n"
        "Do not expand scope; if blocked, report blockers explicitly.\n"
    )


def adapt_body(agent_name: str, original_body: str, solo_mode: bool) -> str:
    body = original_body.replace("$ARGUMENTS", "raw_input")
    body = minify_orchestrator_runtime_body(agent_name, body)
    blocks: List[str] = []
    if agent_name.startswith(ORCHESTRATOR_PREFIX):
        blocks.append(make_input_adapter(agent_name))
    if solo_mode:
        blocks.append(make_solo_adapter())
    blocks.append(body.lstrip("\n"))
    return compact_markdown("\n\n".join(blocks).rstrip() + "\n")


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


YAML_PLAIN_MODEL_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/+:-]*$")


def yaml_model_scalar(value: str) -> str:
    if YAML_PLAIN_MODEL_RE.fullmatch(value):
        return value
    return yaml_quote(value)


def resolve_runtime_model_settings(
    agent_names: Sequence[str], args: argparse.Namespace, *, runtime: str
) -> Dict[str, RuntimeModelSetting]:
    if (
        args.uniform_model is None
        and (args.agent_profile or args.model_set)
        and not (args.agent_profile and args.model_set)
    ):
        raise ValueError(
            "--agent-profile and --model-set must be supplied together unless --uniform-model is used"
        )

    profile = (
        load_profile(args.agent_profile, args.profile_dir, runtime)
        if args.agent_profile
        else None
    )
    model_set = (
        load_model_set(args.model_set, args.model_set_dir, runtime)
        if args.model_set
        else None
    )
    return resolve_agent_model_settings(
        agent_names,
        profile,
        model_set,
        uniform_model=args.uniform_model,
        runtime=runtime,
    )


def build_agent_markdown(
    *,
    name: str,
    description: str,
    body: str,
    subagents: Sequence[str],
    model_setting: Optional[RuntimeModelSetting] = None,
) -> str:
    lines: List[str] = [
        "---",
        f"name: {yaml_quote(name)}",
        f"description: {yaml_quote(description)}",
    ]
    if model_setting is not None:
        if isinstance(model_setting, str):
            lines.append(f"model: {yaml_model_scalar(model_setting)}")
        elif isinstance(model_setting, list):
            lines.append("model:")
            for model_name in model_setting:
                lines.append(f"  - {yaml_model_scalar(model_name)}")
        else:
            raise ValueError(
                f"{name}: Copilot model setting must be a string or list of strings"
            )
    if subagents:
        lines.append("agents:")
        for agent in subagents:
            lines.append(f"  - {agent}")
    lines.append("---")
    lines.append("")
    lines.append(f"{GENERATED_MARKER} -->")
    lines.append("")
    lines.append(body.rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def collect_generated(
    generated: List[Tuple[Path, str]],
    generated_names: Set[str],
    path: Path,
    content: str,
    errors: List[str],
) -> None:
    key = path.name.lower()
    if key in generated_names:
        errors.append(f"Duplicate generated output filename: {path.name}")
        return
    generated_names.add(key)
    generated.append((path, content))


def is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in read_text(path)
    except OSError:
        return False


def find_stale_generated_outputs(
    target_dir: Path, generated: Sequence[Tuple[Path, str]]
) -> List[Path]:
    expected = {path.name.lower() for path, _ in generated}
    stale: List[Path] = []
    for existing in sorted(target_dir.glob("*.agent.md")):
        if existing.name.lower() in expected:
            continue
        if is_generated_file(existing):
            stale.append(existing)
    return stale


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export OpenCode agents into VS Code Copilot .agent.md files."
    )
    parser.add_argument(
        "--source-agents",
        default="opencode/agents",
        help="Directory containing source OpenCode agent markdown files.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Directory where Copilot .agent.md files will be generated.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--emit-fallback",
        dest="emit_fallback",
        action="store_true",
        default=True,
        help="Emit '-solo' fallback files for orchestrator agents (default: enabled).",
    )
    parser.add_argument(
        "--no-emit-fallback",
        dest="emit_fallback",
        action="store_false",
        help="Disable '-solo' fallback file generation.",
    )
    parser.add_argument(
        "--agent-profile",
        default=None,
        help="Opt-in agent model profile name or JSON path.",
    )
    parser.add_argument(
        "--model-set",
        default=None,
        help="Runtime model-set name or JSON path used with --agent-profile.",
    )
    parser.add_argument(
        "--profile-dir",
        default=DEFAULT_PROFILE_DIR,
        help=f"Directory containing agent model profiles (default: {DEFAULT_PROFILE_DIR}).",
    )
    parser.add_argument(
        "--model-set-dir",
        default=DEFAULT_MODEL_SET_DIR,
        help=f"Directory containing Copilot model sets (default: {DEFAULT_MODEL_SET_DIR}).",
    )
    parser.add_argument(
        "--uniform-model",
        default=None,
        help="Opt-in runtime model to apply uniformly to all generated Copilot agents.",
    )
    args = parser.parse_args()

    source_agents_dir = Path(args.source_agents).expanduser()
    target_dir = Path(args.target_dir).expanduser()
    catalog_path = Path(args.catalog).expanduser()

    if not source_agents_dir.exists():
        print(f"Source directory not found: {source_agents_dir}", file=sys.stderr)
        return 2

    try:
        source_agents = parse_source_agents(source_agents_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    available_agent_names = {agent.name for agent in source_agents}
    catalog_agents = parse_catalog_agents(catalog_path)
    try:
        model_settings = resolve_runtime_model_settings(
            [agent.name for agent in source_agents], args, runtime="copilot"
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    errors: List[str] = []
    generated: List[Tuple[Path, str]] = []
    generated_names: Set[str] = set()

    if args.strict and catalog_agents:
        if catalog_agents != available_agent_names:
            missing_in_source = sorted(catalog_agents - available_agent_names)
            missing_in_catalog = sorted(available_agent_names - catalog_agents)
            if missing_in_source:
                errors.append(
                    "Agents listed in AGENTS.md but missing in source: "
                    + ", ".join(missing_in_source)
                )
            if missing_in_catalog:
                errors.append(
                    "Agents present in source but missing in AGENTS.md: "
                    + ", ".join(missing_in_catalog)
                )

    for agent in source_agents:
        if args.strict:
            unknown_keys = sorted(agent.fm_keys - KNOWN_SOURCE_FRONTMATTER_KEYS)
            if unknown_keys:
                errors.append(
                    f"{agent.path.as_posix()}: unknown frontmatter key(s): {', '.join(unknown_keys)}"
                )
            if agent.name != agent.file_stem:
                errors.append(
                    f"{agent.path.as_posix()}: frontmatter name '{agent.name}' must match source filename stem "
                    f"'{agent.file_stem}' for .agent.md naming consistency"
                )

        subagents, unresolved = extract_subagents(agent.body, available_agent_names)
        if args.strict and unresolved:
            errors.append(
                f"{agent.path.as_posix()}: unresolved @agent reference(s): {', '.join(unresolved)}"
            )

        body_main = adapt_body(agent.name, agent.body, solo_mode=False)
        content_main = build_agent_markdown(
            name=agent.name,
            description=agent.description,
            body=body_main,
            subagents=subagents,
            model_setting=model_settings.get(agent.name),
        )
        main_path = target_dir / f"{agent.file_stem}.agent.md"
        collect_generated(generated, generated_names, main_path, content_main, errors)

        if args.emit_fallback and agent.name.startswith(ORCHESTRATOR_PREFIX):
            solo_name = f"{agent.name}-solo"
            body_solo = adapt_body(agent.name, agent.body, solo_mode=True)
            content_solo = build_agent_markdown(
                name=solo_name,
                description=f"{agent.description} (fallback: no subagents)",
                body=body_solo,
                subagents=[],
                model_setting=model_settings.get(agent.name),
            )
            solo_path = target_dir / f"{agent.file_stem}-solo.agent.md"
            collect_generated(
                generated, generated_names, solo_path, content_solo, errors
            )

    if args.strict:
        for out_path, out_content in generated:
            if "$ARGUMENTS" in out_content:
                errors.append(
                    f"{out_path.as_posix()}: output still contains '$ARGUMENTS'"
                )

    if errors:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"- {err}", file=sys.stderr)
        return 2

    if args.dry_run:
        print(
            f"Dry run: would generate {len(generated)} files into {target_dir.as_posix()}"
        )
        for out_path, _ in generated:
            print(f"- {out_path.as_posix()}")
        for stale_path in find_stale_generated_outputs(target_dir, generated):
            print(f"- remove stale generated file: {stale_path.as_posix()}")
        return 0

    target_dir.mkdir(parents=True, exist_ok=True)
    for stale_path in find_stale_generated_outputs(target_dir, generated):
        stale_path.unlink()
        print(f"Removed stale generated file: {stale_path.as_posix()}")
    for out_path, out_content in generated:
        write_text(out_path, out_content)

    print(f"Generated {len(generated)} files into {target_dir.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
