#!/usr/bin/env python3
import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


FRONTMATTER_BOUNDARY = re.compile(r"^\s*---\s*$")
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$")
AGENT_REF_RE = re.compile(r"@([a-z0-9][a-z0-9-]*(?:\*)?)")
ROLE_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")

KNOWN_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "tools",
    "model",
    "agent",
}

ORCHESTRATOR_PREFIX = "orchestrator-"
EXECUTOR_WILDCARD = "executor-*"
GENERATED_MARKER = "# Generated by scripts/export-codex-agents.py"


@dataclass
class AgentSource:
    path: Path
    file_stem: str
    name: str
    description: str
    body: str
    fm_keys: Set[str]
    model: Optional[str]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_quotes(value: str) -> str:
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        return value[1:-1]
    return value


def parse_frontmatter(content: str, path: Path) -> Tuple[Dict[str, str], str]:
    lines = content.splitlines()
    if not lines or not FRONTMATTER_BOUNDARY.match(lines[0]):
        raise ValueError(f"{path.as_posix()}: missing frontmatter block")

    end_idx: Optional[int] = None
    for idx in range(1, len(lines)):
        if FRONTMATTER_BOUNDARY.match(lines[idx]):
            end_idx = idx
            break
    if end_idx is None:
        raise ValueError(f"{path.as_posix()}: unterminated frontmatter block")

    fm: Dict[str, str] = {}
    for line in lines[1:end_idx]:
        match = TOP_LEVEL_KEY_RE.match(line)
        if match is None:
            continue
        key = match.group(1).strip()
        value = match.group(2).strip()
        fm[key] = strip_quotes(value)

    body = "\n".join(lines[end_idx + 1 :])
    if content.endswith("\n"):
        body += "\n"
    return fm, body


def parse_source_agents(source_agents_dir: Path) -> List[AgentSource]:
    agents: List[AgentSource] = []
    for path in sorted(source_agents_dir.glob("*.md")):
        source = read_text(path)
        fm, body = parse_frontmatter(source, path)
        name = fm.get("name", "").strip()
        description = fm.get("description", "").strip()
        if not name:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'name'"
            )
        if not description:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'description'"
            )
        model = fm.get("model", "").strip() or None
        agents.append(
            AgentSource(
                path=path,
                file_stem=path.stem,
                name=name,
                description=description,
                body=body,
                fm_keys=set(fm.keys()),
                model=model,
            )
        )
    return agents


def parse_catalog_agents(catalog_path: Path) -> Set[str]:
    if not catalog_path.exists():
        return set()
    rows = read_text(catalog_path).splitlines()
    agents: Set[str] = set()
    for line in rows:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [part.strip() for part in stripped.split("|")]
        if len(parts) < 3:
            continue
        agent = parts[1]
        if agent in {"", "Agent"}:
            continue
        if set(agent) <= {"-"}:
            continue
        agents.add(agent)
    return agents


def ordered_unique(values: Sequence[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def expand_ref_token(
    token: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    if token == EXECUTOR_WILDCARD:
        return ["executor-core", "executor-advanced"], []
    if token.endswith("*"):
        return [], [token]
    if token in available_agents:
        return [token], []
    return [], [token]


def extract_subagents(
    body: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    resolved: List[str] = []
    unresolved: List[str] = []
    for match in AGENT_REF_RE.finditer(body):
        token = match.group(1)
        expanded, unknown = expand_ref_token(token, available_agents)
        resolved.extend(expanded)
        unresolved.extend(unknown)
    return ordered_unique(resolved), ordered_unique(unresolved)


def make_input_adapter(agent_name: str) -> str:
    suffix = agent_name[len(ORCHESTRATOR_PREFIX) :]
    command_token = f"/run-{suffix}"
    return (
        "## Codex Input Adapter\n\n"
        "Codex role configs do not provide the OpenCode positional input variable.\n"
        "Use the user's latest message as `raw_input`.\n"
        f"If `raw_input` starts with `{command_token}`, remove that first token before parsing flags.\n"
        "Then apply the existing flag parsing protocol unchanged.\n"
    )


def make_role_reference_adapter() -> str:
    return (
        "## Codex Agent Role Adapter\n\n"
        "Interpret source `@agent-name` references in these instructions as references to generated role names defined in the `.codex/config.toml`.\n"
        "When you decide to spawn or route work, use the corresponding role names directly.\n"
    )


def adapt_body(agent_name: str, original_body: str, has_subagents: bool) -> str:
    body = original_body.replace("$ARGUMENTS", "raw_input")
    blocks: List[str] = []
    if agent_name.startswith(ORCHESTRATOR_PREFIX):
        blocks.append(make_input_adapter(agent_name))
    if has_subagents:
        blocks.append(make_role_reference_adapter())
    blocks.append(body.lstrip("\n"))
    return "\n\n".join(blocks).rstrip() + "\n"


def toml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def toml_multiline_string(value: str) -> str:
    normalized = value.rstrip("\n")
    lines = normalized.split("\n") if normalized else [""]
    escaped = [json.dumps(line, ensure_ascii=False)[1:-1] for line in lines]
    return '"""\n' + "\n".join(escaped) + '\n"""'


def build_role_config(agent: AgentSource, body: str) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        f"# Source: {agent.path.as_posix()}",
        "# This file is safe to regenerate. Edit the source OpenCode agent instead.",
        "",
    ]
    if agent.model:
        lines.append(f"model = {toml_quote(agent.model)}")
    lines.append(f"developer_instructions = {toml_multiline_string(body)}")
    lines.append("")
    return "\n".join(lines)


def build_root_config(
    agents: Sequence[AgentSource],
    *,
    enable_feature: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
) -> str:
    lines: List[str] = [
        GENERATED_MARKER,
        "# Generated Codex multi-agent config from opencode/agents/*.md.",
        "# If you already maintain your own .codex/config.toml, merge the generated",
        "# [features] and [agents] sections instead of overwriting your custom settings.",
        "",
    ]

    if enable_feature:
        lines.extend(
            [
                "[features]",
                "multi_agent = true",
                "",
            ]
        )

    lines.extend(
        [
            "[agents]",
            f"max_threads = {max_threads}",
            f"max_depth = {max_depth}",
        ]
    )
    if job_max_runtime_seconds is not None:
        lines.append(f"job_max_runtime_seconds = {job_max_runtime_seconds}")
    lines.append("")

    for agent in agents:
        lines.extend(
            [
                f"[agents.{agent.name}]",
                f"description = {toml_quote(agent.description)}",
                f"config_file = {toml_quote(f'agents/{agent.file_stem}.toml')}",
                "",
            ]
        )

    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def collect_generated(
    generated: List[Tuple[Path, str]],
    generated_names: Set[str],
    path: Path,
    content: str,
    errors: List[str],
) -> None:
    key = path.as_posix().lower()
    if key in generated_names:
        errors.append(f"Duplicate generated output filename: {path.as_posix()}")
        return
    generated_names.add(key)
    generated.append((path, content))


def validate_overwrite_policy(
    generated: Sequence[Tuple[Path, str]], force: bool, errors: List[str]
) -> None:
    if force:
        return
    for out_path, _ in generated:
        if not out_path.exists():
            continue
        existing = read_text(out_path)
        if GENERATED_MARKER not in existing.splitlines()[:3]:
            errors.append(
                f"{out_path.as_posix()}: existing file was not generated by this script; rerun with --force to overwrite"
            )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export OpenCode agents into Codex multi-agent role config files."
    )
    parser.add_argument(
        "--source-agents",
        default="opencode/agents",
        help="Directory containing source OpenCode agent markdown files.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Target `.codex`-style directory where `config.toml` and `agents/*.toml` will be generated.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting non-generated existing files.",
    )
    parser.add_argument(
        "--max-threads",
        type=int,
        default=6,
        help="Value written to `agents.max_threads` in generated config.toml (default: 6).",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=1,
        help="Value written to `agents.max_depth` in generated config.toml (default: 1).",
    )
    parser.add_argument(
        "--job-max-runtime-seconds",
        type=int,
        default=None,
        help="Optional value written to `agents.job_max_runtime_seconds`.",
    )
    parser.add_argument(
        "--enable-feature-flag",
        dest="enable_feature_flag",
        action="store_true",
        default=True,
        help="Emit `[features] multi_agent = true` in generated config.toml (default: enabled).",
    )
    parser.add_argument(
        "--no-enable-feature-flag",
        dest="enable_feature_flag",
        action="store_false",
        help="Do not emit the `[features]` block.",
    )
    args = parser.parse_args()

    if args.max_threads < 1:
        print("--max-threads must be >= 1", file=sys.stderr)
        return 2
    if args.max_depth < 0:
        print("--max-depth must be >= 0", file=sys.stderr)
        return 2
    if args.job_max_runtime_seconds is not None and args.job_max_runtime_seconds < 1:
        print("--job-max-runtime-seconds must be >= 1 when provided", file=sys.stderr)
        return 2

    source_agents_dir = Path(args.source_agents).expanduser()
    target_dir = Path(args.target_dir).expanduser()
    catalog_path = Path(args.catalog).expanduser()

    if not source_agents_dir.exists():
        print(f"Source directory not found: {source_agents_dir}", file=sys.stderr)
        return 2

    try:
        source_agents = parse_source_agents(source_agents_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    available_agent_names = {agent.name for agent in source_agents}
    catalog_agents = parse_catalog_agents(catalog_path)

    errors: List[str] = []
    generated: List[Tuple[Path, str]] = []
    generated_names: Set[str] = set()

    if args.strict and catalog_agents:
        if catalog_agents != available_agent_names:
            missing_in_source = sorted(catalog_agents - available_agent_names)
            missing_in_catalog = sorted(available_agent_names - catalog_agents)
            if missing_in_source:
                errors.append(
                    "Agents listed in AGENTS.md but missing in source: "
                    + ", ".join(missing_in_source)
                )
            if missing_in_catalog:
                errors.append(
                    "Agents present in source but missing in AGENTS.md: "
                    + ", ".join(missing_in_catalog)
                )

    for agent in source_agents:
        if args.strict:
            unknown_keys = sorted(agent.fm_keys - KNOWN_SOURCE_FRONTMATTER_KEYS)
            if unknown_keys:
                errors.append(
                    f"{agent.path.as_posix()}: unknown frontmatter key(s): {', '.join(unknown_keys)}"
                )
            if agent.name != agent.file_stem:
                errors.append(
                    f"{agent.path.as_posix()}: frontmatter name '{agent.name}' must match source filename stem "
                    f"'{agent.file_stem}' for Codex role naming consistency"
                )
            if not ROLE_NAME_RE.match(agent.name):
                errors.append(
                    f"{agent.path.as_posix()}: agent name '{agent.name}' is not a valid Codex role key"
                )

        subagents, unresolved = extract_subagents(agent.body, available_agent_names)
        if args.strict and unresolved:
            errors.append(
                f"{agent.path.as_posix()}: unresolved @agent reference(s): {', '.join(unresolved)}"
            )

        body = adapt_body(agent.name, agent.body, has_subagents=bool(subagents))
        content = build_role_config(agent, body)
        out_path = target_dir / "agents" / f"{agent.file_stem}.toml"
        collect_generated(generated, generated_names, out_path, content, errors)

    root_config = build_root_config(
        source_agents,
        enable_feature=args.enable_feature_flag,
        max_threads=args.max_threads,
        max_depth=args.max_depth,
        job_max_runtime_seconds=args.job_max_runtime_seconds,
    )
    collect_generated(
        generated, generated_names, target_dir / "config.toml", root_config, errors
    )

    if not args.dry_run:
        validate_overwrite_policy(generated, force=args.force, errors=errors)

    if errors:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"- {err}", file=sys.stderr)
        return 2

    if args.dry_run:
        print(
            f"Dry run: would generate {len(generated)} files into {target_dir.as_posix()}"
        )
        for out_path, _ in generated:
            print(f"- {out_path.as_posix()}")
        return 0

    (target_dir / "agents").mkdir(parents=True, exist_ok=True)
    for out_path, out_content in generated:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        write_text(out_path, out_content)

    print(f"Generated {len(generated)} files into {target_dir.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
