#!/usr/bin/env python3
import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple


FRONTMATTER_BOUNDARY = re.compile(r"^\s*---\s*$")
TOP_LEVEL_KEY_RE = re.compile(r"^([A-Za-z0-9_-]+)\s*:\s*(.*)$")
TOOL_ENTRY_RE = re.compile(r"^  ([A-Za-z0-9_-]+)\s*:\s*(true|false)\s*$")
AGENT_REF_RE = re.compile(r"@([a-z0-9][a-z0-9-]*(?:\*)?)")
FENCE_RE = re.compile(r"^[ \t]{0,3}(`{3,}|~{3,})(.*)$")
HANDOFF_PROTOCOL_RE = re.compile(
    r"(?ms)^# HANDOFF PROTOCOL \(GLOBAL\)\n.*?(?=^## AGENT RESPONSIBILITY MATRIX|^# )"
)
RESPONSIBILITY_MATRIX_RE = re.compile(
    r"(?ms)^## AGENT RESPONSIBILITY MATRIX\n\n"
    r"\| Agent \| Primary Responsibility \| Forbidden Actions \|\n"
    r"\|[-| ]+\|\n"
    r"(?P<rows>(?:\|.*\|\n)+)"
)
FLAG_PARSING_INTRO_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} FLAG PARSING PROTOCOL(?: \([^)]+\))?)\n\n"
    r"You are given positional parameters via the slash command\.\n\n"
    r"Parse `raw_input`: tokens before the first `--\*` flag form `main_task_prompt`; `--\*` tokens are flags\.(?P<resume> If `main_task_prompt` is empty and `resume_mode = true`, treat as resume-only invocation\.)?\n"
)
RESPONSE_MODE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} RESPONSE MODE \(DEFAULT\))\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)
CONFIRM_VERBOSE_RE = re.compile(
    r"(?ms)^(?P<heading>#{1,2} CONFIRM / VERBOSE PROTOCOL)\n\n"
    r"(?P<bullets>(?:- [^\n]+\n)+)"
)

KNOWN_SOURCE_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "tools",
    "agent",
}

SCALAR_FRONTMATTER_KEYS = {
    "name",
    "description",
    "mode",
    "hidden",
    "temperature",
    "agent",
}

UNSUPPORTED_VALUE_PREFIXES = ("[", "{", "|", ">")

ORCHESTRATOR_PREFIX = "orchestrator-"
GENERATED_MARKER = "<!-- Generated by scripts/export-claude-agents.py"
RUNNER_BEGIN = "<!-- BEGIN agents-pipeline-runner -->"
RUNNER_END = "<!-- END agents-pipeline-runner -->"
CLAUDE_TOOL_MAP = {
    "read": "Read",
    "edit": "Edit",
    "write": "Write",
    "grep": "Grep",
    "glob": "Glob",
    "bash": "Bash",
    "webfetch": "WebFetch",
    "google_search": "WebSearch",
}
CLAUDE_TOOL_ORDER = [
    "Read",
    "Edit",
    "Write",
    "Grep",
    "Glob",
    "Bash",
    "WebFetch",
    "WebSearch",
]


@dataclass
class AgentSource:
    path: Path
    file_stem: str
    name: str
    description: str
    body: str
    fm_keys: Set[str]
    tools: Dict[str, bool]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def strip_quotes(value: str) -> str:
    if len(value) >= 2 and (
        (value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")
    ):
        return value[1:-1]
    return value


def parse_scalar_frontmatter_value(path: Path, key: str, raw_value: str) -> str:
    value = raw_value.strip()
    if not value:
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' must use a single-line scalar value"
        )
    if value.startswith(UNSUPPORTED_VALUE_PREFIXES):
        raise ValueError(
            f"{path.as_posix()}: frontmatter key '{key}' uses unsupported structured value '{value}'"
        )
    return strip_quotes(value)


def parse_frontmatter(
    content: str, path: Path
) -> Tuple[Dict[str, str], Dict[str, bool], str]:
    lines = content.splitlines()
    if not lines or not FRONTMATTER_BOUNDARY.match(lines[0]):
        raise ValueError(f"{path.as_posix()}: missing frontmatter block")

    end_idx: Optional[int] = None
    for idx in range(1, len(lines)):
        if FRONTMATTER_BOUNDARY.match(lines[idx]):
            end_idx = idx
            break
    if end_idx is None:
        raise ValueError(f"{path.as_posix()}: unterminated frontmatter block")

    fm: Dict[str, str] = {}
    tools: Dict[str, bool] = {}
    saw_tools = False
    frontmatter_lines = lines[1:end_idx]
    idx = 0
    while idx < len(frontmatter_lines):
        line = frontmatter_lines[idx]
        if not line.strip():
            raise ValueError(
                f"{path.as_posix()}: blank lines are not allowed inside frontmatter"
            )
        if line[:1].isspace():
            raise ValueError(
                f"{path.as_posix()}: unexpected indented frontmatter line '{line}'"
            )

        match = TOP_LEVEL_KEY_RE.match(line)
        if match is None:
            raise ValueError(f"{path.as_posix()}: malformed frontmatter line '{line}'")

        key = match.group(1).strip()
        raw_value = match.group(2).strip()
        if key in {"model", "provider"}:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported; configure model/provider in runtime config instead"
            )
        if key not in KNOWN_SOURCE_FRONTMATTER_KEYS:
            raise ValueError(f"{path.as_posix()}: unsupported frontmatter key '{key}'")
        if key in fm or (key == "tools" and saw_tools):
            raise ValueError(f"{path.as_posix()}: duplicate frontmatter key '{key}'")

        if key == "tools":
            saw_tools = True
            if raw_value:
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must not have an inline value"
                )
            idx += 1
            if idx >= len(frontmatter_lines) or not frontmatter_lines[idx].startswith(
                "  "
            ):
                raise ValueError(
                    f"{path.as_posix()}: frontmatter key 'tools' must contain indented boolean entries"
                )
            while idx < len(frontmatter_lines) and frontmatter_lines[idx].startswith(
                "  "
            ):
                tool_line = frontmatter_lines[idx]
                tool_match = TOOL_ENTRY_RE.match(tool_line)
                if tool_match is None:
                    raise ValueError(
                        f"{path.as_posix()}: malformed tools entry '{tool_line}'"
                    )
                tool_name = tool_match.group(1)
                if tool_name in tools:
                    raise ValueError(
                        f"{path.as_posix()}: duplicate tools entry '{tool_name}'"
                    )
                tools[tool_name] = tool_match.group(2) == "true"
                idx += 1
            continue

        if key not in SCALAR_FRONTMATTER_KEYS:
            raise ValueError(
                f"{path.as_posix()}: frontmatter key '{key}' is not supported in this exporter"
            )
        fm[key] = parse_scalar_frontmatter_value(path, key, raw_value)
        idx += 1

    body = "\n".join(lines[end_idx + 1 :])
    if content.endswith("\n"):
        body += "\n"
    return fm, tools, body


def parse_source_agents(source_agents_dir: Path) -> List[AgentSource]:
    agents: List[AgentSource] = []
    for path in sorted(source_agents_dir.glob("*.md")):
        source = read_text(path)
        fm, tools, body = parse_frontmatter(source, path)
        name = fm.get("name", "").strip()
        description = fm.get("description", "").strip()
        if not name:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'name'"
            )
        if not description:
            raise ValueError(
                f"{path.as_posix()}: missing required frontmatter key 'description'"
            )
        agents.append(
            AgentSource(
                path=path,
                file_stem=path.stem,
                name=name,
                description=description,
                body=body,
                fm_keys=set(fm.keys()) | ({"tools"} if tools else set()),
                tools=tools,
            )
        )
    return agents


def parse_catalog_agents(catalog_path: Path) -> Set[str]:
    if not catalog_path.exists():
        return set()
    rows = read_text(catalog_path).splitlines()
    agents: Set[str] = set()
    for line in rows:
        stripped = line.strip()
        if not stripped.startswith("|"):
            continue
        parts = [part.strip() for part in stripped.split("|")]
        if len(parts) < 3:
            continue
        agent = parts[1]
        if agent in {"", "Agent"}:
            continue
        if set(agent) <= {"-"}:
            continue
        agents.add(agent)
    return agents


def ordered_unique(values: Sequence[str]) -> List[str]:
    seen: Set[str] = set()
    out: List[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        out.append(value)
    return out


def compact_markdown(text: str) -> str:
    lines = text.splitlines()
    compacted: List[str] = []
    pending_blank = False
    in_fence = False
    fence_token = ""

    for line in lines:
        fence_match = FENCE_RE.match(line)
        if in_fence:
            compacted.append(line)
            if fence_match and line.strip() == fence_token:
                in_fence = False
                fence_token = ""
            continue

        if fence_match:
            if pending_blank and compacted:
                compacted.append("")
                pending_blank = False
            compacted.append(line)
            in_fence = True
            fence_token = fence_match.group(1)
            continue

        stripped = line.rstrip()
        if not stripped:
            pending_blank = True
            continue

        if pending_blank and compacted:
            compacted.append("")
            pending_blank = False
        compacted.append(stripped)

    out = "\n".join(compacted)
    if text.endswith("\n"):
        out += "\n"
    return out


def ensure_sentence(text: str) -> str:
    return text if text.endswith((".", "!", "?")) else f"{text}."


def minify_handoff_protocol(text: str) -> str:
    match = HANDOFF_PROTOCOL_RE.search(text)
    if not match:
        return text

    section = match.group(0)
    general_match = re.search(
        r"(?m)^## General Handoff Rules\n\n(?P<bullets>(?:- [^\n]+\n)+)",
        section,
    )
    if not general_match:
        return text

    lines = ["# HANDOFF PROTOCOL (GLOBAL)", ""]
    lines.extend(line.rstrip() for line in general_match.group("bullets").strip().splitlines())
    lines.append(
        "- Orchestrator -> subagent: selected for specialization; stay within scope; satisfy the provided Definition of Done exactly."
    )

    if "## EXECUTOR -> REVIEWER HANDOFF" in section:
        lines.append(
            "- Executor -> reviewer: only evidence and DoD satisfaction count; missing or weak evidence means incomplete."
        )
    if "## REVIEWER -> ORCHESTRATOR HANDOFF" in section:
        lines.append(
            "- Reviewer -> orchestrator: reviewer decisions are final. If `status = fail` and `test_only = false`, convert `required_followups` into delta tasks, route them, and retry up to `max_retry_rounds`; if `test_only = true`, skip retries; stop and report blockers when failure persists."
        )

    replacement = "\n".join(lines) + "\n\n"
    return text[: match.start()] + replacement + text[match.end() :]


def minify_agent_responsibility_matrix(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets: List[str] = []
        for raw_row in match.group("rows").strip().splitlines():
            cells = [cell.strip() for cell in raw_row.strip().strip("|").split("|")]
            if len(cells) != 3 or not all(cells):
                return match.group(0)
            bullets.append(
                f"- `{cells[0]}`: {ensure_sentence(cells[1])} Forbidden: {ensure_sentence(cells[2])}"
            )
        return "## AGENT RESPONSIBILITY MATRIX\n\n" + "\n".join(bullets) + "\n"

    return RESPONSIBILITY_MATRIX_RE.sub(repl, text, count=1)


def minify_flag_parsing_intro(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        resume = match.group("resume") or ""
        return (
            f"{match.group('heading')}\n\n"
            "Parse `raw_input`: tokens before the first `--*` flag form `main_task_prompt`; `--*` tokens are flags."
            f"{resume}\n"
        )

    return FLAG_PARSING_INTRO_RE.sub(repl, text, count=1)


def minify_response_mode(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        section = match.group("bullets")
        autopilot_clause = " and `autopilot_mode = false`" if "autopilot_mode = false" in section else ""
        return (
            f"{match.group('heading')}\n\n"
            "- Default to concise final-only reporting: outcome, key deliverables, blockers/errors. Emit stage-by-stage progress only when `--confirm` or `--verbose` requires it"
            f"{autopilot_clause}.\n"
        )

    return RESPONSE_MODE_RE.sub(repl, text, count=1)


def minify_confirm_verbose_protocol(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        bullets = [line.strip()[2:] for line in match.group("bullets").strip().splitlines()]
        if len(bullets) < 2:
            return match.group(0)

        confirm_line = bullets[0]
        verbose_line = bullets[1]
        if "Proceed? [yes / feedback / abort]" not in confirm_line or "On abort: checkpoint and stop." not in confirm_line:
            return match.group(0)

        confirm_label = "`confirm_mode` (when not autopilot)" if "when not autopilot" in confirm_line else "`confirm_mode`"
        waiting_clause = "update status to `waiting_for_user` and " if "waiting_for_user" in confirm_line else ""
        verbose_line = verbose_line.replace("`verbose_mode` (implies confirm): also ", "`verbose_mode` (implies confirm): ")

        return (
            f"{match.group('heading')}\n\n"
            f"- {confirm_label}: after each stage, {waiting_clause}pause with `Proceed? [yes / feedback / abort]`; on abort checkpoint and stop.\n"
            f"- {verbose_line}\n"
        )

    return CONFIRM_VERBOSE_RE.sub(repl, text, count=1)


def minify_orchestrator_runtime_body(agent_name: str, text: str) -> str:
    if not agent_name.startswith(ORCHESTRATOR_PREFIX):
        return text

    text = minify_handoff_protocol(text)
    text = minify_agent_responsibility_matrix(text)
    text = minify_flag_parsing_intro(text)
    text = minify_response_mode(text)
    return minify_confirm_verbose_protocol(text)


def expand_ref_token(
    token: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    if token == "executor-*":
        resolved = [name for name in ("executor",) if name in available_agents]
        missing = [name for name in ("executor",) if name not in available_agents]
        return resolved, missing
    if token.endswith("*"):
        return [], [token]
    if token in available_agents:
        return [token], []
    return [], [token]


def extract_agent_refs(
    body: str, available_agents: Set[str]
) -> Tuple[List[str], List[str]]:
    resolved: List[str] = []
    unresolved: List[str] = []
    for match in AGENT_REF_RE.finditer(body):
        token = match.group(1)
        expanded, unknown = expand_ref_token(token, available_agents)
        resolved.extend(expanded)
        unresolved.extend(unknown)
    return ordered_unique(resolved), ordered_unique(unresolved)


def make_input_adapter(agent_name: str) -> str:
    suffix = agent_name[len(ORCHESTRATOR_PREFIX) :]
    command_token = f"/run-{suffix}"
    helper_token = f"/{suffix}"
    return (
        "## Claude Code Input Adapter\n\n"
        "Use the user's latest message as `raw_input`.\n"
        f"If it starts with `{command_token}` or `{helper_token}`, strip that first token, then apply the existing flag parsing unchanged.\n"
    )


def make_delegation_adapter(resolved_refs: List[str]) -> str:
    lines = [
        "## Claude Code Delegation Protocol\n",
        "Claude Code subagents cannot nest `Agent` calls. When a stage needs `@agent-name` delegation, return a fenced JSON block with the key `dispatch` so the top-level runner can execute it.\n",
        "```json",
        '{ "dispatch": [',
        '    { "id": "T1", "agent": "<agent-name>", "prompt": "<full task handoff>", "deps": [] },',
        '    { "id": "T2", "agent": "<agent-name>", "prompt": "<full task handoff>", "deps": ["T1"], "worktree": "<optional repo path>" }',
        "  ]}",
        "```\n",
        "Rules:",
        "- Include all required inputs, constraints, and expected output format in each task `prompt`.",
        "- Use `deps` for ordering; tasks with no deps may run in parallel.",
        "- Include `worktree` only when the delegated task must run in another repo/worktree; if the runtime cannot honor it, it should stop rather than silently use the current repo.",
        "- The top-level runner executes tasks, collects results, and sends them back if you still have post-dispatch stages (for example synthesis).",
        "- You may interleave orchestrator-owned stages (no dispatch needed) with dispatch blocks.",
        "- Each dispatch block is executed atomically before the orchestrator resumes.",
    ]
    if resolved_refs:
        lines.append("\nAvailable agents for dispatch: " + ", ".join(resolved_refs))
    return "\n".join(lines) + "\n"


def adapt_body(
    agent_name: str,
    original_body: str,
    resolved_refs: Optional[List[str]] = None,
) -> str:
    body = original_body.replace("$ARGUMENTS", "raw_input")
    body = minify_orchestrator_runtime_body(agent_name, body)
    blocks: List[str] = []
    if agent_name.startswith(ORCHESTRATOR_PREFIX):
        blocks.append(make_input_adapter(agent_name))
        blocks.append(make_delegation_adapter(resolved_refs or []))
    blocks.append(body.lstrip("\n"))
    return compact_markdown("\n\n".join(blocks).rstrip() + "\n")


def yaml_quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def map_claude_tools(
    source_tools: Dict[str, bool], *, strict: bool, errors: List[str], path: Path
) -> List[str]:
    mapped: List[str] = []
    for source_name, enabled in source_tools.items():
        if not enabled:
            continue
        mapped_name = CLAUDE_TOOL_MAP.get(source_name)
        if mapped_name is None:
            if strict:
                errors.append(
                    f"{path.as_posix()}: enabled tool '{source_name}' has no Claude Code tool mapping"
                )
            continue
        mapped.append(mapped_name)

    ordered = [tool_name for tool_name in CLAUDE_TOOL_ORDER if tool_name in mapped]
    extras = sorted(
        tool_name for tool_name in mapped if tool_name not in CLAUDE_TOOL_ORDER
    )
    return ordered + extras


def build_agent_markdown(
    *,
    name: str,
    description: str,
    body: str,
    tools: Sequence[str],
) -> str:
    lines: List[str] = [
        "---",
        f"name: {yaml_quote(name)}",
        f"description: {yaml_quote(description)}",
    ]
    if tools:
        lines.append("tools:")
        for tool_name in tools:
            lines.append(f"  - {tool_name}")
    lines.append("---")
    lines.append("")
    lines.append(f"{GENERATED_MARKER} -->")
    lines.append("")
    lines.append(body.rstrip("\n"))
    lines.append("")
    return "\n".join(lines)


def write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def collect_generated(
    generated: List[Tuple[Path, str]],
    generated_names: Set[str],
    path: Path,
    content: str,
    errors: List[str],
) -> None:
    key = path.name.lower()
    if key in generated_names:
        errors.append(f"Duplicate generated output filename: {path.name}")
        return
    generated_names.add(key)
    generated.append((path, content))


def is_generated_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_MARKER in read_text(path)
    except OSError:
        return False


def find_stale_generated_outputs(
    target_dir: Path, generated: Sequence[Tuple[Path, str]]
) -> List[Path]:
    expected = {path.name.lower() for path, _ in generated}
    stale: List[Path] = []
    for existing in sorted(target_dir.glob("*.md")):
        if existing.name.lower() in expected:
            continue
        if is_generated_file(existing):
            stale.append(existing)
    return stale


RUNNER_PROTOCOL = f"""{RUNNER_BEGIN}
## Agents Pipeline — Claude Code Runner Protocol

When you spawn an orchestrator agent (e.g., `@orchestrator-flow`, `@orchestrator-pipeline`)
and it returns a JSON block with a `"dispatch"` key, execute it as follows:

1. Parse the `dispatch` array from the orchestrator response.
2. Tasks with empty `deps` may be spawned in parallel via `Agent(subagent_type=..., prompt=...)`.
3. Tasks whose `deps` reference earlier task IDs wait for those to complete;
   include dependency results in the prompt.
4. If a task includes `worktree`, execute it in that repo/worktree when runtime support exists.
   If the runtime cannot honor the requested worktree, stop and report the blocker.
5. After all tasks complete, if the orchestrator has post-dispatch stages
   (e.g., synthesis), send collected results back via `SendMessage`.

Dispatch plan format:
```json
{{ "dispatch": [
    {{ "id": "T1", "agent": "executor", "prompt": "...", "deps": [] }},
    {{ "id": "T2", "agent": "reviewer", "prompt": "...", "deps": ["T1"] }},
    {{ "id": "T3", "agent": "orchestrator-pipeline", "prompt": "...", "deps": ["T2"], "worktree": "../target-project" }}
  ]}}
```

For simple single-file tasks, skip the orchestrator and use `@executor` directly.
{RUNNER_END}
"""


def merge_runner_protocol(claude_md_path: Path, *, dry_run: bool) -> None:
    """Insert or replace the runner protocol section in a CLAUDE.md file."""
    if claude_md_path.exists():
        content = read_text(claude_md_path)
        begin = content.find(RUNNER_BEGIN)
        end = content.find(RUNNER_END)
        if begin != -1 and end != -1:
            # Replace existing block (include the end marker + trailing newline)
            end += len(RUNNER_END)
            if end < len(content) and content[end] == "\n":
                end += 1
            new_content = content[:begin] + RUNNER_PROTOCOL + content[end:]
        else:
            # Append to end
            new_content = content.rstrip("\n") + "\n\n" + RUNNER_PROTOCOL
    else:
        new_content = RUNNER_PROTOCOL

    if dry_run:
        action = "update" if claude_md_path.exists() else "create"
        print(f"Would {action} runner protocol in {claude_md_path.as_posix()}")
    else:
        claude_md_path.parent.mkdir(parents=True, exist_ok=True)
        write_text(claude_md_path, new_content)
        print(f"Runner protocol written to {claude_md_path.as_posix()}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Export OpenCode agents into Claude Code markdown subagent files."
    )
    parser.add_argument(
        "--source-agents",
        default="opencode/agents",
        help="Directory containing source OpenCode agent markdown files.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Directory where Claude Code markdown agent files will be generated.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--claude-md",
        default=None,
        help="Path to CLAUDE.md where the runner protocol section will be injected. "
        "If omitted, no runner protocol is written.",
    )
    args = parser.parse_args()

    source_agents_dir = Path(args.source_agents).expanduser()
    target_dir = Path(args.target_dir).expanduser()
    catalog_path = Path(args.catalog).expanduser()

    if not source_agents_dir.exists():
        print(f"Source directory not found: {source_agents_dir}", file=sys.stderr)
        return 2
    if target_dir.exists() and not target_dir.is_dir():
        print(f"Target path is not a directory: {target_dir}", file=sys.stderr)
        return 2

    try:
        source_agents = parse_source_agents(source_agents_dir)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    available_agent_names = {agent.name for agent in source_agents}
    catalog_agents = parse_catalog_agents(catalog_path)
    known_reference_agents = available_agent_names | catalog_agents

    errors: List[str] = []
    generated: List[Tuple[Path, str]] = []
    generated_names: Set[str] = set()

    if args.strict and catalog_agents:
        if catalog_agents != available_agent_names:
            missing_in_source = sorted(catalog_agents - available_agent_names)
            missing_in_catalog = sorted(available_agent_names - catalog_agents)
            if missing_in_source:
                errors.append(
                    "Agents listed in AGENTS.md but missing in source: "
                    + ", ".join(missing_in_source)
                )
            if missing_in_catalog:
                errors.append(
                    "Agents present in source but missing in AGENTS.md: "
                    + ", ".join(missing_in_catalog)
                )

    for agent in source_agents:
        if args.strict:
            unknown_keys = sorted(agent.fm_keys - KNOWN_SOURCE_FRONTMATTER_KEYS)
            if unknown_keys:
                errors.append(
                    f"{agent.path.as_posix()}: unknown frontmatter key(s): {', '.join(unknown_keys)}"
                )
            if agent.name != agent.file_stem:
                errors.append(
                    f"{agent.path.as_posix()}: frontmatter name '{agent.name}' must match source filename stem "
                    f"'{agent.file_stem}' for Claude Code file naming consistency"
                )
            if not agent.name.strip():
                errors.append(f"{agent.path.as_posix()}: agent name must not be empty")
            if not agent.description.strip():
                errors.append(
                    f"{agent.path.as_posix()}: agent description must not be empty"
                )

        resolved_refs, unresolved = extract_agent_refs(
            agent.body, known_reference_agents
        )
        if args.strict and unresolved:
            errors.append(
                f"{agent.path.as_posix()}: unresolved @agent reference(s): {', '.join(unresolved)}"
            )

        body = adapt_body(agent.name, agent.body, resolved_refs)
        tools = map_claude_tools(
            agent.tools, strict=args.strict, errors=errors, path=agent.path
        )
        # NOTE: Orchestrators do NOT get the Agent tool in Claude Code.
        # They produce dispatch plans instead; the top-level runner executes them.
        # See make_delegation_adapter() for the protocol.
        content = build_agent_markdown(
            name=agent.name,
            description=agent.description,
            body=body,
            tools=tools,
        )
        out_path = target_dir / f"{agent.file_stem}.md"
        collect_generated(generated, generated_names, out_path, content, errors)

    if args.strict:
        for out_path, out_content in generated:
            if "$ARGUMENTS" in out_content:
                errors.append(
                    f"{out_path.as_posix()}: output still contains '$ARGUMENTS'"
                )

    if errors:
        print("Validation failed:", file=sys.stderr)
        for err in errors:
            print(f"- {err}", file=sys.stderr)
        return 2

    if args.dry_run:
        print(
            f"Dry run: would generate {len(generated)} files into {target_dir.as_posix()}"
        )
        for out_path, _ in generated:
            print(f"- {out_path.as_posix()}")
        for stale_path in find_stale_generated_outputs(target_dir, generated):
            print(f"- remove stale generated file: {stale_path.as_posix()}")
        if args.claude_md:
            merge_runner_protocol(Path(args.claude_md).expanduser(), dry_run=True)
        return 0

    target_dir.mkdir(parents=True, exist_ok=True)
    for stale_path in find_stale_generated_outputs(target_dir, generated):
        stale_path.unlink()
        print(f"Removed stale generated file: {stale_path.as_posix()}")
    for out_path, out_content in generated:
        write_text(out_path, out_content)

    print(f"Generated {len(generated)} files into {target_dir.as_posix()}")

    if args.claude_md:
        merge_runner_protocol(Path(args.claude_md).expanduser(), dry_run=False)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
