#!/usr/bin/env python3
import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence


GENERATED_ROLE_MARKER = "# Generated by scripts/export-codex-agents.py"
MANIFEST_FILENAME = ".agents-pipeline-codex-manifest.json"
TABLE_RE = re.compile(r"^\s*\[([^\[\]]+)\]\s*$")
ARRAY_TABLE_RE = re.compile(r"^\s*\[\[([^\[\]]+)\]\]\s*$")
DEFAULT_MAX_THREADS = 6
DEFAULT_MAX_DEPTH = 2
DEFAULT_PROFILE_DIR = "opencode/tools/agent-profiles"
DEFAULT_MODEL_SET_DIR = "codex/tools/model-sets"
SUPPORT_TREE_DIRS = ("agents", "commands", "protocols", "tools")


@dataclass
class Block:
    kind: str
    path: Optional[str]
    lines: List[str]


@dataclass(frozen=True)
class AssetLayout:
    name: str
    asset_root: Path
    support_tree_source: Path
    export_script: Path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def has_support_tree(root: Path) -> bool:
    return all((root / name).is_dir() for name in SUPPORT_TREE_DIRS)


def resolve_asset_layout(script_path: Path) -> AssetLayout:
    asset_root = script_path.parent.parent
    export_script = asset_root / "scripts" / "export-codex-agents.py"

    if has_support_tree(asset_root):
        return AssetLayout(
            name="installed",
            asset_root=asset_root,
            support_tree_source=asset_root,
            export_script=export_script,
        )

    return AssetLayout(
        name="repo",
        asset_root=asset_root,
        support_tree_source=asset_root / "opencode",
        export_script=export_script,
    )


def parse_blocks(text: str) -> List[Block]:
    blocks: List[Block] = []
    current_kind = "preamble"
    current_path: Optional[str] = None
    current_lines: List[str] = []

    for line in text.splitlines():
        array_match = ARRAY_TABLE_RE.match(line)
        table_match = TABLE_RE.match(line)
        if array_match or table_match:
            if current_lines or current_kind != "preamble" or not blocks:
                blocks.append(Block(current_kind, current_path, current_lines))
            current_kind = "array" if array_match else "table"
            current_path = (array_match or table_match).group(1).strip()
            current_lines = [line]
            continue
        current_lines.append(line)

    if current_lines or current_kind != "preamble" or not blocks:
        blocks.append(Block(current_kind, current_path, current_lines))
    return blocks


def render_blocks(blocks: Sequence[Block]) -> str:
    rendered: List[str] = []
    for block in blocks:
        lines = list(block.lines)
        while lines and not lines[-1].strip():
            lines.pop()
        if not lines:
            continue
        rendered.append("\n".join(lines))
    if not rendered:
        return ""
    return "\n\n".join(rendered).rstrip() + "\n"


def find_block_index(blocks: Sequence[Block], *, kind: str, path: str) -> Optional[int]:
    for idx, block in enumerate(blocks):
        if block.kind == kind and block.path == path:
            return idx
    return None


def insert_index_before_prefix(blocks: Sequence[Block], prefix: str) -> Optional[int]:
    for idx, block in enumerate(blocks):
        if (
            block.kind in {"table", "array"}
            and block.path
            and block.path.startswith(prefix)
        ):
            return idx
    return None


def ensure_root_table(blocks: List[Block], path: str) -> Block:
    existing_idx = find_block_index(blocks, kind="table", path=path)
    if existing_idx is not None:
        return blocks[existing_idx]

    child_idx = insert_index_before_prefix(blocks, path + ".")
    if child_idx is not None:
        insert_idx = child_idx
    elif blocks and blocks[0].kind == "preamble":
        insert_idx = 1
    else:
        insert_idx = len(blocks)

    block = Block("table", path, [f"[{path}]"])
    blocks.insert(insert_idx, block)
    return block


def upsert_assignment(block: Block, key: str, value: str) -> None:
    assign_re = re.compile(rf"^\s*{re.escape(key)}\s*=")
    new_line = f"{key} = {value}"
    output = [block.lines[0]]
    replaced = False

    for line in block.lines[1:]:
        if assign_re.match(line) and not line.lstrip().startswith("#"):
            if not replaced:
                output.append(new_line)
                replaced = True
            continue
        output.append(line)

    if not replaced:
        while len(output) > 1 and not output[-1].strip():
            output.pop()
        output.append(new_line)

    block.lines = output


def parse_manifest(path: Path) -> Optional[Dict[str, List[str]]]:
    if not path.exists():
        return None
    data = json.loads(read_text(path))
    names = data.get("managed_agent_names")
    files = data.get("managed_agent_files")
    if not isinstance(names, list) or not isinstance(files, list):
        raise ValueError(f"{path.as_posix()}: invalid manifest shape")
    return {
        "managed_agent_names": [str(name) for name in names],
        "managed_agent_files": [str(file_path) for file_path in files],
    }


def write_manifest(
    path: Path, *, agent_names: Sequence[str], agent_files: Sequence[str]
) -> None:
    payload = {
        "managed_agent_names": sorted(agent_names),
        "managed_agent_files": sorted(agent_files),
    }
    write_text(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def is_generated_role_file(path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_ROLE_MARKER in read_text(path).splitlines()[:3]
    except OSError:
        return False


def infer_previous_managed(target_dir: Path) -> Dict[str, List[str]]:
    manifest_path = target_dir / MANIFEST_FILENAME
    manifest = parse_manifest(manifest_path)
    if manifest is not None:
        return manifest

    names: List[str] = []
    files: List[str] = []
    agents_dir = target_dir / "agents"
    if agents_dir.exists():
        for role_file in sorted(agents_dir.glob("*.toml")):
            if not is_generated_role_file(role_file):
                continue
            names.append(role_file.stem)
            files.append(role_file.relative_to(target_dir).as_posix())
    return {
        "managed_agent_names": names,
        "managed_agent_files": files,
    }


def build_export_command(
    export_script: Path,
    source_agents_dir: Path,
    catalog_path: Path,
    target_dir: Path,
    *,
    strict: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
    resolve_opencode_refs_to: Optional[Path],
    agent_profile: Optional[str] = None,
    model_set: Optional[str] = None,
    profile_dir: Optional[Path] = None,
    model_set_dir: Optional[Path] = None,
    uniform_model: Optional[str] = None,
) -> List[str]:
    command = [
        sys.executable,
        export_script.as_posix(),
        "--source-agents",
        source_agents_dir.as_posix(),
        "--target-dir",
        target_dir.as_posix(),
        "--catalog",
        catalog_path.as_posix(),
        "--max-threads",
        str(max_threads),
        "--max-depth",
        str(max_depth),
    ]
    if strict:
        command.append("--strict")
    if job_max_runtime_seconds is not None:
        command.extend(["--job-max-runtime-seconds", str(job_max_runtime_seconds)])
    if resolve_opencode_refs_to is not None:
        command.extend(
            ["--resolve-opencode-refs-to", resolve_opencode_refs_to.as_posix()]
        )
    if agent_profile is not None:
        command.extend(["--agent-profile", agent_profile])
    if model_set is not None:
        command.extend(["--model-set", model_set])
    if profile_dir is not None:
        command.extend(["--profile-dir", profile_dir.as_posix()])
    if model_set_dir is not None:
        command.extend(["--model-set-dir", model_set_dir.as_posix()])
    if uniform_model is not None:
        command.extend(["--uniform-model", uniform_model])
    return command


def resolve_temp_root(*, repo_root: Path, temp_dir: Optional[str]) -> Path:
    if temp_dir:
        return Path(temp_dir).expanduser()
    return repo_root / ".tmp"


def run_export(
    export_script: Path,
    source_agents_dir: Path,
    catalog_path: Path,
    *,
    strict: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
    temp_root: Path,
    resolve_opencode_refs_to: Optional[Path],
    agent_profile: Optional[str] = None,
    model_set: Optional[str] = None,
    profile_dir: Optional[Path] = None,
    model_set_dir: Optional[Path] = None,
    uniform_model: Optional[str] = None,
) -> Path:
    try:
        temp_root.mkdir(parents=True, exist_ok=True)
        temp_dir = Path(
            tempfile.mkdtemp(prefix="agents-pipeline-codex-", dir=temp_root)
        )
    except OSError as exc:
        raise RuntimeError(
            f"Unable to create temp dir under {temp_root.as_posix()}: {exc}"
        ) from exc
    command = build_export_command(
        export_script,
        source_agents_dir,
        catalog_path,
        temp_dir,
        strict=strict,
        max_threads=max_threads,
        max_depth=max_depth,
        job_max_runtime_seconds=job_max_runtime_seconds,
        resolve_opencode_refs_to=resolve_opencode_refs_to,
        agent_profile=agent_profile,
        model_set=model_set,
        profile_dir=profile_dir,
        model_set_dir=model_set_dir,
        uniform_model=uniform_model,
    )
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        if result.stdout:
            sys.stderr.write(result.stdout)
        if result.stderr:
            sys.stderr.write(result.stderr)
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise RuntimeError(
            f"Codex role export failed with exit code {result.returncode}."
        )
    return temp_dir


def extract_generated_agent_blocks(config_text: str) -> Dict[str, Block]:
    blocks = parse_blocks(config_text)
    generated: Dict[str, Block] = {}
    for block in blocks:
        if (
            block.kind != "table"
            or not block.path
            or not block.path.startswith("agents.")
        ):
            continue
        if block.path == "agents":
            continue
        name = block.path[len("agents.") :]
        if "." in name:
            continue
        generated[name] = Block(block.kind, block.path, list(block.lines))
    return generated


def merge_config_text(
    existing_text: str,
    current_agent_blocks: Dict[str, Block],
    *,
    previous_agent_names: Sequence[str],
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
) -> str:
    blocks = parse_blocks(existing_text)
    managed_headers = {
        f"agents.{name}"
        for name in set(previous_agent_names) | set(current_agent_blocks)
    }
    blocks = [
        block
        for block in blocks
        if not (block.kind == "table" and block.path in managed_headers)
    ]

    features_block = ensure_root_table(blocks, "features")
    upsert_assignment(features_block, "multi_agent", "true")

    agents_block = ensure_root_table(blocks, "agents")
    upsert_assignment(agents_block, "max_threads", str(max_threads))
    upsert_assignment(agents_block, "max_depth", str(max_depth))
    if job_max_runtime_seconds is not None:
        upsert_assignment(
            agents_block,
            "job_max_runtime_seconds",
            str(job_max_runtime_seconds),
        )

    for name in sorted(current_agent_blocks):
        block = current_agent_blocks[name]
        blocks.append(Block(block.kind, block.path, list(block.lines)))

    return render_blocks(blocks)


def collect_generated_role_files(temp_dir: Path) -> Dict[str, str]:
    generated: Dict[str, str] = {}
    for role_file in sorted((temp_dir / "agents").glob("*.toml")):
        generated[role_file.relative_to(temp_dir).as_posix()] = read_text(role_file)
    return generated


def remove_file_if_present(path: Path, *, stop_path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    path.unlink()
    parent = path.parent
    while (
        parent != stop_path
        and parent.exists()
        and parent.is_dir()
        and not any(parent.iterdir())
    ):
        parent.rmdir()
        parent = parent.parent
    return True


def sync_support_tree(source_root: Path, target_root: Path) -> None:
    if target_root.exists():
        if target_root.is_dir():
            shutil.rmtree(target_root)
        else:
            target_root.unlink()
    shutil.copytree(source_root, target_root)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Merge generated Codex agent config into an existing target directory."
    )
    parser.add_argument(
        "--source-agents",
        default="opencode/agents",
        help="Directory containing source OpenCode agent markdown files.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Target `.codex`-style directory where the merged config will be installed.",
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--max-threads",
        type=int,
        default=DEFAULT_MAX_THREADS,
        help="Value written to `agents.max_threads` in the merged config (default: 6).",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=DEFAULT_MAX_DEPTH,
        help="Value written to `agents.max_depth` in the merged config (default: 2).",
    )
    parser.add_argument(
        "--job-max-runtime-seconds",
        type=int,
        default=None,
        help="Optional value written to `agents.job_max_runtime_seconds`.",
    )
    parser.add_argument(
        "--temp-dir",
        default=None,
        help=(
            "Directory used for temporary exported Codex files before merge. "
            "Defaults to `<repo-root>/.tmp` so restricted workspace sandboxes can stay inside the repo."
        ),
    )
    parser.add_argument(
        "--agent-profile",
        default=None,
        help="Opt-in agent model profile name or JSON path forwarded to export-codex-agents.py.",
    )
    parser.add_argument(
        "--model-set",
        default=None,
        help="Runtime model-set name or JSON path forwarded to export-codex-agents.py.",
    )
    parser.add_argument(
        "--profile-dir",
        default=DEFAULT_PROFILE_DIR,
        help=f"Directory containing agent model profiles (default: {DEFAULT_PROFILE_DIR}).",
    )
    parser.add_argument(
        "--model-set-dir",
        default=DEFAULT_MODEL_SET_DIR,
        help=f"Directory containing Codex model sets (default: {DEFAULT_MODEL_SET_DIR}).",
    )
    parser.add_argument(
        "--uniform-model",
        default=None,
        help="Opt-in runtime model to apply uniformly to all generated Codex agents.",
    )
    args = parser.parse_args()

    if args.max_threads < 1:
        print("--max-threads must be >= 1", file=sys.stderr)
        return 2
    if args.max_depth < 0:
        print("--max-depth must be >= 0", file=sys.stderr)
        return 2
    if args.job_max_runtime_seconds is not None and args.job_max_runtime_seconds < 1:
        print("--job-max-runtime-seconds must be >= 1 when provided", file=sys.stderr)
        return 2

    script_path = Path(__file__).resolve()
    asset_layout = resolve_asset_layout(script_path)
    export_script = asset_layout.export_script
    source_agents_dir = Path(args.source_agents).expanduser()
    target_dir = Path(args.target_dir).expanduser()
    catalog_path = Path(args.catalog).expanduser()
    profile_dir = Path(args.profile_dir).expanduser()
    model_set_dir = Path(args.model_set_dir).expanduser()
    temp_root = resolve_temp_root(repo_root=asset_layout.asset_root, temp_dir=args.temp_dir)
    support_tree_source = asset_layout.support_tree_source
    support_tree_target = target_dir / "opencode"

    if not export_script.exists():
        print(f"Export script not found: {export_script.as_posix()}", file=sys.stderr)
        return 2
    if not source_agents_dir.exists():
        print(
            f"Source directory not found: {source_agents_dir.as_posix()}",
            file=sys.stderr,
        )
        return 2

    temp_dir: Optional[Path] = None
    try:
        temp_dir = run_export(
            export_script,
            source_agents_dir,
            catalog_path,
            strict=args.strict,
            max_threads=args.max_threads,
            max_depth=args.max_depth,
            job_max_runtime_seconds=args.job_max_runtime_seconds,
            temp_root=temp_root,
            resolve_opencode_refs_to=support_tree_target,
            agent_profile=args.agent_profile,
            model_set=args.model_set,
            profile_dir=profile_dir,
            model_set_dir=model_set_dir,
            uniform_model=args.uniform_model,
        )
        generated_config = read_text(temp_dir / "config.toml")
        generated_role_files = collect_generated_role_files(temp_dir)
        generated_agent_blocks = extract_generated_agent_blocks(generated_config)

        previous_manifest = infer_previous_managed(target_dir)
        previous_names = previous_manifest["managed_agent_names"]
        previous_files = previous_manifest["managed_agent_files"]

        current_names = sorted(generated_agent_blocks)
        current_files = sorted(generated_role_files)

        stale_names = sorted(set(previous_names) - set(current_names))
        stale_files = sorted(set(previous_files) - set(current_files))

        config_path = target_dir / "config.toml"
        existing_config_text = read_text(config_path) if config_path.exists() else ""
        merged_config_text = merge_config_text(
            existing_config_text,
            generated_agent_blocks,
            previous_agent_names=previous_names,
            max_threads=args.max_threads,
            max_depth=args.max_depth,
            job_max_runtime_seconds=args.job_max_runtime_seconds,
        )

        manifest_path = target_dir / MANIFEST_FILENAME

        if args.dry_run:
            print(f"Dry run: would merge Codex config into {target_dir.as_posix()}")
            print("- set features.multi_agent = true")
            print(f"- set agents.max_threads = {args.max_threads}")
            print(f"- set agents.max_depth = {args.max_depth}")
            if args.job_max_runtime_seconds is not None:
                print(
                    "- set agents.job_max_runtime_seconds = "
                    + str(args.job_max_runtime_seconds)
                )
            for name in stale_names:
                print(f"- remove stale managed agent entry: [agents.{name}]")
            for relative_path in stale_files:
                print(
                    "- remove stale managed agent file: "
                    + (target_dir / relative_path).as_posix()
                )
            for relative_path in current_files:
                print(
                    "- write managed agent file: "
                    + (target_dir / relative_path).as_posix()
                )
            print(
                "- sync repo-managed Codex support tree: "
                + support_tree_source.as_posix()
                + " -> "
                + support_tree_target.as_posix()
            )
            print(f"- write merged config: {config_path.as_posix()}")
            print(f"- write manifest: {manifest_path.as_posix()}")
            return 0

        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / "agents").mkdir(parents=True, exist_ok=True)

        for relative_path in stale_files:
            stale_path = target_dir / relative_path
            if remove_file_if_present(stale_path, stop_path=target_dir):
                print(f"Removed stale managed agent file: {stale_path.as_posix()}")

        for relative_path, content in generated_role_files.items():
            write_text(target_dir / relative_path, content)

        sync_support_tree(support_tree_source, support_tree_target)
        write_text(config_path, merged_config_text)
        write_manifest(
            manifest_path,
            agent_names=current_names,
            agent_files=current_files,
        )

        print(f"Merged Codex config into {target_dir.as_posix()}")
        return 0
    except (RuntimeError, ValueError, json.JSONDecodeError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        return 2
    finally:
        if temp_dir is not None:
            shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
