#!/usr/bin/env python3
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Sequence

try:  # Python 3.11+
    import tomllib
except ImportError:  # pragma: no cover - exercised only on Python 3.10.
    tomllib = None  # type: ignore[assignment]


SCRIPT_DIR = Path(__file__).resolve().parent
if SCRIPT_DIR.as_posix() not in sys.path:
    sys.path.insert(0, SCRIPT_DIR.as_posix())

from codex_mode_aliases import build_mode_summary_lines, load_mode_agents
from path_safety import is_linklike, validate_generated_shell_path


GENERATED_ROLE_MARKER = "# Generated by scripts/export-codex-agents.py"
MANIFEST_FILENAME = ".agents-pipeline-codex-manifest.json"
MANIFEST_TOOL = "agents_pipeline.install-codex-config"
MANIFEST_VERSION = 3
TABLE_RE = re.compile(r"^\s*\[([^\[\]]+)\]\s*(?:#.*)?$")
ARRAY_TABLE_RE = re.compile(r"^\s*\[\[([^\[\]]+)\]\]\s*(?:#.*)?$")
BARE_KEY_RE = re.compile(r"[A-Za-z0-9_-]+")
MANAGED_AGENT_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
MANAGED_AGENT_FILE_RE = re.compile(
    r"^agents/([a-z0-9][a-z0-9-]*)\.toml$"
)
DEFAULT_MAX_THREADS = 6
DEFAULT_MAX_DEPTH = 2
DEFAULT_PROFILE_DIR = "tools/agent-profiles"
DEFAULT_MODEL_SET_DIR = "runtimes/codex/model-sets"
SUPPORT_TREE_DIRS = ("agents", "protocols", "runtimes", "scripts", "skills", "tools")
SUPPORT_TREE_FILES = ("AGENTS.md", "VERSION", "modes.json")
SUPPORT_TREE_DIRNAME = "agents-pipeline"
SUPPORT_SYNC_SCRIPT = SCRIPT_DIR / "sync-runtime-support.py"
LEGACY_SUPPORT_TREE_DIRNAME = "opencode"
LEGACY_SUPPORT_TREE_MARKERS = (
    "agents/orchestrator-pipeline.md",
    "commands/run-pipeline.md",
    "protocols/PIPELINE_PROTOCOL.md",
)
GLOBAL_AGENTS_FILENAME = "AGENTS.md"
GLOBAL_AGENTS_OVERRIDE_FILENAME = "AGENTS.override.md"
GLOBAL_AGENTS_HEADING = "# Codex Global Agent Notes"
WORKSPACE_AGENTS_HEADING = "# Workspace Agent Notes"
WORKSPACE_AGENTS_MANAGED_START = "<!-- BEGIN agents-pipeline-codex-managed -->"
WORKSPACE_AGENTS_MANAGED_END = "<!-- END agents-pipeline-codex-managed -->"


@dataclass
class Block:
    kind: str
    path: Optional[str]
    lines: List[str]


@dataclass(frozen=True)
class AssetLayout:
    name: str
    asset_root: Path
    support_tree_source: Path
    export_script: Path


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def validate_managed_leaf(path: Path, label: str) -> None:
    if is_linklike(path):
        raise ValueError(
            f"{label} must not be a symbolic link or junction: {path.as_posix()}"
        )
    if path.exists() and not path.is_file():
        raise ValueError(f"{label} must be a regular file: {path.as_posix()}")


def write_text_atomic(path: Path, content: str) -> None:
    validate_managed_leaf(path, "Managed output")
    path.parent.mkdir(parents=True, exist_ok=True)
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    temp_path: Optional[Path] = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            dir=path.parent,
            prefix=f".{path.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temp_path = Path(handle.name)
            handle.write(content)
        os.chmod(temp_path, mode)
        os.replace(temp_path, path)
        temp_path = None
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)


def has_support_tree(root: Path) -> bool:
    return all((root / name).is_dir() for name in SUPPORT_TREE_DIRS) and all(
        (root / name).is_file() for name in SUPPORT_TREE_FILES
    )


def resolve_workspace_agents_path(
    target_dir: Path, workspace_root: Optional[Path]
) -> Optional[Path]:
    if workspace_root is None:
        return None

    resolved_workspace = workspace_root.expanduser().resolve()
    resolved_target = target_dir.expanduser().resolve()
    if resolved_target != (resolved_workspace / ".codex").resolve():
        return None
    return resolved_workspace / "AGENTS.md"


def resolve_global_agents_path(target_dir: Path) -> Path:
    override_path = target_dir / GLOBAL_AGENTS_OVERRIDE_FILENAME
    validate_managed_leaf(override_path, "Global AGENTS override")
    if override_path.is_file() and read_text(override_path).strip():
        return override_path
    return target_dir / GLOBAL_AGENTS_FILENAME


def resolve_catalog_path(catalog_arg: str, *, asset_root: Path) -> Path:
    catalog_path = Path(catalog_arg).expanduser()
    if catalog_path.is_absolute():
        return catalog_path
    if catalog_arg == "AGENTS.md":
        return asset_root / catalog_path
    return catalog_path


def build_agents_alias_map_lines(modes_path: Path) -> List[str]:
    mode_agents = load_mode_agents(modes_path)
    lines = ["Alias map:"]
    for alias, agent_name in mode_agents.items():
        lines.append(f"- `{alias}` / `run-{alias}` -> `{agent_name}`")
    return lines


def build_global_agents_managed_block(modes_path: Path) -> str:
    lines = [
        WORKSPACE_AGENTS_MANAGED_START,
        "## Codex global mode aliases",
        "",
        *build_mode_summary_lines(),
        "",
        *build_agents_alias_map_lines(modes_path),
        "",
        "Higher-priority system, developer, tool, and runtime instructions override this note.",
        "Project/workspace `AGENTS.md` files may further refine behavior for a specific repo.",
        WORKSPACE_AGENTS_MANAGED_END,
    ]
    return "\n".join(lines) + "\n"


def build_workspace_agents_managed_block(modes_path: Path) -> str:
    lines = [
        WORKSPACE_AGENTS_MANAGED_START,
        "## Codex mode aliases",
        "",
        *build_mode_summary_lines(),
        "",
        *build_agents_alias_map_lines(modes_path),
        "",
        "Higher-priority system, developer, tool, and runtime instructions override this note.",
        WORKSPACE_AGENTS_MANAGED_END,
    ]
    return "\n".join(lines) + "\n"


def _markdown_marker_indices(lines: Sequence[str], marker: str) -> List[int]:
    indexes: List[int] = []
    fence_char: Optional[str] = None
    fence_length = 0
    for index, line in enumerate(lines):
        leading_spaces = len(line) - len(line.lstrip(" "))
        candidate = line[leading_spaces:] if leading_spaces <= 3 else ""
        if fence_char is not None:
            run = len(candidate) - len(candidate.lstrip(fence_char))
            if run >= fence_length and not candidate[run:].strip():
                fence_char = None
                fence_length = 0
            continue
        if candidate.startswith("```") or candidate.startswith("~~~"):
            char = candidate[0]
            run = len(candidate) - len(candidate.lstrip(char))
            fence_char = char
            fence_length = run
            continue
        if leading_spaces >= 4 or line.startswith("\t"):
            continue
        if line.strip() == marker:
            indexes.append(index)
    return indexes


def merge_agents_text(existing_text: str, managed_block: str, *, heading: str) -> str:
    normalized = existing_text.replace("\r\n", "\n")
    start_token = WORKSPACE_AGENTS_MANAGED_START
    end_token = WORKSPACE_AGENTS_MANAGED_END
    managed = managed_block.rstrip()

    lines = normalized.split("\n")
    start_indices = _markdown_marker_indices(lines, start_token)
    end_indices = _markdown_marker_indices(lines, end_token)
    if len(start_indices) != len(end_indices) or len(start_indices) > 1:
        raise ValueError("Managed AGENTS block has malformed or duplicate markers.")
    start_idx = start_indices[0] if start_indices else None
    end_idx = end_indices[0] if end_indices else None
    if start_idx is not None and (end_idx is None or end_idx <= start_idx):
        raise ValueError("Managed AGENTS block markers are out of order.")

    if start_idx is not None and end_idx is not None and start_idx < end_idx:
        before = "\n".join(lines[:start_idx]).rstrip()
        after = "\n".join(lines[end_idx + 1 :]).strip()
        parts = [part for part in (before, managed, after) if part]
        return "\n\n".join(parts).rstrip() + "\n"

    cleaned = normalized.strip()
    if not cleaned:
        return f"{heading}\n\n{managed}\n"
    return cleaned.rstrip() + "\n\n" + managed + "\n"


def merge_global_agents_text(existing_text: str, managed_block: str) -> str:
    return merge_agents_text(
        existing_text,
        managed_block,
        heading=GLOBAL_AGENTS_HEADING,
    )


def merge_workspace_agents_text(existing_text: str, managed_block: str) -> str:
    return merge_agents_text(
        existing_text,
        managed_block,
        heading=WORKSPACE_AGENTS_HEADING,
    )


def resolve_asset_layout(script_path: Path) -> AssetLayout:
    asset_root = script_path.parent.parent
    export_script = asset_root / "scripts" / "export-codex-agents.py"
    return AssetLayout(
        name="neutral",
        asset_root=asset_root,
        support_tree_source=asset_root,
        export_script=export_script,
    )


def _scan_multiline_string_state(line: str, state: Optional[str]) -> Optional[str]:
    """Track TOML multiline strings so string contents are never parsed as syntax."""

    index = 0
    while index < len(line):
        if state is not None:
            delimiter = state
            found = line.find(delimiter, index)
            if found < 0:
                return state
            if delimiter == '"""':
                backslashes = 0
                cursor = found - 1
                while cursor >= 0 and line[cursor] == "\\":
                    backslashes += 1
                    cursor -= 1
                if backslashes % 2:
                    index = found + 1
                    continue
            state = None
            index = found + 3
            continue

        if line.startswith('"""', index):
            state = '"""'
            index += 3
            continue
        if line.startswith("'''", index):
            state = "'''"
            index += 3
            continue
        char = line[index]
        if char == "#":
            break
        if char == '"':
            index += 1
            while index < len(line):
                if line[index] == '"':
                    backslashes = 0
                    cursor = index - 1
                    while cursor >= 0 and line[cursor] == "\\":
                        backslashes += 1
                        cursor -= 1
                    if backslashes % 2 == 0:
                        index += 1
                        break
                index += 1
            continue
        if char == "'":
            closing = line.find("'", index + 1)
            index = len(line) if closing < 0 else closing + 1
            continue
        index += 1
    return state


def _syntax_line_flags(lines: Sequence[str]) -> List[bool]:
    state: Optional[str] = None
    flags: List[bool] = []
    for line in lines:
        flags.append(state is None)
        state = _scan_multiline_string_state(line, state)
    return flags


def _canonical_table_path(raw: str) -> str:
    """Canonicalize simple TOML dotted keys, including quoted agent names."""

    parts: List[str] = []
    index = 0
    while True:
        while index < len(raw) and raw[index].isspace():
            index += 1
        if index >= len(raw):
            return raw.strip()
        if raw[index] == '"':
            start = index
            index += 1
            escaped = False
            while index < len(raw):
                char = raw[index]
                if char == '"' and not escaped:
                    index += 1
                    break
                if char == "\\" and not escaped:
                    escaped = True
                else:
                    escaped = False
                index += 1
            else:
                return raw.strip()
            try:
                part = json.loads(raw[start:index])
            except (TypeError, ValueError, json.JSONDecodeError):
                return raw.strip()
        elif raw[index] == "'":
            closing = raw.find("'", index + 1)
            if closing < 0:
                return raw.strip()
            part = raw[index + 1 : closing]
            index = closing + 1
        else:
            match = BARE_KEY_RE.match(raw, index)
            if match is None:
                return raw.strip()
            part = match.group(0)
            index = match.end()
        if not isinstance(part, str):
            return raw.strip()
        parts.append(part)
        while index < len(raw) and raw[index].isspace():
            index += 1
        if index == len(raw):
            return ".".join(parts)
        if raw[index] != ".":
            return raw.strip()
        index += 1


def parse_blocks(text: str) -> List[Block]:
    blocks: List[Block] = []
    current_kind = "preamble"
    current_path: Optional[str] = None
    current_lines: List[str] = []

    multiline_state: Optional[str] = None
    for line in text.splitlines():
        syntax_line = multiline_state is None
        array_match = ARRAY_TABLE_RE.match(line) if syntax_line else None
        table_match = TABLE_RE.match(line) if syntax_line else None
        multiline_state = _scan_multiline_string_state(line, multiline_state)
        if array_match or table_match:
            if current_lines or current_kind != "preamble" or not blocks:
                blocks.append(Block(current_kind, current_path, current_lines))
            current_kind = "array" if array_match else "table"
            current_path = _canonical_table_path(
                (array_match or table_match).group(1).strip()
            )
            current_lines = [line]
            continue
        current_lines.append(line)

    if current_lines or current_kind != "preamble" or not blocks:
        blocks.append(Block(current_kind, current_path, current_lines))
    return blocks


def render_blocks(blocks: Sequence[Block]) -> str:
    rendered: List[str] = []
    for block in blocks:
        lines = list(block.lines)
        while lines and not lines[-1].strip():
            lines.pop()
        if not lines:
            continue
        rendered.append("\n".join(lines))
    if not rendered:
        return ""
    return "\n\n".join(rendered).rstrip() + "\n"


def validate_toml_text(text: str, label: str) -> None:
    if tomllib is None:
        raise RuntimeError("Codex installation requires Python 3.11 or newer.")
    if not text.strip():
        return
    try:
        tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"{label} is not valid TOML: {exc}") from exc


def find_block_index(blocks: Sequence[Block], *, kind: str, path: str) -> Optional[int]:
    for idx, block in enumerate(blocks):
        if block.kind == kind and block.path == path:
            return idx
    return None


def insert_index_before_prefix(blocks: Sequence[Block], prefix: str) -> Optional[int]:
    for idx, block in enumerate(blocks):
        if (
            block.kind in {"table", "array"}
            and block.path
            and block.path.startswith(prefix)
        ):
            return idx
    return None


def ensure_root_table(blocks: List[Block], path: str) -> Block:
    existing_idx = find_block_index(blocks, kind="table", path=path)
    if existing_idx is not None:
        return blocks[existing_idx]

    child_idx = insert_index_before_prefix(blocks, path + ".")
    if child_idx is not None:
        insert_idx = child_idx
    elif blocks and blocks[0].kind == "preamble":
        insert_idx = 1
    else:
        insert_idx = len(blocks)

    block = Block("table", path, [f"[{path}]"])
    blocks.insert(insert_idx, block)
    return block


def upsert_assignment(block: Block, key: str, value: str) -> None:
    assign_re = re.compile(rf"^\s*{re.escape(key)}\s*=")
    new_line = f"{key} = {value}"
    output = [block.lines[0]]
    replaced = False

    syntax_flags = _syntax_line_flags(block.lines)
    for line, syntax_line in zip(block.lines[1:], syntax_flags[1:]):
        if syntax_line and assign_re.match(line) and not line.lstrip().startswith("#"):
            if not replaced:
                output.append(new_line)
                replaced = True
            continue
        output.append(line)

    if not replaced:
        while len(output) > 1 and not output[-1].strip():
            output.pop()
        output.append(new_line)

    block.lines = output


def remove_assignment_if_value(block: Block, key: str, value: str) -> bool:
    assign_re = re.compile(rf"^\s*{re.escape(key)}\s*=\s*{re.escape(value)}\s*(?:#.*)?$")
    output = [block.lines[0]]
    removed = False

    syntax_flags = _syntax_line_flags(block.lines)
    for line, syntax_line in zip(block.lines[1:], syntax_flags[1:]):
        if syntax_line and assign_re.match(line) and not line.lstrip().startswith("#"):
            removed = True
            continue
        output.append(line)

    block.lines = output
    return removed


def _dotted_root_pattern(root: str, key: Optional[str] = None) -> re.Pattern[str]:
    root_token = rf'(?:{re.escape(root)}|"{re.escape(root)}"|\'{re.escape(root)}\')'
    if key is None:
        return re.compile(rf"^\s*{root_token}\s*\.")
    key_token = rf'(?:{re.escape(key)}|"{re.escape(key)}"|\'{re.escape(key)}\')'
    return re.compile(rf"^\s*{root_token}\s*\.\s*{key_token}\s*=")


def has_dotted_root_assignment(block: Block, root: str) -> bool:
    pattern = _dotted_root_pattern(root)
    return any(
        syntax_line and pattern.match(line) and not line.lstrip().startswith("#")
        for line, syntax_line in zip(block.lines, _syntax_line_flags(block.lines))
    )


def upsert_dotted_root_assignment(
    block: Block, root: str, key: str, value: str
) -> None:
    pattern = _dotted_root_pattern(root, key)
    new_line = f"{root}.{key} = {value}"
    output: List[str] = []
    replaced = False
    for line, syntax_line in zip(block.lines, _syntax_line_flags(block.lines)):
        if (
            syntax_line
            and pattern.match(line)
            and not line.lstrip().startswith("#")
        ):
            if not replaced:
                output.append(new_line)
                replaced = True
            continue
        output.append(line)
    if not replaced:
        while output and not output[-1].strip():
            output.pop()
        output.append(new_line)
    block.lines = output


def remove_dotted_root_assignment_if_value(
    block: Block, root: str, key: str, value: str
) -> bool:
    prefix = _dotted_root_pattern(root, key).pattern.removesuffix("=")
    pattern = re.compile(rf"{prefix}=\s*{re.escape(value)}\s*(?:#.*)?$")
    output: List[str] = []
    removed = False
    for line, syntax_line in zip(block.lines, _syntax_line_flags(block.lines)):
        if syntax_line and pattern.match(line) and not line.lstrip().startswith("#"):
            removed = True
            continue
        output.append(line)
    block.lines = output
    return removed


def is_workspace_profile_target(
    target_dir: Path, global_agents_target: Optional[Path]
) -> bool:
    """Whether the profile wrapper is writing a project-local Codex config."""
    return (
        global_agents_target is not None
        and target_dir.expanduser().resolve()
        != global_agents_target.expanduser().resolve()
    )


def parse_manifest(path: Path) -> Optional[Dict[str, object]]:
    validate_managed_leaf(path, "Codex installer manifest")
    if not path.exists():
        return None
    data = json.loads(read_text(path))
    if not isinstance(data, dict):
        raise ValueError(f"{path.as_posix()}: invalid manifest shape")

    raw_version = data.get("version", 0)
    if type(raw_version) is not int or not 0 <= raw_version <= MANIFEST_VERSION:
        raise ValueError(f"{path.as_posix()}: unsupported manifest version")
    raw_tool = data.get("tool")
    if raw_tool is not None and raw_tool != MANIFEST_TOOL:
        raise ValueError(f"{path.as_posix()}: unexpected manifest tool identity")
    if raw_version >= 2 and raw_tool != MANIFEST_TOOL:
        raise ValueError(f"{path.as_posix()}: missing manifest tool identity")
    if raw_version >= 2:
        declared_target = data.get("target_dir")
        if (
            not isinstance(declared_target, str)
            or Path(declared_target).expanduser().resolve() != path.parent.resolve()
        ):
            raise ValueError(f"{path.as_posix()}: manifest target does not match its location")
    if (
        raw_version == MANIFEST_VERSION
        and data.get("managed_support_root") != SUPPORT_TREE_DIRNAME
    ):
        raise ValueError(f"{path.as_posix()}: invalid managed support root")

    names = data.get("managed_agent_names")
    files = data.get("managed_agent_files")
    if not isinstance(names, list) or not isinstance(files, list):
        raise ValueError(f"{path.as_posix()}: invalid manifest shape")
    if not all(
        isinstance(name, str) and MANAGED_AGENT_NAME_RE.fullmatch(name)
        for name in names
    ):
        raise ValueError(f"{path.as_posix()}: invalid managed agent name")
    if len(set(names)) != len(names):
        raise ValueError(f"{path.as_posix()}: duplicate managed agent name")

    file_names: List[str] = []
    for file_path in files:
        if not isinstance(file_path, str):
            raise ValueError(f"{path.as_posix()}: invalid managed agent file")
        match = MANAGED_AGENT_FILE_RE.fullmatch(file_path)
        if match is None:
            raise ValueError(
                f"{path.as_posix()}: managed agent files must match "
                "agents/<name>.toml"
            )
        file_names.append(match.group(1))
    if len(set(files)) != len(files):
        raise ValueError(f"{path.as_posix()}: duplicate managed agent file")
    if set(names) != set(file_names):
        raise ValueError(
            f"{path.as_posix()}: managed agent names and files do not match"
        )

    return {
        "manifest_version": raw_version,
        "managed_agent_names": list(names),
        "managed_agent_files": list(files),
    }


def write_manifest(
    path: Path,
    *,
    agent_names: Sequence[str],
    agent_files: Sequence[str],
    profile: Optional[str],
    model_set: Optional[str],
    uniform_model: Optional[str],
    source_agents_dir: Path,
    target_dir: Path,
) -> None:
    mode = "default"
    if uniform_model:
        mode = "uniform"
    elif profile:
        mode = "profile"
    payload = {
        "tool": MANIFEST_TOOL,
        "version": MANIFEST_VERSION,
        "profile": profile or ("uniform" if uniform_model else None),
        "mode": mode,
        "model_set": model_set,
        "uniform_model": uniform_model,
        "target_dir": target_dir.resolve().as_posix(),
        "managed_support_root": SUPPORT_TREE_DIRNAME,
        "managed_agent_names": sorted(agent_names),
        "managed_agent_files": sorted(agent_files),
    }
    write_text_atomic(path, json.dumps(payload, indent=2, sort_keys=True) + "\n")


def is_generated_role_file(path: Path) -> bool:
    if is_linklike(path) or not path.exists() or not path.is_file():
        return False
    try:
        return GENERATED_ROLE_MARKER in read_text(path).splitlines()[:3]
    except OSError:
        return False


def validate_generated_role_ownership(path: Path) -> None:
    if not path.exists():
        return
    if not is_generated_role_file(path):
        raise ValueError(
            "Refusing to replace or remove a Codex role file without the generated "
            f"ownership marker: {path}"
        )


def infer_previous_managed(target_dir: Path) -> Dict[str, object]:
    manifest_path = target_dir / MANIFEST_FILENAME
    manifest = parse_manifest(manifest_path)
    if manifest is not None:
        version = manifest.get("manifest_version")
        if isinstance(version, int) and version < 2:
            files = [
                relative
                for relative in manifest["managed_agent_files"]
                if is_generated_role_file(target_dir / str(relative))
            ]
            return {
                "manifest_version": version,
                "managed_agent_names": [Path(relative).stem for relative in files],
                "managed_agent_files": files,
            }
        return manifest

    names: List[str] = []
    files: List[str] = []
    agents_dir = target_dir / "agents"
    if agents_dir.exists():
        for role_file in sorted(agents_dir.glob("*.toml")):
            if not is_generated_role_file(role_file):
                continue
            names.append(role_file.stem)
            files.append(role_file.relative_to(target_dir).as_posix())
    return {
        "manifest_version": None,
        "managed_agent_names": names,
        "managed_agent_files": files,
    }


def resolve_managed_agent_path(target_dir: Path, relative_path: str) -> Path:
    if MANAGED_AGENT_FILE_RE.fullmatch(relative_path) is None:
        raise ValueError(
            f"Unsafe managed agent path: {relative_path!r}; expected agents/<name>.toml"
        )
    resolved_target = target_dir.expanduser().resolve()
    lexical_path = resolved_target / relative_path
    expected_parent = resolved_target / "agents"
    if lexical_path.parent.resolve() != expected_parent:
        raise ValueError(
            f"Unsafe managed agent path escapes target directory: {relative_path!r}"
        )
    if is_linklike(lexical_path):
        raise ValueError(
            f"Managed agent path must not be a symbolic link or junction: {relative_path!r}"
        )
    if lexical_path.exists() and not lexical_path.is_file():
        raise ValueError(f"Managed agent path is not a file: {relative_path!r}")
    return lexical_path


def resolve_managed_tree_target(target_dir: Path, dirname: str) -> Path:
    lexical = (target_dir / dirname).expanduser()
    if is_linklike(lexical):
        raise ValueError(
            f"Managed support path must not be a symbolic link or junction: {dirname!r}"
        )
    resolved_target = target_dir.expanduser().resolve()
    expected = resolved_target / dirname
    resolved = lexical.resolve()
    if resolved != expected:
        raise ValueError(
            f"Unsafe managed support path escapes target directory: {dirname!r}"
        )
    return resolved


def is_legacy_support_tree_owned(path: Path) -> bool:
    return (
        path.is_dir()
        and not is_linklike(path)
        and all((path / marker).is_file() for marker in LEGACY_SUPPORT_TREE_MARKERS)
    )


def should_remove_legacy_support(
    previous_manifest: Dict[str, object],
    *,
    manifest_exists: bool,
    legacy_support_path: Path,
) -> bool:
    version = previous_manifest.get("manifest_version")
    return (
        manifest_exists
        and isinstance(version, int)
        and version < MANIFEST_VERSION
        and is_legacy_support_tree_owned(legacy_support_path)
    )


def build_export_command(
    export_script: Path,
    source_agents_dir: Path,
    modes_path: Path,
    catalog_path: Path,
    target_dir: Path,
    *,
    strict: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
    resolve_support_refs_to: Optional[Path],
    agent_profile: Optional[str] = None,
    model_set: Optional[str] = None,
    profile_dir: Optional[Path] = None,
    model_set_dir: Optional[Path] = None,
    uniform_model: Optional[str] = None,
) -> List[str]:
    command = [
        sys.executable,
        export_script.as_posix(),
        "--source-agents",
        source_agents_dir.as_posix(),
        "--modes-file",
        modes_path.as_posix(),
        "--target-dir",
        target_dir.as_posix(),
        "--catalog",
        catalog_path.as_posix(),
        "--max-threads",
        str(max_threads),
        "--max-depth",
        str(max_depth),
    ]
    if strict:
        command.append("--strict")
    if job_max_runtime_seconds is not None:
        command.extend(["--job-max-runtime-seconds", str(job_max_runtime_seconds)])
    if resolve_support_refs_to is not None:
        command.extend(
            ["--resolve-support-refs-to", resolve_support_refs_to.as_posix()]
        )
    if agent_profile is not None:
        command.extend(["--agent-profile", agent_profile])
    if model_set is not None:
        command.extend(["--model-set", model_set])
    if profile_dir is not None:
        command.extend(["--profile-dir", profile_dir.as_posix()])
    if model_set_dir is not None:
        command.extend(["--model-set-dir", model_set_dir.as_posix()])
    if uniform_model is not None:
        command.extend(["--uniform-model", uniform_model])
    return command


def resolve_temp_root(*, repo_root: Path, temp_dir: Optional[str]) -> Path:
    if temp_dir:
        return Path(temp_dir).expanduser()
    return repo_root / ".tmp"


def run_export(
    export_script: Path,
    source_agents_dir: Path,
    modes_path: Path,
    catalog_path: Path,
    *,
    strict: bool,
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
    temp_root: Path,
    resolve_support_refs_to: Optional[Path],
    agent_profile: Optional[str] = None,
    model_set: Optional[str] = None,
    profile_dir: Optional[Path] = None,
    model_set_dir: Optional[Path] = None,
    uniform_model: Optional[str] = None,
) -> Path:
    try:
        temp_root.mkdir(parents=True, exist_ok=True)
        temp_dir = Path(
            tempfile.mkdtemp(prefix="agents-pipeline-codex-", dir=temp_root)
        )
    except OSError as exc:
        raise RuntimeError(
            f"Unable to create temp dir under {temp_root.as_posix()}: {exc}"
        ) from exc
    command = build_export_command(
        export_script,
        source_agents_dir,
        modes_path,
        catalog_path,
        temp_dir,
        strict=strict,
        max_threads=max_threads,
        max_depth=max_depth,
        job_max_runtime_seconds=job_max_runtime_seconds,
        resolve_support_refs_to=resolve_support_refs_to,
        agent_profile=agent_profile,
        model_set=model_set,
        profile_dir=profile_dir,
        model_set_dir=model_set_dir,
        uniform_model=uniform_model,
    )
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        if result.stdout:
            sys.stderr.write(result.stdout)
        if result.stderr:
            sys.stderr.write(result.stderr)
        shutil.rmtree(temp_dir, ignore_errors=True)
        raise RuntimeError(
            f"Codex role export failed with exit code {result.returncode}."
        )
    return temp_dir


def extract_generated_agent_blocks(config_text: str) -> Dict[str, Block]:
    validate_toml_text(config_text, "Generated Codex config")
    blocks = parse_blocks(config_text)
    generated: Dict[str, Block] = {}
    for block in blocks:
        if (
            block.kind != "table"
            or not block.path
            or not block.path.startswith("agents.")
        ):
            continue
        if block.path == "agents":
            continue
        name = block.path[len("agents.") :]
        if "." in name:
            continue
        generated[name] = Block(block.kind, block.path, list(block.lines))
    return generated


def merge_config_text(
    existing_text: str,
    current_agent_blocks: Dict[str, Block],
    *,
    previous_agent_names: Sequence[str],
    max_threads: int,
    max_depth: int,
    job_max_runtime_seconds: Optional[int],
    manage_agent_limits: bool,
    remove_legacy_agent_limits: bool,
) -> str:
    validate_toml_text(existing_text, "Existing Codex config")
    blocks = parse_blocks(existing_text)
    managed_headers = {
        f"agents.{name}"
        for name in set(previous_agent_names) | set(current_agent_blocks)
    }
    blocks = [
        block
        for block in blocks
        if not (block.kind == "table" and block.path in managed_headers)
    ]
    if not blocks or blocks[0].kind != "preamble":
        blocks.insert(0, Block("preamble", None, []))
    preamble = blocks[0]

    features_idx = find_block_index(blocks, kind="table", path="features")
    if features_idx is None and has_dotted_root_assignment(preamble, "features"):
        upsert_dotted_root_assignment(preamble, "features", "multi_agent", "true")
    else:
        features_block = ensure_root_table(blocks, "features")
        upsert_assignment(features_block, "multi_agent", "true")

    agents_idx = find_block_index(blocks, kind="table", path="agents")
    use_dotted_agents = (
        agents_idx is None and has_dotted_root_assignment(preamble, "agents")
    )
    agents_block = None if use_dotted_agents else ensure_root_table(blocks, "agents")
    if manage_agent_limits:
        if use_dotted_agents:
            upsert_dotted_root_assignment(
                preamble, "agents", "max_threads", str(max_threads)
            )
            upsert_dotted_root_assignment(
                preamble, "agents", "max_depth", str(max_depth)
            )
        else:
            assert agents_block is not None
            upsert_assignment(agents_block, "max_threads", str(max_threads))
            upsert_assignment(agents_block, "max_depth", str(max_depth))
    elif remove_legacy_agent_limits:
        if use_dotted_agents:
            remove_dotted_root_assignment_if_value(
                preamble, "agents", "max_threads", str(DEFAULT_MAX_THREADS)
            )
            remove_dotted_root_assignment_if_value(
                preamble, "agents", "max_depth", str(DEFAULT_MAX_DEPTH)
            )
        else:
            assert agents_block is not None
            remove_assignment_if_value(
                agents_block, "max_threads", str(DEFAULT_MAX_THREADS)
            )
            remove_assignment_if_value(
                agents_block, "max_depth", str(DEFAULT_MAX_DEPTH)
            )
    if job_max_runtime_seconds is not None:
        if use_dotted_agents:
            upsert_dotted_root_assignment(
                preamble,
                "agents",
                "job_max_runtime_seconds",
                str(job_max_runtime_seconds),
            )
        else:
            assert agents_block is not None
            upsert_assignment(
                agents_block,
                "job_max_runtime_seconds",
                str(job_max_runtime_seconds),
            )

    for name in sorted(current_agent_blocks):
        block = current_agent_blocks[name]
        blocks.append(Block(block.kind, block.path, list(block.lines)))

    merged = render_blocks(blocks)
    validate_toml_text(merged, "Merged Codex config")
    return merged


def collect_generated_role_files(temp_dir: Path) -> Dict[str, str]:
    generated: Dict[str, str] = {}
    for role_file in sorted((temp_dir / "agents").glob("*.toml")):
        generated[role_file.relative_to(temp_dir).as_posix()] = read_text(role_file)
    return generated


def remove_file_if_present(path: Path, *, stop_path: Path) -> bool:
    if not path.exists() or not path.is_file():
        return False
    path.unlink()
    parent = path.parent
    while (
        parent != stop_path
        and parent.exists()
        and parent.is_dir()
        and not any(parent.iterdir())
    ):
        parent.rmdir()
        parent = parent.parent
    return True


def sync_support_tree(
    source_root: Path, target_root: Path, *, dry_run: bool = False
) -> None:
    if not SUPPORT_SYNC_SCRIPT.is_file():
        raise RuntimeError(
            f"Neutral support sync helper not found: {SUPPORT_SYNC_SCRIPT.as_posix()}"
        )
    command = [
        sys.executable,
        SUPPORT_SYNC_SCRIPT.as_posix(),
        "--source-root",
        source_root.as_posix(),
        "--target-root",
        target_root.as_posix(),
    ]
    if dry_run:
        command.append("--dry-run")
    result = subprocess.run(
        command,
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise RuntimeError(
            "Neutral support tree synchronization failed"
            + (f": {detail}" if detail else "")
        )


def seed_builtin_project_profile_caches(asset_root: Path, global_target: Path) -> None:
    helper = asset_root / "scripts" / "codex-project-profile.py"
    profile_dir = asset_root / DEFAULT_PROFILE_DIR
    model_set_dir = asset_root / DEFAULT_MODEL_SET_DIR
    if not helper.is_file():
        raise RuntimeError(f"Codex project profile helper not found: {helper.as_posix()}")
    profile_names = sorted(path.stem for path in profile_dir.glob("*.json"))
    model_set_names = sorted(path.stem for path in model_set_dir.glob("*.json"))
    if not profile_names or not model_set_names:
        raise RuntimeError("Built-in Codex profiles or model sets are missing.")
    for profile_name in profile_names:
        for model_set_name in model_set_names:
            result = subprocess.run(
                [
                    sys.executable,
                    helper.as_posix(),
                    "cache",
                    "--global-target",
                    global_target.as_posix(),
                    "--asset-root",
                    asset_root.as_posix(),
                    "--profile",
                    profile_name,
                    "--model-set",
                    model_set_name,
                ],
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode != 0:
                detail = result.stderr.strip() or result.stdout.strip()
                raise RuntimeError(
                    "Unable to seed Codex project profile cache "
                    f"{profile_name}/{model_set_name}: {detail}"
                )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Merge generated Codex agent config into an existing target directory."
    )
    parser.add_argument(
        "--source-agents",
        default="agents",
        help="Directory containing canonical source agent markdown files.",
    )
    parser.add_argument(
        "--modes-file",
        default=None,
        help="Neutral modes.json manifest. Defaults to the bundled asset root.",
    )
    parser.add_argument(
        "--target-dir",
        required=True,
        help="Target `.codex`-style directory where the merged config will be installed.",
    )
    parser.add_argument(
        "--workspace-root",
        default=None,
        help=(
            "Optional workspace root. When target-dir resolves to `<workspace>/.codex`, "
            "merge a managed block into `<workspace>/AGENTS.md` instead of managing "
            "the target-dir global AGENTS file."
        ),
    )
    parser.add_argument(
        "--global-agents-target",
        default=None,
        help=(
            "Optional Codex home directory whose AGENTS file receives the managed "
            "global block. When provided, this overrides the default target-dir "
            "global AGENTS merge and disables workspace AGENTS merging."
        ),
    )
    parser.add_argument(
        "--catalog",
        default="AGENTS.md",
        help="Optional AGENTS catalog used for strict all-agent coverage checks.",
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print actions without writing files."
    )
    parser.add_argument(
        "--strict", action="store_true", help="Fail on unresolved refs or unknown keys."
    )
    parser.add_argument(
        "--max-threads",
        type=int,
        default=DEFAULT_MAX_THREADS,
        help="Value written to `agents.max_threads` in the merged config (default: 6).",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=DEFAULT_MAX_DEPTH,
        help="Value written to `agents.max_depth` in the merged config (default: 2).",
    )
    parser.add_argument(
        "--job-max-runtime-seconds",
        type=int,
        default=None,
        help="Optional value written to `agents.job_max_runtime_seconds`.",
    )
    parser.add_argument(
        "--temp-dir",
        default=None,
        help=(
            "Directory used for temporary exported Codex files before merge. "
            "Defaults to `<repo-root>/.tmp` so restricted workspace sandboxes can stay inside the repo."
        ),
    )
    parser.add_argument(
        "--agent-profile",
        default=None,
        help="Workspace-only agent model profile forwarded to export-codex-agents.py.",
    )
    parser.add_argument(
        "--model-set",
        default=None,
        help="Workspace-only runtime model-set forwarded to export-codex-agents.py.",
    )
    parser.add_argument(
        "--profile-dir",
        default=DEFAULT_PROFILE_DIR,
        help=f"Directory containing agent model profiles (default: {DEFAULT_PROFILE_DIR}).",
    )
    parser.add_argument(
        "--model-set-dir",
        default=DEFAULT_MODEL_SET_DIR,
        help=f"Directory containing Codex model sets (default: {DEFAULT_MODEL_SET_DIR}).",
    )
    parser.add_argument(
        "--uniform-model",
        default=None,
        help="Workspace-only runtime model applied uniformly to generated Codex agents.",
    )
    args = parser.parse_args()

    if args.max_threads < 1:
        print("--max-threads must be >= 1", file=sys.stderr)
        return 2
    if args.max_depth < 0:
        print("--max-depth must be >= 0", file=sys.stderr)
        return 2
    if args.job_max_runtime_seconds is not None and args.job_max_runtime_seconds < 1:
        print("--job-max-runtime-seconds must be >= 1 when provided", file=sys.stderr)
        return 2

    script_path = Path(__file__).resolve()
    asset_layout = resolve_asset_layout(script_path)
    export_script = asset_layout.export_script
    source_agents_dir = (
        asset_layout.asset_root / "agents"
        if args.source_agents == "agents"
        else Path(args.source_agents).expanduser()
    )
    modes_path = (
        Path(args.modes_file).expanduser()
        if args.modes_file
        else asset_layout.asset_root / "modes.json"
    )
    try:
        target_dir = Path(
            validate_generated_shell_path(args.target_dir, "Target path")
        )
        workspace_root = (
            Path(validate_generated_shell_path(args.workspace_root, "Workspace root"))
            if args.workspace_root
            else None
        )
        global_agents_target = (
            Path(
                validate_generated_shell_path(
                    args.global_agents_target, "Global AGENTS target"
                )
            )
            if args.global_agents_target
            else None
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    if is_linklike(target_dir):
        print(
            f"Target path must not be a symbolic link or junction: {target_dir}",
            file=sys.stderr,
        )
        return 2
    if target_dir.exists() and not target_dir.is_dir():
        print(f"Target path is not a directory: {target_dir}", file=sys.stderr)
        return 2
    workspace_profile_target = is_workspace_profile_target(
        target_dir, global_agents_target
    )
    model_profile_requested = any(
        value is not None
        for value in (args.agent_profile, args.model_set, args.uniform_model)
    )
    canonical_workspace_target = (
        workspace_root is not None
        and target_dir.expanduser().resolve()
        == (workspace_root.expanduser().resolve() / ".codex").resolve()
    )
    global_targets = {(Path.home() / ".codex").expanduser().resolve()}
    configured_codex_home = os.environ.get("CODEX_HOME")
    if configured_codex_home:
        global_targets.add(Path(configured_codex_home).expanduser().resolve())
    active_global_target = target_dir.expanduser().resolve() in global_targets
    if model_profile_requested and (
        not canonical_workspace_target or active_global_target
    ):
        print(
            "Codex agent model profiles are workspace-only. Global Codex roles "
            "must inherit the parent session model. For explicit workspace "
            "materialization, pass --workspace-root <path> and target exactly "
            "<path>/.codex; normally use the installed profile manager with "
            "--scope workspace --workspace <path>.",
            file=sys.stderr,
        )
        return 2
    catalog_path = resolve_catalog_path(args.catalog, asset_root=asset_layout.asset_root)
    profile_dir = (
        asset_layout.asset_root / DEFAULT_PROFILE_DIR
        if args.profile_dir == DEFAULT_PROFILE_DIR
        else Path(args.profile_dir).expanduser()
    )
    model_set_dir = (
        asset_layout.asset_root / DEFAULT_MODEL_SET_DIR
        if args.model_set_dir == DEFAULT_MODEL_SET_DIR
        else Path(args.model_set_dir).expanduser()
    )
    temp_root = resolve_temp_root(repo_root=asset_layout.asset_root, temp_dir=args.temp_dir)
    support_tree_source = asset_layout.support_tree_source
    try:
        support_tree_target = resolve_managed_tree_target(
            target_dir, SUPPORT_TREE_DIRNAME
        )
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    legacy_support_tree_target = target_dir / LEGACY_SUPPORT_TREE_DIRNAME
    workspace_agents_path = (
        None
        if global_agents_target is not None
        else resolve_workspace_agents_path(target_dir, workspace_root)
    )
    global_agents_path = None
    global_agents_block = None
    workspace_agents_block = None
    if not export_script.exists():
        print(f"Export script not found: {export_script.as_posix()}", file=sys.stderr)
        return 2
    if not source_agents_dir.exists():
        print(
            f"Source directory not found: {source_agents_dir.as_posix()}",
            file=sys.stderr,
        )
        return 2
    if not has_support_tree(support_tree_source):
        print(
            "Neutral support tree is incomplete; expected directories "
            + ", ".join(SUPPORT_TREE_DIRS)
            + " and files "
            + ", ".join(SUPPORT_TREE_FILES)
            + f" under {support_tree_source.as_posix()}",
            file=sys.stderr,
        )
        return 2
    try:
        if global_agents_target is not None:
            global_agents_path = resolve_global_agents_path(global_agents_target)
            global_agents_block = build_global_agents_managed_block(modes_path)
        elif workspace_agents_path is not None:
            workspace_agents_block = build_workspace_agents_managed_block(modes_path)
        else:
            global_agents_path = resolve_global_agents_path(target_dir)
            global_agents_block = build_global_agents_managed_block(modes_path)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    temp_dir: Optional[Path] = None
    try:
        temp_dir = run_export(
            export_script,
            source_agents_dir,
            modes_path,
            catalog_path,
            strict=args.strict,
            max_threads=args.max_threads,
            max_depth=args.max_depth,
            job_max_runtime_seconds=args.job_max_runtime_seconds,
            temp_root=temp_root,
            resolve_support_refs_to=support_tree_target,
            agent_profile=args.agent_profile,
            model_set=args.model_set,
            profile_dir=profile_dir,
            model_set_dir=model_set_dir,
            uniform_model=args.uniform_model,
        )
        generated_config = read_text(temp_dir / "config.toml")
        generated_role_files = collect_generated_role_files(temp_dir)
        generated_agent_blocks = extract_generated_agent_blocks(generated_config)

        previous_manifest = infer_previous_managed(target_dir)
        previous_manifest_exists = (target_dir / MANIFEST_FILENAME).exists()
        previous_names = list(previous_manifest["managed_agent_names"])
        previous_files = list(previous_manifest["managed_agent_files"])
        remove_legacy_support = should_remove_legacy_support(
            previous_manifest,
            manifest_exists=previous_manifest_exists,
            legacy_support_path=legacy_support_tree_target,
        )

        current_names = sorted(generated_agent_blocks)
        current_files = sorted(generated_role_files)

        stale_names = sorted(set(previous_names) - set(current_names))
        stale_files = sorted(set(previous_files) - set(current_files))
        stale_file_targets = {
            relative_path: resolve_managed_agent_path(target_dir, relative_path)
            for relative_path in stale_files
        }
        current_file_targets = {
            relative_path: resolve_managed_agent_path(target_dir, relative_path)
            for relative_path in current_files
        }
        for managed_path in {
            *stale_file_targets.values(),
            *current_file_targets.values(),
        }:
            validate_generated_role_ownership(managed_path)

        config_path = target_dir / "config.toml"
        manifest_path = target_dir / MANIFEST_FILENAME
        validate_managed_leaf(config_path, "Codex config")
        validate_managed_leaf(manifest_path, "Codex installer manifest")
        if global_agents_path is not None:
            validate_managed_leaf(global_agents_path, "Global AGENTS file")
        if workspace_agents_path is not None:
            validate_managed_leaf(workspace_agents_path, "Workspace AGENTS file")
        existing_config_text = read_text(config_path) if config_path.exists() else ""
        merged_config_text = merge_config_text(
            existing_config_text,
            generated_agent_blocks,
            previous_agent_names=previous_names,
            max_threads=args.max_threads,
            max_depth=args.max_depth,
            job_max_runtime_seconds=args.job_max_runtime_seconds,
            manage_agent_limits=not workspace_profile_target,
            remove_legacy_agent_limits=(
                workspace_profile_target and previous_manifest_exists
            ),
        )
        merged_global_agents_text: Optional[str] = None
        if global_agents_path is not None and global_agents_block is not None:
            existing_global_agents = (
                read_text(global_agents_path) if global_agents_path.exists() else ""
            )
            merged_global_agents_text = merge_global_agents_text(
                existing_global_agents,
                global_agents_block,
            )
        merged_workspace_agents_text: Optional[str] = None
        if workspace_agents_path is not None and workspace_agents_block is not None:
            existing_workspace_agents = (
                read_text(workspace_agents_path) if workspace_agents_path.exists() else ""
            )
            merged_workspace_agents_text = merge_workspace_agents_text(
                existing_workspace_agents,
                workspace_agents_block,
            )

        if args.dry_run:
            sync_support_tree(
                support_tree_source, support_tree_target, dry_run=True
            )
            print(f"Dry run: would merge Codex config into {target_dir.as_posix()}")
            print("- set features.multi_agent = true")
            if workspace_profile_target:
                print("- preserve agents.max_threads/max_depth from global Codex config")
                if previous_manifest_exists:
                    print(
                        "- remove legacy agents.max_threads/max_depth when they match "
                        "the previous managed defaults"
                    )
            else:
                print(f"- set agents.max_threads = {args.max_threads}")
                print(f"- set agents.max_depth = {args.max_depth}")
            if args.job_max_runtime_seconds is not None:
                print(
                    "- set agents.job_max_runtime_seconds = "
                    + str(args.job_max_runtime_seconds)
                )
            for name in stale_names:
                print(f"- remove stale managed agent entry: [agents.{name}]")
            for relative_path in stale_files:
                print(
                    "- remove stale managed agent file: "
                    + stale_file_targets[relative_path].as_posix()
                )
            for relative_path in current_files:
                print(
                    "- write managed agent file: "
                    + current_file_targets[relative_path].as_posix()
                )
            if remove_legacy_support:
                print(
                    "- remove legacy managed support tree: "
                    + legacy_support_tree_target.as_posix()
                )
            print(
                "- sync neutral Codex support tree: "
                + support_tree_source.as_posix()
                + " -> "
                + support_tree_target.as_posix()
            )
            if global_agents_path is not None:
                print(
                    "- merge managed global AGENTS block: "
                    + global_agents_path.as_posix()
                )
            if workspace_agents_path is not None:
                print(
                    "- merge managed workspace AGENTS block: "
                    + workspace_agents_path.as_posix()
                )
            print(f"- write merged config: {config_path.as_posix()}")
            print(f"- write manifest: {manifest_path.as_posix()}")
            return 0

        target_dir.mkdir(parents=True, exist_ok=True)
        (target_dir / "agents").mkdir(parents=True, exist_ok=True)

        # Validate ownership, then replace the namespaced support tree through
        # rollback-capable staged moves before modifying managed roles/config.
        # An unowned same-named directory is preserved.
        sync_support_tree(support_tree_source, support_tree_target)

        for relative_path in stale_files:
            stale_path = stale_file_targets[relative_path]
            validate_generated_role_ownership(stale_path)
            if remove_file_if_present(
                stale_path, stop_path=target_dir.expanduser().resolve()
            ):
                print(f"Removed stale managed agent file: {stale_path.as_posix()}")

        for relative_path, content in generated_role_files.items():
            validate_generated_role_ownership(current_file_targets[relative_path])
            write_text_atomic(current_file_targets[relative_path], content)

        if remove_legacy_support:
            resolved_legacy_support = resolve_managed_tree_target(
                target_dir, LEGACY_SUPPORT_TREE_DIRNAME
            )
            if resolved_legacy_support.is_dir():
                shutil.rmtree(resolved_legacy_support)
            else:
                resolved_legacy_support.unlink()
            print(
                "Removed legacy managed support tree: "
                + resolved_legacy_support.as_posix()
            )
        if global_agents_path is not None and merged_global_agents_text is not None:
            write_text_atomic(
                global_agents_path,
                merged_global_agents_text,
            )
            print(
                "Merged managed global AGENTS block into "
                + global_agents_path.as_posix()
            )
        if workspace_agents_path is not None and merged_workspace_agents_text is not None:
            write_text_atomic(
                workspace_agents_path,
                merged_workspace_agents_text,
            )
            print(
                "Merged managed workspace AGENTS block into "
                + workspace_agents_path.as_posix()
            )
        write_text_atomic(config_path, merged_config_text)
        write_manifest(
            manifest_path,
            agent_names=current_names,
            agent_files=current_files,
            profile=args.agent_profile,
            model_set=args.model_set,
            uniform_model=args.uniform_model,
            source_agents_dir=source_agents_dir,
            target_dir=target_dir,
        )
        if not workspace_profile_target and workspace_root is None:
            seed_builtin_project_profile_caches(
                support_tree_target, target_dir.expanduser().resolve()
            )

        print(f"Merged Codex config into {target_dir.as_posix()}")
        return 0
    except (
        RuntimeError,
        ValueError,
        json.JSONDecodeError,
        OSError,
        UnicodeDecodeError,
    ) as exc:
        print(str(exc), file=sys.stderr)
        return 2
    finally:
        if temp_dir is not None:
            shutil.rmtree(temp_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
