#!/usr/bin/env python3
"""Runtime-neutral agent model profile manager.

The public actions are ``set``, ``status``, ``clear``, and ``list``.
``install`` remains a compatibility alias for ``set``.  The ``record`` action
is an installer-facing protocol used by the Claude and Copilot installers to
persist deterministic profile metadata.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import IO, Any, Iterable, Mapping, Sequence


SCRIPT_DIR = Path(__file__).resolve().parent.parent / "scripts"
if SCRIPT_DIR.as_posix() not in sys.path:
    sys.path.insert(0, SCRIPT_DIR.as_posix())

from codex_skill_catalog import (  # noqa: E402 - support-tree sibling import.
    MANAGED_SKILL_NAMES,
    SKILL_MARKER_VERSION,
    SKILL_SYNC_STATE_READY,
    skill_collection_issues,
)


PUBLIC_ACTIONS = ("set", "install", "status", "clear", "list")
INTERACTIVE_ACTIONS = ("set", "status", "clear", "list")
INTERNAL_ACTION = "record"
RUNTIMES = ("codex", "claude", "copilot")
SCOPES = ("workspace", "global")
COMMON_MANIFEST_FILENAME = ".agents-pipeline-runtime-profile.json"
CODEX_MANIFEST_FILENAME = ".agents-pipeline-codex-manifest.json"
COMMON_MANIFEST_TOOL = "agents_pipeline.agent-profile"
CODEX_MANIFEST_TOOL = "agents_pipeline.install-codex-config"
COMMON_MANIFEST_VERSION = 1
CODEX_MANIFEST_VERSION = 4
SUPPORTED_CODEX_MANIFEST_VERSIONS = (2, 3, CODEX_MANIFEST_VERSION)

RUNTIME_NAMES = {
    "codex": "Codex",
    "claude": "Claude Code",
    "copilot": "GitHub Copilot",
}
RUNTIME_LABELS = {**RUNTIME_NAMES, "codex": "Codex (recommended)"}

GENERATED_MARKERS = {
    "claude": "<!-- Generated by scripts/export-claude-agents.py",
    "copilot": "<!-- Generated by scripts/export-copilot-agents.py",
}
SAFE_AGENT_STEM = r"[A-Za-z0-9][A-Za-z0-9._-]*"
MANAGED_FILE_PATTERNS = {
    "codex": re.compile(rf"^agents/({SAFE_AGENT_STEM})\.toml$"),
    "claude": re.compile(rf"^({SAFE_AGENT_STEM})\.md$"),
    "copilot": re.compile(rf"^({SAFE_AGENT_STEM})\.agent\.md$"),
}
CODEX_AGENT_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9-]*$")
SUPPORT_MARKER_FILENAME = ".agents-pipeline-support.json"
SUPPORT_MARKER_TOOL = "agents_pipeline.sync-runtime-support"
SUPPORTED_SUPPORT_MARKER_VERSIONS = (1, 2, 3)
SUPPORT_COMMON_REQUIRED_DIRS = (
    "agents",
    "protocols",
    "runtimes",
    "scripts",
    "skills",
    "tools",
)
SUPPORT_COMMON_REQUIRED_FILES = (
    "AGENTS.md",
    "VERSION",
    "modes.json",
    "protocols/UI_UX_WORKFLOW.md",
    "protocols/UX_DEVTOOLS_WORKFLOW.md",
    "scripts/agent-profile.sh",
    "scripts/agent-profile.ps1",
    "scripts/agent_model_profiles.py",
    "scripts/path_safety.py",
    "scripts/sync-runtime-support.py",
    "tools/agent-profile.py",
    "tools/status-event.js",
)
SUPPORT_RUNTIME_REQUIRED_FILES = {
    "codex": (
        "scripts/codex_mode_aliases.py",
        "scripts/codex-project-profile.py",
        "scripts/codex_skill_catalog.py",
        "scripts/export-codex-agents.py",
        "scripts/install-codex-config.py",
        "scripts/install-codex.sh",
        "scripts/install-codex.ps1",
        "scripts/sync-codex-skills.py",
    ),
    "claude": (
        "scripts/export-claude-agents.py",
        "scripts/install-claude.sh",
        "scripts/install-claude.ps1",
    ),
    "copilot": (
        "scripts/export-copilot-agents.py",
        "scripts/install-copilot.sh",
        "scripts/install-copilot.ps1",
    ),
}
CODEX_AGENTS_BEGIN_MARKER = "<!-- BEGIN agents-pipeline-codex-managed -->"
CODEX_AGENTS_END_MARKER = "<!-- END agents-pipeline-codex-managed -->"


class ProfileError(RuntimeError):
    """A clear, user-actionable profile manager failure."""


@dataclass(frozen=True)
class ResolvedRequest:
    action: str
    runtime: str
    scope: str
    workspace: Path
    target: Path
    profile: str | None
    model_set: str | None
    uniform_model: str | None
    profile_dir: Path
    model_set_dir: Path
    asset_root: Path


def _normalize_compat_args(argv: Sequence[str]) -> list[str]:
    """Accept PowerShell-style names without weakening normal argparse rules."""

    aliases = {
        "-Action": "--action",
        "-Profile": "--profile",
        "-Runtime": "--runtime",
        "-Scope": "--scope",
        "-Workspace": "--workspace",
        "-Target": "--target",
        "-Model": "--model",
        "-ModelSet": "--model-set",
        "-UniformModel": "--uniform-model",
        "-ProfileDir": "--profile-dir",
        "-ModelSetDir": "--model-set-dir",
        "-ClaudeMd": "--claude-md",
        "-DryRun": "--dry-run",
        "-NoBackup": "--no-backup",
        "-NoRunner": "--no-runner",
        "-Force": "--force",
        "-Json": "--json",
    }
    return [aliases.get(value, value) for value in argv]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Set and inspect runtime-neutral agent model profiles. "
            "Run without choices in a terminal for an interactive menu."
        )
    )
    parser.add_argument("action", nargs="?", choices=PUBLIC_ACTIONS + (INTERNAL_ACTION,))
    parser.add_argument("positional_profile", nargs="?")
    parser.add_argument("--action", dest="action_option", choices=PUBLIC_ACTIONS + (INTERNAL_ACTION,))
    parser.add_argument("--profile")
    parser.add_argument("--runtime", choices=RUNTIMES, type=str.lower)
    parser.add_argument("--scope", choices=SCOPES, type=str.lower)
    parser.add_argument("--workspace")
    parser.add_argument("--target")
    parser.add_argument("--model-set")
    parser.add_argument("--uniform-model")
    parser.add_argument("--model", help="Compatibility alias for --uniform-model.")
    parser.add_argument("--profile-dir")
    parser.add_argument("--model-set-dir")
    parser.add_argument("--asset-root", help=argparse.SUPPRESS)
    parser.add_argument("--claude-md")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--no-backup", action="store_true")
    parser.add_argument("--no-runner", action="store_true")
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--managed-file", action="append", default=[], help=argparse.SUPPRESS)
    return parser


def _merge_positional_options(args: argparse.Namespace) -> None:
    if args.action and args.action_option and args.action != args.action_option:
        raise ProfileError("Positional action and --action must match when both are supplied.")
    args.action = args.action_option or args.action
    if args.positional_profile and args.profile and args.positional_profile != args.profile:
        raise ProfileError("Positional profile and --profile must match when both are supplied.")
    args.profile = args.profile or args.positional_profile
    if args.model and args.uniform_model and args.model != args.uniform_model:
        raise ProfileError("--model and --uniform-model must match when both are supplied.")
    args.uniform_model = args.uniform_model or args.model


def _stream_is_tty(stream: IO[str]) -> bool:
    try:
        return bool(stream.isatty())
    except (AttributeError, OSError):
        return False


def is_interactive(stdin: IO[str], stdout: IO[str]) -> bool:
    return _stream_is_tty(stdin) and _stream_is_tty(stdout)


def choose_numbered(
    title: str,
    choices: Sequence[tuple[str, str]],
    *,
    stdin: IO[str],
    stdout: IO[str],
) -> str:
    if not choices:
        raise ProfileError(f"No choices are available for {title.lower()}.")
    print(title, file=stdout)
    for index, (_value, label) in enumerate(choices, start=1):
        print(f"  {index}) {label}", file=stdout)
    while True:
        print(f"Select [1-{len(choices)}] (default 1): ", end="", file=stdout, flush=True)
        answer = stdin.readline()
        if answer == "":
            raise ProfileError(f"Input ended while selecting {title.lower()}.")
        answer = answer.strip()
        if answer == "":
            return choices[0][0]
        if answer.isdigit() and 1 <= int(answer) <= len(choices):
            return choices[int(answer) - 1][0]
        print("Invalid selection; enter one of the displayed numbers.", file=stdout)


def require_or_choose(
    value: str | None,
    *,
    name: str,
    title: str,
    choices: Sequence[tuple[str, str]],
    interactive: bool,
    stdin: IO[str],
    stdout: IO[str],
) -> str:
    if value:
        return value
    if not interactive:
        raise ProfileError(
            f"Missing required {name} in non-interactive mode; pass --{name.replace('_', '-')} explicitly."
        )
    return choose_numbered(title, choices, stdin=stdin, stdout=stdout)


def _canonical(path: str | Path) -> Path:
    return Path(path).expanduser().resolve(strict=False)


def _absolute_lexical(path: str | Path) -> Path:
    return Path(os.path.abspath(os.fspath(Path(path).expanduser())))


def _is_linklike(path: Path) -> bool:
    if path.is_symlink():
        return True
    is_junction = getattr(path, "is_junction", None)
    if is_junction and is_junction():
        return True
    try:
        file_attributes = getattr(path.lstat(), "st_file_attributes", 0)
    except OSError:
        return False
    reparse_point = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
    return bool(file_attributes & reparse_point)


def _reject_linklike_path(path: Path, label: str) -> None:
    if _is_linklike(path):
        raise ProfileError(f"{label} must not be a symbolic link or junction: {path}")


def _validate_derived_target(root: Path, target: Path, label: str) -> Path:
    try:
        relative = target.relative_to(root)
    except ValueError as exc:
        raise ProfileError(f"{label} escapes its selected scope: {target}") from exc
    current = root
    for part in relative.parts:
        current = current / part
        _reject_linklike_path(current, label)
    return target


def _default_codex_target(*, home: Path | None, asset_root: Path | None) -> Path:
    if (
        asset_root is not None
        and asset_root.name == "agents-pipeline"
        and (asset_root.parent / CODEX_MANIFEST_FILENAME).is_file()
    ):
        return _absolute_lexical(asset_root.parent)
    if home is not None:
        return _absolute_lexical(_canonical(home) / ".codex")
    if os.environ.get("CODEX_HOME"):
        return _absolute_lexical(os.environ["CODEX_HOME"])
    return _absolute_lexical(Path.home() / ".codex")


def discover_asset_root(explicit: str | None = None) -> Path:
    if explicit:
        root = _canonical(explicit)
    elif os.environ.get("AGENTS_PIPELINE_ASSET_ROOT"):
        root = _canonical(os.environ["AGENTS_PIPELINE_ASSET_ROOT"])
    else:
        root = Path(__file__).resolve().parent.parent
    if not (root / "tools" / "agent-profiles").is_dir():
        raise ProfileError(f"Agent profile assets not found under: {root}")
    return root


def _load_json_object(path: Path, label: str) -> dict[str, Any]:
    if path.is_symlink():
        raise ProfileError(f"{label} must not be a symbolic link: {path}")
    if not path.is_file():
        raise ProfileError(f"{label} not found: {path}")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ProfileError(
            f"Invalid JSON in {label.lower()} {path} at line {exc.lineno}, column {exc.colno}: {exc.msg}"
        ) from exc
    except (OSError, UnicodeDecodeError) as exc:
        raise ProfileError(f"Unable to read {label.lower()} as UTF-8: {path}") from exc
    if not isinstance(value, dict):
        raise ProfileError(f"{label} JSON must be an object: {path}")
    return value


def list_profiles(profile_dir: Path) -> list[dict[str, Any]]:
    if not profile_dir.is_dir():
        raise ProfileError(f"Profile directory not found: {profile_dir}")
    profiles: list[dict[str, Any]] = []
    for path in sorted(profile_dir.glob("*.json")):
        value = _load_json_object(path, "Agent profile")
        if value.get("runtime") != "neutral":
            raise ProfileError(f"Profile runtime must be 'neutral': {path}")
        name = value.get("name")
        models = value.get("models")
        if not isinstance(name, str) or not name or not isinstance(models, dict) or not models:
            raise ProfileError(f"Invalid neutral profile shape: {path}")
        profiles.append(
            {
                "name": name,
                "description": value.get("description") or "",
                "agent_count": len(models),
                "path": path.as_posix(),
            }
        )
    return profiles


def list_model_sets(runtime: str, model_set_dir: Path) -> list[dict[str, Any]]:
    if not model_set_dir.is_dir():
        raise ProfileError(f"Model-set directory not found for {runtime}: {model_set_dir}")
    model_sets: list[dict[str, Any]] = []
    for path in sorted(model_set_dir.glob("*.json")):
        value = _load_json_object(path, "Runtime model set")
        if value.get("runtime") != runtime:
            raise ProfileError(f"Model-set runtime must be '{runtime}': {path}")
        name = value.get("name")
        tiers = value.get("tiers")
        if not isinstance(name, str) or not name or not isinstance(tiers, dict):
            raise ProfileError(f"Invalid runtime model-set shape: {path}")
        missing = [tier for tier in ("mini", "standard", "strong") if tier not in tiers]
        if missing:
            raise ProfileError(f"Model set is missing tiers {', '.join(missing)}: {path}")
        model_sets.append(
            {
                "name": name,
                "description": value.get("description") or "",
                "tiers": tiers,
                "path": path.as_posix(),
            }
        )
    return model_sets


def _profile_choices(profiles: Sequence[Mapping[str, Any]]) -> list[tuple[str, str]]:
    ordered = sorted(profiles, key=lambda value: (value["name"] != "balanced", value["name"]))
    choices = [
        (
            str(value["name"]),
            f"{value['name']}{' (recommended)' if value['name'] == 'balanced' else ''} — {value['description']}",
        )
        for value in ordered
    ]
    choices.append(("uniform", "uniform — apply one model to every generated agent"))
    return choices


def resolve_target(
    runtime: str,
    scope: str,
    *,
    workspace: Path,
    explicit_target: str | None,
    home: Path | None = None,
    asset_root: Path | None = None,
) -> Path:
    if explicit_target:
        if not explicit_target.strip():
            raise ProfileError("--target must not be empty or whitespace.")
        target = _absolute_lexical(explicit_target)
        _reject_linklike_path(target, "Explicit target")
        return target.parent.resolve(strict=False) / target.name
    home_dir = _canonical(home or Path.home())
    if scope == "workspace":
        suffixes = {
            "codex": Path(".codex"),
            "claude": Path(".claude/agents"),
            "copilot": Path(".github/agents"),
        }
        target = _absolute_lexical(workspace / suffixes[runtime])
        return _validate_derived_target(workspace, target, "Workspace target")
    codex_target = _default_codex_target(home=home, asset_root=asset_root)
    global_targets = {
        "codex": codex_target,
        "claude": home_dir / ".claude/agents",
        "copilot": home_dir / ".copilot/agents",
    }
    target = _absolute_lexical(global_targets[runtime])
    if runtime == "codex":
        _reject_linklike_path(target, "Global target")
        return target.parent.resolve(strict=False) / target.name
    return _validate_derived_target(home_dir, target, "Global target")


def resolve_request(
    args: argparse.Namespace,
    *,
    stdin: IO[str] = sys.stdin,
    stdout: IO[str] = sys.stdout,
    home: Path | None = None,
) -> ResolvedRequest:
    _merge_positional_options(args)
    interactive = is_interactive(stdin, stdout)
    action = require_or_choose(
        args.action,
        name="action",
        title="Choose an action",
        choices=[(value, value) for value in INTERACTIVE_ACTIONS],
        interactive=interactive,
        stdin=stdin,
        stdout=stdout,
    )
    if action == "install":
        action = "set"
    runtime = require_or_choose(
        args.runtime,
        name="runtime",
        title="Choose a runtime",
        choices=[(value, RUNTIME_LABELS[value]) for value in RUNTIMES],
        interactive=interactive,
        stdin=stdin,
        stdout=stdout,
    )

    asset_root = discover_asset_root(args.asset_root)
    profile_dir = _canonical(args.profile_dir or asset_root / "tools/agent-profiles")
    model_set_dir = _canonical(
        args.model_set_dir or asset_root / "runtimes" / runtime / "model-sets"
    )
    workspace = _canonical(args.workspace or Path.cwd())
    scope_choices = (
        [
            ("global", "global install diagnostics / legacy cleanup"),
            ("workspace", "workspace profile"),
        ]
        if runtime == "codex"
        else [("global", "global (recommended)")]
    )

    if action == INTERNAL_ACTION:
        if args.target is None:
            raise ProfileError("record requires --target.")
        scope = args.scope or "workspace"
    elif action == "list":
        scope = args.scope or "global"
    elif runtime == "codex" and action == "set":
        # Codex global roles are always model-free and inherit the parent
        # session. Resource-tier profiles belong only to project-local roles.
        scope = args.scope or "workspace"
    elif args.target:
        if args.scope:
            scope = args.scope
        elif runtime == "codex" and action == "status":
            # A read-only explicit target historically means a native/global
            # installer target. Workspace status has the unambiguous
            # --scope workspace --workspace surface.
            scope = "global"
        elif runtime == "codex" and action == "clear":
            explicit_target = _canonical(resolve_target(
                runtime,
                "workspace",
                workspace=workspace,
                explicit_target=args.target,
                home=home,
                asset_root=asset_root,
            ))
            workspace_target = _canonical(resolve_target(
                runtime,
                "workspace",
                workspace=workspace,
                explicit_target=None,
                home=home,
                asset_root=asset_root,
            ))
            global_target = _canonical(resolve_target(
                runtime,
                "global",
                workspace=workspace,
                explicit_target=None,
                home=home,
                asset_root=asset_root,
            ))
            if explicit_target == workspace_target:
                scope = "workspace"
            elif explicit_target == global_target:
                scope = "global"
            else:
                scope = require_or_choose(
                    None,
                    name="scope",
                    title="Choose how this custom Codex target should behave",
                    choices=scope_choices,
                    interactive=interactive,
                    stdin=stdin,
                    stdout=stdout,
                )
        else:
            scope = "workspace"
    else:
        scope = require_or_choose(
            args.scope,
            name="scope",
            title="Choose a profile scope",
            choices=scope_choices,
            interactive=interactive,
            stdin=stdin,
            stdout=stdout,
        )

    if runtime == "codex" and action == "set" and scope != "workspace":
        raise ProfileError(
            "Codex agent model profiles are workspace-only. Install global roles "
            "without a profile, then use --scope workspace --workspace <path>."
        )

    if (
        interactive
        and action not in ("list", INTERNAL_ACTION)
        and scope == "workspace"
        and args.workspace is None
        and args.target is None
    ):
        print(
            f"Workspace path (default {workspace}): ",
            end="",
            file=stdout,
            flush=True,
        )
        answer = stdin.readline()
        if answer == "":
            raise ProfileError("Input ended while selecting the workspace path.")
        if answer.strip():
            workspace = _canonical(answer.strip())

    target = resolve_target(
        runtime,
        scope,
        workspace=workspace,
        explicit_target=args.target,
        home=home,
        asset_root=asset_root,
    )
    if runtime == "codex" and action == "set" and args.target:
        global_target = resolve_target(
            runtime,
            "global",
            workspace=workspace,
            explicit_target=None,
            home=home,
            asset_root=asset_root,
        )
        if target == global_target:
            raise ProfileError(
                "Codex agent model profiles are workspace-only. The global Codex "
                "installation must remain model-free."
            )
    if (
        runtime == "codex"
        and scope == "workspace"
        and args.target
        and action in ("set", "clear", "status")
    ):
        expected_workspace_target = resolve_target(
            runtime,
            "workspace",
            workspace=workspace,
            explicit_target=None,
            home=home,
            asset_root=asset_root,
        )
        if target != expected_workspace_target:
            raise ProfileError(
                "Codex project profiles always target <workspace>/.codex. "
                "Use --workspace to select the project; omit --target."
            )

    profile = args.profile
    model_set = args.model_set
    uniform_model = args.uniform_model
    if scope == "workspace" and runtime != "codex" and action in ("set", "clear"):
        raise ProfileError(
            f"Workspace profile-only setup is not supported for {RUNTIME_NAMES[runtime]}. "
            "Use global scope, or call the direct installer explicitly to materialize project agents."
        )

    if action == "set":
        profiles = list_profiles(profile_dir)
        profile = require_or_choose(
            profile,
            name="profile",
            title="Choose an agent profile",
            choices=_profile_choices(profiles),
            interactive=interactive,
            stdin=stdin,
            stdout=stdout,
        )
        known_profiles = {str(value["name"]) for value in profiles}
        if profile != "uniform" and profile not in known_profiles:
            raise ProfileError(
                f"Unknown profile '{profile}'. Available profiles: {', '.join(sorted(known_profiles))}, uniform."
            )
        if profile == "uniform":
            if model_set:
                raise ProfileError("--model-set is not valid with the uniform profile.")
            if not uniform_model:
                if not interactive:
                    raise ProfileError(
                        "Missing required uniform model in non-interactive mode; pass --uniform-model explicitly."
                    )
                print("Uniform model: ", end="", file=stdout, flush=True)
                uniform_model = stdin.readline().strip()
                if not uniform_model:
                    raise ProfileError("Uniform model must not be empty.")
        else:
            if uniform_model:
                raise ProfileError("--uniform-model is only valid with the uniform profile.")
            model_sets = list_model_sets(runtime, model_set_dir)
            model_set = require_or_choose(
                model_set,
                name="model_set",
                title=f"Choose a {RUNTIME_NAMES[runtime]} model set",
                choices=[
                    (str(value["name"]), f"{value['name']} — {value['description']}")
                    for value in model_sets
                ],
                interactive=interactive,
                stdin=stdin,
                stdout=stdout,
            )
            known_model_sets = {str(value["name"]) for value in model_sets}
            if model_set not in known_model_sets:
                raise ProfileError(
                    f"Unknown model set '{model_set}' for {runtime}. Available: {', '.join(sorted(known_model_sets))}."
                )

    return ResolvedRequest(
        action=action,
        runtime=runtime,
        scope=scope,
        workspace=workspace,
        target=target,
        profile=profile,
        model_set=model_set,
        uniform_model=uniform_model,
        profile_dir=profile_dir,
        model_set_dir=model_set_dir,
        asset_root=asset_root,
    )


def resolve_installer(request: ResolvedRequest, *, windows: bool | None = None) -> Path:
    use_windows = os.name == "nt" if windows is None else windows
    suffix = ".ps1" if use_windows else ".sh"
    installer = request.asset_root / "scripts" / f"install-{request.runtime}{suffix}"
    if not installer.is_file():
        raise ProfileError(f"Runtime installer not found: {installer}")
    return installer


def build_install_command(
    request: ResolvedRequest,
    args: argparse.Namespace,
    *,
    windows: bool | None = None,
    home: Path | None = None,
) -> list[str]:
    use_windows = os.name == "nt" if windows is None else windows
    installer = resolve_installer(request, windows=use_windows)
    if use_windows:
        shell = shutil.which("pwsh") or "pwsh"
        command = [shell, "-NoProfile", "-File", str(installer), "-Target", str(request.target)]
        names = {
            "global_agents": "-GlobalAgentsTarget",
            "user_skills": "-UserSkillsRoot",
            "profile": "-AgentProfile",
            "model_set": "-ModelSet",
            "profile_dir": "-ProfileDir",
            "model_set_dir": "-ModelSetDir",
            "uniform": "-UniformModel",
            "dry_run": "-DryRun",
            "no_backup": "-NoBackup",
            "force": "-Force",
            "claude_md": "-ClaudeMd",
            "no_runner": "-NoRunner",
        }
    else:
        shell = shutil.which("bash") or "bash"
        command = [shell, str(installer), "--target", str(request.target)]
        names = {
            "global_agents": "--global-agents-target",
            "user_skills": "--user-skills-root",
            "profile": "--agent-profile",
            "model_set": "--model-set",
            "profile_dir": "--profile-dir",
            "model_set_dir": "--model-set-dir",
            "uniform": "--uniform-model",
            "dry_run": "--dry-run",
            "no_backup": "--no-backup",
            "force": "--force",
            "claude_md": "--claude-md",
            "no_runner": "--no-runner",
        }

    if request.runtime == "codex" and request.scope == "workspace":
        command.extend([names["global_agents"], str(_canonical(home or Path.home()) / ".codex")])
    elif (
        request.runtime == "codex"
        and request.scope == "global"
        and request.action == "clear"
    ):
        managed_user_skills_root = _codex_manifest_user_skills_root(request.target)
        if managed_user_skills_root is not None:
            command.extend([names["user_skills"], managed_user_skills_root])
    if args.dry_run:
        command.append(names["dry_run"])
    if args.no_backup:
        command.append(names["no_backup"])
    if args.force and request.runtime == "codex":
        command.append(names["force"])
    if request.runtime != "claude" and (args.claude_md or args.no_runner):
        raise ProfileError("--claude-md and --no-runner are only valid for Claude Code.")
    if request.runtime == "claude":
        if args.claude_md:
            command.extend([names["claude_md"], str(_canonical(args.claude_md))])
        elif request.scope == "workspace" and not args.target and not args.no_runner:
            command.extend([names["claude_md"], str(request.workspace / "CLAUDE.md")])
        if args.no_runner:
            command.append(names["no_runner"])

    if request.action == "set":
        if request.profile == "uniform":
            command.extend([names["uniform"], str(request.uniform_model)])
        else:
            command.extend(
                [
                    names["profile"],
                    str(request.profile),
                    names["model_set"],
                    str(request.model_set),
                    names["profile_dir"],
                    str(request.profile_dir),
                    names["model_set_dir"],
                    str(request.model_set_dir),
                ]
            )
    elif request.action != "clear":
        raise ProfileError(f"Cannot construct an installer command for action '{request.action}'.")
    return command


def build_project_profile_command(
    request: ResolvedRequest,
    args: argparse.Namespace,
    *,
    home: Path | None = None,
) -> list[str]:
    global_target = _canonical(
        _default_codex_target(home=home, asset_root=request.asset_root)
    )
    global_asset_root = global_target / "agents-pipeline"
    helper = global_asset_root / "scripts" / "codex-project-profile.py"
    if not helper.is_file():
        raise ProfileError(
            "Codex project profile helper is missing from the selected global install: "
            f"{helper}. Run the global bootstrap first."
        )
    command = [
        sys.executable,
        str(helper),
        request.action,
        "--workspace",
        str(request.workspace),
        "--global-target",
        str(global_target),
        "--asset-root",
        str(global_asset_root),
    ]
    if args.dry_run:
        command.append("--dry-run")
    if args.json:
        command.append("--json")
    if request.action == "set":
        if request.profile == "uniform":
            command.extend(["--uniform-model", str(request.uniform_model)])
        else:
            command.extend(
                ["--profile", str(request.profile), "--model-set", str(request.model_set)]
            )
    return command


def _validate_manifest_leaf(path: Path) -> None:
    if path.is_symlink():
        raise ProfileError(f"Runtime profile manifest must not be a symbolic link: {path}")
    if path.exists() and not path.is_file():
        raise ProfileError(f"Runtime profile manifest must be a regular file: {path}")


def _atomic_json_write(path: Path, payload: Mapping[str, Any]) -> None:
    _validate_manifest_leaf(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temp_path, path.stat().st_mode & 0o777 if path.exists() else 0o644)
        os.replace(temp_path, path)
    finally:
        try:
            temp_path.unlink()
        except FileNotFoundError:
            pass


def _safe_relative_managed_file(
    target: Path,
    raw: str,
    *,
    require_file: bool = True,
) -> str:
    candidate = Path(raw)
    lexical = candidate if candidate.is_absolute() else target / candidate
    lexical = Path(os.path.abspath(os.path.expanduser(str(lexical))))
    try:
        lexical_relative = lexical.relative_to(target)
    except ValueError as exc:
        raise ProfileError(f"Managed generated file escapes target: {raw}") from exc
    if not lexical_relative.parts or any(
        part in ("", ".", "..") for part in lexical_relative.parts
    ):
        raise ProfileError(f"Invalid managed generated file: {raw}")
    if lexical.is_symlink():
        raise ProfileError(f"Managed generated file must not be a symbolic link: {lexical}")
    absolute = lexical.resolve(strict=False)
    try:
        relative = absolute.relative_to(target)
    except ValueError as exc:
        raise ProfileError(f"Managed generated file escapes target: {raw}") from exc
    if require_file and not absolute.is_file():
        raise ProfileError(f"Managed generated file is not a regular file: {absolute}")
    return relative.as_posix()


def discover_managed_files(runtime: str, target: Path) -> list[str]:
    marker = GENERATED_MARKERS.get(runtime)
    if marker is None or not target.is_dir():
        return []
    pattern = "*.md" if runtime == "claude" else "*.agent.md"
    managed: list[str] = []
    for path in sorted(target.glob(pattern)):
        if path.is_symlink() or not path.is_file():
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if marker in content:
            managed.append(path.relative_to(target).as_posix())
    return managed


def record_manifest(
    request: ResolvedRequest,
    args: argparse.Namespace,
    *,
    dry_run: bool | None = None,
) -> Path:
    if request.runtime == "codex":
        raise ProfileError("Codex records profile state in its native installer manifest; record is for Claude and Copilot installers.")
    target = request.target
    if target.exists() and not target.is_dir():
        raise ProfileError(f"Runtime profile target must be a directory: {target}")
    manifest_path = target / COMMON_MANIFEST_FILENAME
    _validate_manifest_leaf(manifest_path)
    preflight = args.dry_run if dry_run is None else dry_run
    if request.uniform_model and request.model_set:
        raise ProfileError("record cannot combine --uniform-model with --model-set.")
    if request.uniform_model and request.profile not in (None, "uniform"):
        raise ProfileError("record cannot combine a named --profile with --uniform-model.")
    if request.profile == "uniform" and not request.uniform_model:
        raise ProfileError("record profile 'uniform' requires --uniform-model.")
    if request.profile not in (None, "uniform") and not request.model_set:
        raise ProfileError("record with a named --profile requires --model-set.")
    if request.model_set and not request.profile:
        raise ProfileError("record --model-set requires --profile.")
    if preflight:
        managed_files = sorted(
            {
                _safe_relative_managed_file(target, raw, require_file=False)
                for raw in args.managed_file
            }
        )
    else:
        raw_files = list(args.managed_file) or discover_managed_files(request.runtime, target)
        managed_files = sorted({_safe_relative_managed_file(target, raw) for raw in raw_files})
    if request.uniform_model:
        mode = "uniform"
        profile = "uniform"
    elif request.profile:
        mode = "profile"
        profile = request.profile
    else:
        mode = "inherit"
        profile = None
    payload = {
        "managed_generated_count": len(managed_files),
        "managed_generated_files": managed_files,
        "mode": mode,
        "model_set": request.model_set,
        "profile": profile,
        "runtime": request.runtime,
        "target": target.as_posix(),
        "tool": COMMON_MANIFEST_TOOL,
        "uniform_model": request.uniform_model,
        "version": COMMON_MANIFEST_VERSION,
    }
    if not preflight:
        _atomic_json_write(manifest_path, payload)
    return manifest_path


def _require_exact_string(data: Mapping[str, Any], key: str, expected: str, path: Path) -> None:
    if data.get(key) != expected:
        raise ProfileError(f"{path}: invalid {key}; expected '{expected}'.")


def _normalize_file_list(
    data: Mapping[str, Any], key: str, path: Path, *, runtime: str
) -> tuple[list[str], list[str]]:
    value = data.get(key)
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise ProfileError(f"{path}: {key} must be an array of strings.")
    if len(value) != len(set(value)):
        raise ProfileError(f"{path}: {key} contains duplicates.")
    pattern = MANAGED_FILE_PATTERNS[runtime]
    names: list[str] = []
    for item in value:
        match = pattern.fullmatch(item)
        if match is None:
            raise ProfileError(f"{path}: unsafe managed generated file for {runtime}: {item!r}.")
        names.append(match.group(1))
    ordered = sorted(zip(value, names))
    return [item for item, _name in ordered], [name for _item, name in ordered]


def _normalize_codex_agent_names(data: Mapping[str, Any], path: Path) -> list[str]:
    value = data.get("managed_agent_names")
    if not isinstance(value, list) or not all(
        isinstance(item, str) and CODEX_AGENT_NAME_RE.fullmatch(item) for item in value
    ):
        raise ProfileError(f"{path}: managed_agent_names must contain safe Codex agent names.")
    if len(value) != len(set(value)):
        raise ProfileError(f"{path}: managed_agent_names contains duplicates.")
    return sorted(value)


def _missing_managed_files(target: Path, files: Sequence[str]) -> list[str]:
    missing: list[str] = []
    for relative in files:
        candidate = target / Path(relative)
        if _is_linklike(candidate) or not candidate.is_file():
            missing.append(relative)
    return missing


def _codex_global_model_policy_violations(
    target: Path, files: Sequence[str]
) -> list[str]:
    violations: list[str] = []
    for relative in files:
        candidate = target / Path(relative)
        if _is_linklike(candidate) or not candidate.is_file():
            continue
        try:
            role = tomllib.loads(candidate.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
            violations.append(f"policy:global-role-invalid:{relative}")
            continue
        for key in ("model", "model_provider"):
            if key in role:
                violations.append(
                    f"policy:global-role-model-override:{relative}:{key}"
                )
    return violations


def _runtime_support_root(runtime: str, target: Path) -> Path:
    return target / "agents-pipeline" if runtime == "codex" else target.parent / "agents-pipeline"


def _missing_runtime_support(runtime: str, target: Path) -> list[str]:
    support_root = _runtime_support_root(runtime, target)
    prefix = f"support:{support_root}"
    if _is_linklike(support_root) or not support_root.is_dir():
        return [prefix]
    missing = [
        f"{prefix}/{name}"
        for name in SUPPORT_COMMON_REQUIRED_DIRS
        if _is_linklike(support_root / name) or not (support_root / name).is_dir()
    ]
    required_files = (
        SUPPORT_COMMON_REQUIRED_FILES + SUPPORT_RUNTIME_REQUIRED_FILES[runtime]
    )
    missing.extend(
        f"{prefix}/{name}"
        for name in required_files
        if _is_linklike(support_root / name) or not (support_root / name).is_file()
    )
    marker_path = support_root / SUPPORT_MARKER_FILENAME
    if _is_linklike(marker_path) or not marker_path.is_file():
        missing.append(f"{prefix}/{SUPPORT_MARKER_FILENAME}")
        return sorted(set(missing))
    try:
        marker = _load_json_object(marker_path, "Runtime support marker")
    except ProfileError:
        missing.append(f"{prefix}/{SUPPORT_MARKER_FILENAME}:invalid")
        return sorted(set(missing))
    version = marker.get("version")
    if (
        marker.get("tool") != SUPPORT_MARKER_TOOL
        or type(version) is not int
        or version not in SUPPORTED_SUPPORT_MARKER_VERSIONS
    ):
        missing.append(f"{prefix}/{SUPPORT_MARKER_FILENAME}:invalid")
    elif version == 3:
        installed_root = marker.get("installed_root")
        if not isinstance(installed_root, str) or _canonical(installed_root) != support_root:
            missing.append(f"{prefix}/{SUPPORT_MARKER_FILENAME}:root-mismatch")
    return sorted(set(missing))


def _missing_codex_config_registration(target: Path, agent_names: Sequence[str]) -> list[str]:
    agents_dir = target / "agents"
    if _is_linklike(agents_dir) or not agents_dir.is_dir():
        return [f"config:{agents_dir}"]
    config_path = target / "config.toml"
    if _is_linklike(config_path) or not config_path.is_file():
        return [f"config:{config_path}"]
    try:
        config = tomllib.loads(config_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, tomllib.TOMLDecodeError):
        return [f"config:{config_path}:invalid"]
    agents = config.get("agents")
    if not isinstance(agents, dict):
        return [f"config:{config_path}:agents"]
    missing: list[str] = []
    for name in agent_names:
        entry = agents.get(name)
        raw_config_file = entry.get("config_file") if isinstance(entry, dict) else None
        if not isinstance(raw_config_file, str) or not raw_config_file:
            missing.append(f"config:agents.{name}.config_file")
            continue
        candidate = Path(raw_config_file).expanduser()
        if not candidate.is_absolute():
            candidate = target / candidate
        if candidate.resolve(strict=False) != (target / "agents" / f"{name}.toml").resolve():
            missing.append(f"config:agents.{name}.config_file")
    features = config.get("features")
    if not isinstance(features, dict) or features.get("multi_agent") is not True:
        missing.append("config:features.multi_agent")
    multi_agent_v2 = (
        features.get("multi_agent_v2") if isinstance(features, dict) else None
    )
    if not (
        multi_agent_v2 is True
        or (
            isinstance(multi_agent_v2, dict)
            and multi_agent_v2.get("enabled") is True
        )
    ):
        missing.append("config:features.multi_agent_v2")
    return missing


def _codex_user_skill_status(
    data: Mapping[str, Any], path: Path
) -> tuple[str | None, list[str], list[str]]:
    """Validate v4 discovery-skill metadata and return root, names, issues."""

    if data.get("version") < 4:
        return None, [], []
    raw_root = data.get("managed_user_skills_root")
    raw_names = data.get("managed_skill_names")
    raw_marker_version = data.get("managed_skill_marker_version")
    raw_sync_state = data.get("managed_skill_sync_state")
    if raw_root is None:
        if (
            raw_names != []
            or raw_marker_version is not None
            or raw_sync_state is not None
        ):
            raise ProfileError(f"{path}: invalid unmanaged user skill declaration.")
        return None, [], []
    if (
        not isinstance(raw_root, str)
        or not Path(raw_root).is_absolute()
        or raw_names != sorted(MANAGED_SKILL_NAMES)
        or raw_marker_version != SKILL_MARKER_VERSION
        or not isinstance(raw_sync_state, str)
    ):
        raise ProfileError(f"{path}: invalid managed user skill declaration.")
    root = _canonical(raw_root)
    names = list(raw_names)
    issues = skill_collection_issues(root, names)
    if raw_sync_state != SKILL_SYNC_STATE_READY:
        issues.insert(0, "skills:sync-pending")
    return root.as_posix(), names, issues


def _codex_manifest_user_skills_root(target: Path) -> str | None:
    """Recover installer-managed discovery root for a model-free global refresh."""

    path = target / CODEX_MANIFEST_FILENAME
    _validate_manifest_leaf(path)
    if not path.exists():
        return None
    data = _load_json_object(path, "Runtime profile manifest")
    _require_exact_string(data, "tool", CODEX_MANIFEST_TOOL, path)
    if data.get("version") not in SUPPORTED_CODEX_MANIFEST_VERSIONS:
        raise ProfileError(f"{path}: unsupported Codex manifest version.")
    declared_target = data.get("target_dir")
    if not isinstance(declared_target, str) or _canonical(declared_target) != target:
        raise ProfileError(
            f"{path}: manifest target does not match requested target {target}."
        )
    root, _names, _issues = _codex_user_skill_status(data, path)
    return root


def _markdown_marker_indexes(lines: Sequence[str], marker: str) -> list[int]:
    indexes: list[int] = []
    fence_char: str | None = None
    fence_length = 0
    for index, line in enumerate(lines):
        leading_spaces = len(line) - len(line.lstrip(" "))
        candidate = line[leading_spaces:] if leading_spaces <= 3 else ""
        if fence_char is not None:
            run = len(candidate) - len(candidate.lstrip(fence_char))
            if run >= fence_length and not candidate[run:].strip():
                fence_char = None
                fence_length = 0
            continue
        if candidate.startswith("```") or candidate.startswith("~~~"):
            fence_char = candidate[0]
            fence_length = len(candidate) - len(candidate.lstrip(fence_char))
            continue
        if leading_spaces >= 4 or line.startswith("\t"):
            continue
        if line.strip() == marker:
            indexes.append(index)
    return indexes


def _missing_codex_global_agents(target: Path) -> list[str]:
    override = target / "AGENTS.override.md"
    if _is_linklike(override):
        return [f"global-agents:{override}"]
    try:
        override_active = (
            override.is_file() and override.read_text(encoding="utf-8").strip()
        )
    except (OSError, UnicodeDecodeError):
        return [f"global-agents:{override}:unreadable"]
    active = override if override_active else target / "AGENTS.md"
    if _is_linklike(active) or not active.is_file():
        return [f"global-agents:{active}"]
    try:
        lines = active.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeDecodeError):
        return [f"global-agents:{active}:unreadable"]
    starts = _markdown_marker_indexes(lines, CODEX_AGENTS_BEGIN_MARKER)
    ends = _markdown_marker_indexes(lines, CODEX_AGENTS_END_MARKER)
    if len(starts) != 1 or len(ends) != 1 or ends[0] <= starts[0]:
        return [f"global-agents:{active}:managed-block"]
    return []


def _normalize_profile_state(
    data: Mapping[str, Any], path: Path, *, inherit_mode: str
) -> tuple[str, str | None, str | None, str | None]:
    mode = data.get("mode")
    profile = data.get("profile")
    model_set = data.get("model_set")
    uniform_model = data.get("uniform_model")
    if mode == inherit_mode:
        if any(value is not None for value in (profile, model_set, uniform_model)):
            raise ProfileError(f"{path}: inherited profile state must not pin model settings.")
        return "inherit", None, None, None
    if mode == "profile":
        if not isinstance(profile, str) or not profile:
            raise ProfileError(f"{path}: profile mode requires a profile name.")
        if not isinstance(model_set, str) or not model_set:
            raise ProfileError(f"{path}: profile mode requires a model set.")
        if uniform_model is not None:
            raise ProfileError(f"{path}: profile mode must not set a uniform model.")
        return mode, profile, model_set, None
    if mode == "uniform":
        if profile not in (None, "uniform"):
            raise ProfileError(f"{path}: uniform mode has an invalid profile value.")
        if model_set is not None:
            raise ProfileError(f"{path}: uniform mode must not set a model set.")
        if not isinstance(uniform_model, str) or not uniform_model:
            raise ProfileError(f"{path}: uniform mode requires a uniform model.")
        return mode, "uniform", None, uniform_model
    raise ProfileError(f"{path}: unsupported profile mode {mode!r}.")


def read_status(request: ResolvedRequest) -> dict[str, Any] | None:
    if request.runtime == "codex":
        path = request.target / CODEX_MANIFEST_FILENAME
    else:
        path = request.target / COMMON_MANIFEST_FILENAME
    _validate_manifest_leaf(path)
    if not path.exists():
        return None
    data = _load_json_object(path, "Runtime profile manifest")

    if request.runtime == "codex":
        _require_exact_string(data, "tool", CODEX_MANIFEST_TOOL, path)
        if data.get("version") not in SUPPORTED_CODEX_MANIFEST_VERSIONS:
            raise ProfileError(f"{path}: unsupported Codex manifest version.")
        if (
            data.get("version") >= 3
            and data.get("managed_support_root") != "agents-pipeline"
        ):
            raise ProfileError(f"{path}: invalid managed support root.")
        declared_target = data.get("target_dir")
        if not isinstance(declared_target, str) or _canonical(declared_target) != request.target:
            raise ProfileError(f"{path}: manifest target does not match requested target {request.target}.")
        files, file_names = _normalize_file_list(
            data, "managed_agent_files", path, runtime="codex"
        )
        agent_names = _normalize_codex_agent_names(data, path)
        if agent_names != sorted(file_names):
            raise ProfileError(
                f"{path}: managed Codex agent names do not match managed agent files."
            )
        mode, profile, model_set, uniform_model = _normalize_profile_state(
            data, path, inherit_mode="default"
        )
        missing_files = _missing_managed_files(request.target, files)
        missing_files.extend(_missing_runtime_support(request.runtime, request.target))
        missing_files.extend(
            _missing_codex_config_registration(request.target, agent_names)
        )
        missing_files.extend(_missing_codex_global_agents(request.target))
        skill_root, skill_names, skill_issues = _codex_user_skill_status(data, path)
        missing_files.extend(skill_issues)
        if mode != "inherit":
            missing_files.append(f"policy:global-profile-mode:{mode}")
        missing_files.extend(
            _codex_global_model_policy_violations(request.target, files)
        )
        return {
            "health": "ok" if not missing_files else "incomplete",
            "managed_generated_count": len(files),
            "managed_generated_files": files,
            "managed_skill_count": len(skill_names),
            "managed_skill_names": skill_names,
            "managed_user_skills_root": skill_root,
            "manifest": path.as_posix(),
            "missing_generated_files": missing_files,
            "mode": mode,
            "model_set": model_set,
            "profile": profile,
            "runtime": request.runtime,
            "target": request.target.as_posix(),
            "uniform_model": uniform_model,
        }

    _require_exact_string(data, "tool", COMMON_MANIFEST_TOOL, path)
    _require_exact_string(data, "runtime", request.runtime, path)
    if data.get("version") != COMMON_MANIFEST_VERSION:
        raise ProfileError(f"{path}: unsupported runtime profile manifest version.")
    declared_target = data.get("target")
    if not isinstance(declared_target, str) or _canonical(declared_target) != request.target:
        raise ProfileError(f"{path}: manifest target does not match requested target {request.target}.")
    files, _file_names = _normalize_file_list(
        data, "managed_generated_files", path, runtime=request.runtime
    )
    if data.get("managed_generated_count") != len(files):
        raise ProfileError(f"{path}: managed generated file count does not match the file list.")
    mode, profile, model_set, uniform_model = _normalize_profile_state(
        data, path, inherit_mode="inherit"
    )
    missing_files = _missing_managed_files(request.target, files)
    missing_files.extend(_missing_runtime_support(request.runtime, request.target))
    return {
        "health": "ok" if not missing_files else "incomplete",
        "managed_generated_count": len(files),
        "managed_generated_files": files,
        "manifest": path.as_posix(),
        "missing_generated_files": missing_files,
        "mode": mode,
        "model_set": model_set,
        "profile": profile,
        "runtime": request.runtime,
        "target": request.target.as_posix(),
        "uniform_model": uniform_model,
    }


def print_status(status: dict[str, Any] | None, request: ResolvedRequest, *, as_json: bool) -> None:
    if as_json:
        payload = status or {
            "installed": False,
            "runtime": request.runtime,
            "target": request.target.as_posix(),
        }
        if status is not None:
            payload = {"installed": True, **status}
        print(json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False))
        return
    print(f"Runtime: {request.runtime}")
    print(f"Target: {request.target}")
    if status is None:
        print("Profile state: not installed")
        return
    print(f"Profile: {status.get('profile') or 'inherit'}")
    print(f"Mode: {status.get('mode') or 'inherit'}")
    if status.get("model_set"):
        print(f"Model set: {status['model_set']}")
    if status.get("uniform_model"):
        print(f"Uniform model: {status['uniform_model']}")
    print(f"Health: {status['health']}")
    print(f"Managed generated files: {status['managed_generated_count']}")
    if status.get("managed_user_skills_root"):
        print(f"Managed global skills: {status.get('managed_skill_count', 0)}")
        print(f"Global skill root: {status['managed_user_skills_root']}")
    if status["missing_generated_files"]:
        print(f"Missing generated files: {len(status['missing_generated_files'])}")
        for relative in status["missing_generated_files"]:
            print(f"- {relative}")
    print(f"Manifest: {status['manifest']}")


def print_listing(request: ResolvedRequest, *, as_json: bool) -> None:
    profiles = list_profiles(request.profile_dir)
    model_sets = list_model_sets(request.runtime, request.model_set_dir)
    if as_json:
        print(
            json.dumps(
                {"runtime": request.runtime, "profiles": profiles, "model_sets": model_sets},
                indent=2,
                sort_keys=True,
                ensure_ascii=False,
            )
        )
        return
    print(f"Runtime: {request.runtime}")
    print("Profiles:")
    for profile in profiles:
        print(f"- {profile['name']}: {profile['agent_count']} agents. {profile['description']}")
    print("- uniform: apply one model to every generated agent")
    print("Model sets:")
    for model_set in model_sets:
        tiers = json.dumps(model_set["tiers"], sort_keys=True, ensure_ascii=False)
        print(f"- {model_set['name']}: {tiers}")


def execute(
    args: argparse.Namespace,
    request: ResolvedRequest,
    *,
    runner: Any = subprocess.run,
) -> int:
    if request.action == "list":
        print_listing(request, as_json=args.json)
        return 0
    if request.runtime == "codex" and request.scope == "workspace":
        completed = runner(build_project_profile_command(request, args))
        return int(completed.returncode)
    if request.action == "status":
        print_status(read_status(request), request, as_json=args.json)
        return 0
    if request.action == INTERNAL_ACTION:
        path = record_manifest(request, args)
        if args.json:
            print(
                json.dumps(
                    {"dry_run": bool(args.dry_run), "manifest": path.as_posix()},
                    sort_keys=True,
                )
            )
        elif args.dry_run:
            print(f"Would record runtime profile manifest: {path}")
        else:
            print(f"Recorded runtime profile manifest: {path}")
        return 0
    command = build_install_command(request, args)
    completed = runner(command)
    return int(completed.returncode)


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    try:
        args = parser.parse_args(_normalize_compat_args(list(argv if argv is not None else sys.argv[1:])))
        request = resolve_request(args)
        return execute(args, request)
    except (ProfileError, OSError) as exc:
        print(f"agent-profile: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
